// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAnalyticsEventsByFamily = `-- name: CountAnalyticsEventsByFamily :one
SELECT COUNT(*) FROM analytics_events
WHERE marketplace_account_id = $1 AND family = $2
`

type CountAnalyticsEventsByFamilyParams struct {
	MarketplaceAccountID uuid.UUID
	Family               string
}

func (q *Queries) CountAnalyticsEventsByFamily(ctx context.Context, arg CountAnalyticsEventsByFamilyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalyticsEventsByFamily, arg.MarketplaceAccountID, arg.Family)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAnalyticsEvent = `-- name: InsertAnalyticsEvent :one

INSERT INTO analytics_events (
    organization_id, marketplace_account_id, entity_id,
    locale, region, currency_contract_version, source_surface, occurred_at,
    family, name, attributes, dedup_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12::text)
ON CONFLICT (marketplace_account_id, dedup_key) WHERE dedup_key IS NOT NULL
DO NOTHING
RETURNING id, organization_id, marketplace_account_id, entity_id, locale, region, currency_contract_version, source_surface, occurred_at, family, name, attributes, created_at, dedup_key
`

type InsertAnalyticsEventParams struct {
	OrganizationID          uuid.UUID
	MarketplaceAccountID    uuid.UUID
	EntityID                uuid.UUID
	Locale                  string
	Region                  string
	CurrencyContractVersion string
	SourceSurface           string
	OccurredAt              time.Time
	Family                  string
	Name                    string
	Attributes              []byte
	DedupKey                string
}

// Analytics event queries (PRD §18). analytics_events is APPEND-ONLY: INSERT and
// SELECT only — there is deliberately NO UPDATE/DELETE query. Every insert carries
// the FULL §18 envelope; the columns are NOT NULL, so a missing field cannot be
// persisted (envelope completeness is structural).
// EVENT DEDUPLICATION (§4.6 never-cut, issue #111): dedup_key is the stable key of
// the producing lifecycle transition. The ACCOUNT-SCOPED partial unique index
// (migration 0045) is the arbiter, so a retried emission of the SAME business fact
// SUPPRESSES itself instead of writing a second row. DO NOTHING — never DO UPDATE:
// analytics_events is APPEND-ONLY, so a duplicate is dropped, never merged. When the
// row is suppressed no row is returned, i.e. pgx.ErrNoRows, which the caller reads as
// "already recorded" (an idempotent success), NOT as a failure.
// The key is cast to text so it can never be inserted NULL through this query: NULL
// is reserved for rows written before the key existed.
func (q *Queries) InsertAnalyticsEvent(ctx context.Context, arg InsertAnalyticsEventParams) (AnalyticsEvent, error) {
	row := q.db.QueryRow(ctx, insertAnalyticsEvent,
		arg.OrganizationID,
		arg.MarketplaceAccountID,
		arg.EntityID,
		arg.Locale,
		arg.Region,
		arg.CurrencyContractVersion,
		arg.SourceSurface,
		arg.OccurredAt,
		arg.Family,
		arg.Name,
		arg.Attributes,
		arg.DedupKey,
	)
	var i AnalyticsEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarketplaceAccountID,
		&i.EntityID,
		&i.Locale,
		&i.Region,
		&i.CurrencyContractVersion,
		&i.SourceSurface,
		&i.OccurredAt,
		&i.Family,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
		&i.DedupKey,
	)
	return i, err
}

const listAnalyticsEventsByFamily = `-- name: ListAnalyticsEventsByFamily :many
SELECT id, organization_id, marketplace_account_id, entity_id, locale, region, currency_contract_version, source_surface, occurred_at, family, name, attributes, created_at, dedup_key FROM analytics_events
WHERE marketplace_account_id = $1 AND family = $2
ORDER BY occurred_at DESC, id
`

type ListAnalyticsEventsByFamilyParams struct {
	MarketplaceAccountID uuid.UUID
	Family               string
}

// Events of one family for an account, newest first (dashboard/read path).
func (q *Queries) ListAnalyticsEventsByFamily(ctx context.Context, arg ListAnalyticsEventsByFamilyParams) ([]AnalyticsEvent, error) {
	rows, err := q.db.Query(ctx, listAnalyticsEventsByFamily, arg.MarketplaceAccountID, arg.Family)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsEvent{}
	for rows.Next() {
		var i AnalyticsEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarketplaceAccountID,
			&i.EntityID,
			&i.Locale,
			&i.Region,
			&i.CurrencyContractVersion,
			&i.SourceSurface,
			&i.OccurredAt,
			&i.Family,
			&i.Name,
			&i.Attributes,
			&i.CreatedAt,
			&i.DedupKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
