// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceApprovalCardState = `-- name: AdvanceApprovalCardState :one
UPDATE approval_cards
SET state = $3
WHERE id = $1 AND state = $2
RETURNING id, recommendation_id, marketplace_account_id, lineage_id, version, action_id, parameter_version, context_version, policy_version, cost_profile_version, evidence_versions, idempotency_key, state, price_mantissa, price_currency, price_exponent, expires_at, created_at
`

type AdvanceApprovalCardStateParams struct {
	ID      uuid.UUID
	State   string
	State_2 string
}

// FROM-guarded §8.4 transition on the current-state projection. The WHERE clause
// is the optimistic guard: only a card still in from_state advances; a card that
// already moved matches nothing and returns no row (the service treats that as a
// rejected transition — no blind overwrite). The append-only history row is
// inserted separately in the same transaction (AppendApprovalCardState).
func (q *Queries) AdvanceApprovalCardState(ctx context.Context, arg AdvanceApprovalCardStateParams) (ApprovalCard, error) {
	row := q.db.QueryRow(ctx, advanceApprovalCardState, arg.ID, arg.State, arg.State_2)
	var i ApprovalCard
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.MarketplaceAccountID,
		&i.LineageID,
		&i.Version,
		&i.ActionID,
		&i.ParameterVersion,
		&i.ContextVersion,
		&i.PolicyVersion,
		&i.CostProfileVersion,
		&i.EvidenceVersions,
		&i.IdempotencyKey,
		&i.State,
		&i.PriceMantissa,
		&i.PriceCurrency,
		&i.PriceExponent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const appendApprovalCardState = `-- name: AppendApprovalCardState :one
INSERT INTO approval_card_states (
    card_id, card_version, from_state, to_state, reason
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, card_id, card_version, from_state, to_state, reason, occurred_at
`

type AppendApprovalCardStateParams struct {
	CardID      uuid.UUID
	CardVersion int32
	FromState   pgtype.Text
	ToState     string
	Reason      string
}

// APPEND-ONLY §8.4 history. One row per state change; INSERT only.
func (q *Queries) AppendApprovalCardState(ctx context.Context, arg AppendApprovalCardStateParams) (ApprovalCardState, error) {
	row := q.db.QueryRow(ctx, appendApprovalCardState,
		arg.CardID,
		arg.CardVersion,
		arg.FromState,
		arg.ToState,
		arg.Reason,
	)
	var i ApprovalCardState
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.CardVersion,
		&i.FromState,
		&i.ToState,
		&i.Reason,
		&i.OccurredAt,
	)
	return i, err
}

const getApprovalCard = `-- name: GetApprovalCard :one
SELECT id, recommendation_id, marketplace_account_id, lineage_id, version, action_id, parameter_version, context_version, policy_version, cost_profile_version, evidence_versions, idempotency_key, state, price_mantissa, price_currency, price_exponent, expires_at, created_at FROM approval_cards WHERE id = $1
`

func (q *Queries) GetApprovalCard(ctx context.Context, id uuid.UUID) (ApprovalCard, error) {
	row := q.db.QueryRow(ctx, getApprovalCard, id)
	var i ApprovalCard
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.MarketplaceAccountID,
		&i.LineageID,
		&i.Version,
		&i.ActionID,
		&i.ParameterVersion,
		&i.ContextVersion,
		&i.PolicyVersion,
		&i.CostProfileVersion,
		&i.EvidenceVersions,
		&i.IdempotencyKey,
		&i.State,
		&i.PriceMantissa,
		&i.PriceCurrency,
		&i.PriceExponent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentApprovalCard = `-- name: GetCurrentApprovalCard :one
SELECT id, recommendation_id, marketplace_account_id, lineage_id, version, action_id, parameter_version, context_version, policy_version, cost_profile_version, evidence_versions, idempotency_key, state, price_mantissa, price_currency, price_exponent, expires_at, created_at FROM approval_cards
WHERE lineage_id = $1
ORDER BY version DESC
LIMIT 1
`

// The greatest-version card for a lineage (the live card version).
func (q *Queries) GetCurrentApprovalCard(ctx context.Context, lineageID uuid.UUID) (ApprovalCard, error) {
	row := q.db.QueryRow(ctx, getCurrentApprovalCard, lineageID)
	var i ApprovalCard
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.MarketplaceAccountID,
		&i.LineageID,
		&i.Version,
		&i.ActionID,
		&i.ParameterVersion,
		&i.ContextVersion,
		&i.PolicyVersion,
		&i.CostProfileVersion,
		&i.EvidenceVersions,
		&i.IdempotencyKey,
		&i.State,
		&i.PriceMantissa,
		&i.PriceCurrency,
		&i.PriceExponent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertApprovalCard = `-- name: InsertApprovalCard :one

INSERT INTO approval_cards (
    recommendation_id, marketplace_account_id, lineage_id, version,
    action_id, parameter_version, context_version, policy_version, cost_profile_version,
    evidence_versions, idempotency_key, state,
    price_mantissa, price_currency, price_exponent, expires_at
) VALUES (
    $1, $2, $3,
    (SELECT COALESCE(MAX(version), 0) + 1 FROM approval_cards WHERE lineage_id = $3),
    $4, $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14, $15
)
RETURNING id, recommendation_id, marketplace_account_id, lineage_id, version, action_id, parameter_version, context_version, policy_version, cost_profile_version, evidence_versions, idempotency_key, state, price_mantissa, price_currency, price_exponent, expires_at, created_at
`

type InsertApprovalCardParams struct {
	RecommendationID     uuid.UUID
	MarketplaceAccountID uuid.UUID
	LineageID            uuid.UUID
	ActionID             uuid.UUID
	ParameterVersion     int64
	ContextVersion       int64
	PolicyVersion        int64
	CostProfileVersion   int64
	EvidenceVersions     []byte
	IdempotencyKey       string
	State                string
	PriceMantissa        int64
	PriceCurrency        string
	PriceExponent        int16
	ExpiresAt            time.Time
}

// Approval card queries (PRD §7.5 APR-001, §8.4 state machine). Write discipline:
//   - approval_cards is APPEND-ONLY within a lineage (a price edit is a new
//     version). The `state` column is a CURRENT-state projection advanced by a
//     FROM-guarded UPDATE (a checked §8.4 transition, never a blind overwrite).
//   - approval_card_states is STRICTLY APPEND-ONLY: INSERT only, no UPDATE/DELETE.
//     It is the authoritative lifecycle history reconstructable for audit (AUD-001).
func (q *Queries) InsertApprovalCard(ctx context.Context, arg InsertApprovalCardParams) (ApprovalCard, error) {
	row := q.db.QueryRow(ctx, insertApprovalCard,
		arg.RecommendationID,
		arg.MarketplaceAccountID,
		arg.LineageID,
		arg.ActionID,
		arg.ParameterVersion,
		arg.ContextVersion,
		arg.PolicyVersion,
		arg.CostProfileVersion,
		arg.EvidenceVersions,
		arg.IdempotencyKey,
		arg.State,
		arg.PriceMantissa,
		arg.PriceCurrency,
		arg.PriceExponent,
		arg.ExpiresAt,
	)
	var i ApprovalCard
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.MarketplaceAccountID,
		&i.LineageID,
		&i.Version,
		&i.ActionID,
		&i.ParameterVersion,
		&i.ContextVersion,
		&i.PolicyVersion,
		&i.CostProfileVersion,
		&i.EvidenceVersions,
		&i.IdempotencyKey,
		&i.State,
		&i.PriceMantissa,
		&i.PriceCurrency,
		&i.PriceExponent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovalCardStates = `-- name: ListApprovalCardStates :many
SELECT id, card_id, card_version, from_state, to_state, reason, occurred_at FROM approval_card_states
WHERE card_id = $1
ORDER BY occurred_at, id
`

// The append-only lifecycle history for a card, in occurrence order (AUD-001).
func (q *Queries) ListApprovalCardStates(ctx context.Context, cardID uuid.UUID) ([]ApprovalCardState, error) {
	rows, err := q.db.Query(ctx, listApprovalCardStates, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalCardState{}
	for rows.Next() {
		var i ApprovalCardState
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.CardVersion,
			&i.FromState,
			&i.ToState,
			&i.Reason,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalCardsByAccount = `-- name: ListApprovalCardsByAccount :many
SELECT latest.id, latest.recommendation_id, latest.marketplace_account_id, latest.lineage_id, latest.version, latest.action_id, latest.parameter_version, latest.context_version, latest.policy_version, latest.cost_profile_version, latest.evidence_versions, latest.idempotency_key, latest.state, latest.price_mantissa, latest.price_currency, latest.price_exponent, latest.expires_at, latest.created_at FROM (
    SELECT DISTINCT ON (ac.lineage_id) ac.id, ac.recommendation_id, ac.marketplace_account_id, ac.lineage_id, ac.version, ac.action_id, ac.parameter_version, ac.context_version, ac.policy_version, ac.cost_profile_version, ac.evidence_versions, ac.idempotency_key, ac.state, ac.price_mantissa, ac.price_currency, ac.price_exponent, ac.expires_at, ac.created_at
    FROM approval_cards ac
    WHERE ac.marketplace_account_id = $1
    ORDER BY ac.lineage_id, ac.version DESC
) latest
ORDER BY latest.created_at DESC
LIMIT $2
`

type ListApprovalCardsByAccountParams struct {
	MarketplaceAccountID uuid.UUID
	Limit                int32
}

// Grouped multi-row actions queue for an account (PD-3 item 5, S37), current
// (greatest) version per lineage, newest first. State filtering is done in Go
// (internal/recommendation) to keep this one simple, always-safe read.
func (q *Queries) ListApprovalCardsByAccount(ctx context.Context, arg ListApprovalCardsByAccountParams) ([]ApprovalCard, error) {
	rows, err := q.db.Query(ctx, listApprovalCardsByAccount, arg.MarketplaceAccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalCard{}
	for rows.Next() {
		var i ApprovalCard
		if err := rows.Scan(
			&i.ID,
			&i.RecommendationID,
			&i.MarketplaceAccountID,
			&i.LineageID,
			&i.Version,
			&i.ActionID,
			&i.ParameterVersion,
			&i.ContextVersion,
			&i.PolicyVersion,
			&i.CostProfileVersion,
			&i.EvidenceVersions,
			&i.IdempotencyKey,
			&i.State,
			&i.PriceMantissa,
			&i.PriceCurrency,
			&i.PriceExponent,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCardsForVariant = `-- name: ListLiveCardsForVariant :many
SELECT ac.id, ac.recommendation_id, ac.marketplace_account_id, ac.lineage_id, ac.version, ac.action_id, ac.parameter_version, ac.context_version, ac.policy_version, ac.cost_profile_version, ac.evidence_versions, ac.idempotency_key, ac.state, ac.price_mantissa, ac.price_currency, ac.price_exponent, ac.expires_at, ac.created_at FROM approval_cards ac
JOIN recommendations r ON r.id = ac.recommendation_id
WHERE r.variant_id = $1
  AND ac.state IN ('draft', 'ready_for_review', 'awaiting_confirmation', 'approved', 'revalidating')
ORDER BY ac.created_at
`

// Live (control-bearing or revalidating) cards for a variant. Used by the
// identity-reopen consumer to expire dependent recommendations (§16): a reopened
// mapping invalidates any card whose control could still authorize a write.
func (q *Queries) ListLiveCardsForVariant(ctx context.Context, variantID uuid.UUID) ([]ApprovalCard, error) {
	rows, err := q.db.Query(ctx, listLiveCardsForVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalCard{}
	for rows.Next() {
		var i ApprovalCard
		if err := rows.Scan(
			&i.ID,
			&i.RecommendationID,
			&i.MarketplaceAccountID,
			&i.LineageID,
			&i.Version,
			&i.ActionID,
			&i.ParameterVersion,
			&i.ContextVersion,
			&i.PolicyVersion,
			&i.CostProfileVersion,
			&i.EvidenceVersions,
			&i.IdempotencyKey,
			&i.State,
			&i.PriceMantissa,
			&i.PriceCurrency,
			&i.PriceExponent,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
