// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditRecord = `-- name: AppendAuditRecord :one

INSERT INTO audit_records (
    action_id, card_id, marketplace_account_id, event_type,
    actor, actor_role, surface,
    context_version, parameter_version, policy_version, cost_profile_version,
    evidence_versions, card_snapshot, detail, terminal_state
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15
)
RETURNING id, action_id, card_id, marketplace_account_id, event_type, actor, actor_role, surface, context_version, parameter_version, policy_version, cost_profile_version, evidence_versions, card_snapshot, detail, terminal_state, occurred_at
`

type AppendAuditRecordParams struct {
	ActionID             uuid.UUID
	CardID               pgtype.UUID
	MarketplaceAccountID pgtype.UUID
	EventType            string
	Actor                string
	ActorRole            string
	Surface              string
	ContextVersion       int64
	ParameterVersion     int64
	PolicyVersion        int64
	CostProfileVersion   int64
	EvidenceVersions     []byte
	CardSnapshot         []byte
	Detail               []byte
	TerminalState        string
}

// Audit trail queries (PRD §7.5 AUD-001). audit_records is STRICTLY APPEND-ONLY:
// INSERT/SELECT only — there is deliberately NO UPDATE/DELETE query. A historical
// action is reproducible from these rows (plus approval_card_states and
// action_executions) WITHOUT the chat transcript (transcript-independent audit).
func (q *Queries) AppendAuditRecord(ctx context.Context, arg AppendAuditRecordParams) (AuditRecord, error) {
	row := q.db.QueryRow(ctx, appendAuditRecord,
		arg.ActionID,
		arg.CardID,
		arg.MarketplaceAccountID,
		arg.EventType,
		arg.Actor,
		arg.ActorRole,
		arg.Surface,
		arg.ContextVersion,
		arg.ParameterVersion,
		arg.PolicyVersion,
		arg.CostProfileVersion,
		arg.EvidenceVersions,
		arg.CardSnapshot,
		arg.Detail,
		arg.TerminalState,
	)
	var i AuditRecord
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.CardID,
		&i.MarketplaceAccountID,
		&i.EventType,
		&i.Actor,
		&i.ActorRole,
		&i.Surface,
		&i.ContextVersion,
		&i.ParameterVersion,
		&i.PolicyVersion,
		&i.CostProfileVersion,
		&i.EvidenceVersions,
		&i.CardSnapshot,
		&i.Detail,
		&i.TerminalState,
		&i.OccurredAt,
	)
	return i, err
}

const listAuditRecordsForAction = `-- name: ListAuditRecordsForAction :many
SELECT id, action_id, card_id, marketplace_account_id, event_type, actor, actor_role, surface, context_version, parameter_version, policy_version, cost_profile_version, evidence_versions, card_snapshot, detail, terminal_state, occurred_at FROM audit_records
WHERE action_id = $1
ORDER BY occurred_at, id
`

// The complete append-only audit trail for an action, in occurrence order. This
// is the reproduction read (AUD-001): it joins NOTHING in the conversation tables,
// so deleting a conversation leaves the trail intact.
func (q *Queries) ListAuditRecordsForAction(ctx context.Context, actionID uuid.UUID) ([]AuditRecord, error) {
	rows, err := q.db.Query(ctx, listAuditRecordsForAction, actionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditRecord{}
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.CardID,
			&i.MarketplaceAccountID,
			&i.EventType,
			&i.Actor,
			&i.ActorRole,
			&i.Surface,
			&i.ContextVersion,
			&i.ParameterVersion,
			&i.PolicyVersion,
			&i.CostProfileVersion,
			&i.EvidenceVersions,
			&i.CardSnapshot,
			&i.Detail,
			&i.TerminalState,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
