// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	TokenHash string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

// Open a server-side session. token_hash is the SHA-256 of the opaque cookie
// token; the raw token never reaches the database.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= now()
`

// Sweep expired sessions.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = $1
`

// Close a single session (logout). Idempotent: deleting an absent row is a no-op.
func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions
WHERE user_id = $1
`

// Revoke every session for a user (role change / password rotation).
func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT s.token_hash, s.expires_at,
       u.id AS user_id, u.organization_id, u.email, u.role
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionUserRow struct {
	TokenHash      string
	ExpiresAt      time.Time
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	Role           string
}

// Resolve a live session to its principal (user + role + organization). Rows
// at/after expiry are excluded, so an expired cookie fails closed.
func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UserID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getUserCredential = `-- name: GetUserCredential :one
SELECT user_id, password_hash, created_at, updated_at FROM user_credentials
WHERE user_id = $1
`

func (q *Queries) GetUserCredential(ctx context.Context, userID uuid.UUID) (UserCredential, error) {
	row := q.db.QueryRow(ctx, getUserCredential, userID)
	var i UserCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserCredential = `-- name: UpsertUserCredential :exec
INSERT INTO user_credentials (user_id, password_hash)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    updated_at    = now()
`

type UpsertUserCredentialParams struct {
	UserID       uuid.UUID
	PasswordHash string
}

// Set or rotate a user's argon2id password hash. Current-state upsert: a
// password change replaces the hash in place.
func (q *Queries) UpsertUserCredential(ctx context.Context, arg UpsertUserCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertUserCredential, arg.UserID, arg.PasswordHash)
	return err
}
