// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceCatalogSyncRun = `-- name: AdvanceCatalogSyncRun :one
UPDATE catalog_sync_runs SET
    next_page        = $2,
    pages_done       = $3,
    total_pages      = $4,
    total_rows       = $5,
    items_seen       = items_seen + $6,
    records_inserted = records_inserted + $7,
    records_updated  = records_updated + $8,
    updated_at       = now()
WHERE id = $1
RETURNING id, marketplace_account_id, kind, status, next_page, pages_done, total_pages, total_rows, items_seen, records_inserted, records_updated, drift_count, error, started_at, updated_at, completed_at
`

type AdvanceCatalogSyncRunParams struct {
	ID              uuid.UUID
	NextPage        int32
	PagesDone       int32
	TotalPages      int32
	TotalRows       int32
	ItemsSeen       int32
	RecordsInserted int32
	RecordsUpdated  int32
}

// Persist page progress after a page is fully applied. next_page is the resume
// cursor an interrupted import continues from; counters accumulate.
func (q *Queries) AdvanceCatalogSyncRun(ctx context.Context, arg AdvanceCatalogSyncRunParams) (CatalogSyncRun, error) {
	row := q.db.QueryRow(ctx, advanceCatalogSyncRun,
		arg.ID,
		arg.NextPage,
		arg.PagesDone,
		arg.TotalPages,
		arg.TotalRows,
		arg.ItemsSeen,
		arg.RecordsInserted,
		arg.RecordsUpdated,
	)
	var i CatalogSyncRun
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Kind,
		&i.Status,
		&i.NextPage,
		&i.PagesDone,
		&i.TotalPages,
		&i.TotalRows,
		&i.ItemsSeen,
		&i.RecordsInserted,
		&i.RecordsUpdated,
		&i.DriftCount,
		&i.Error,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeCatalogSyncRun = `-- name: CompleteCatalogSyncRun :one
UPDATE catalog_sync_runs SET
    status       = 'completed',
    drift_count  = $2,
    completed_at = now(),
    updated_at   = now()
WHERE id = $1
RETURNING id, marketplace_account_id, kind, status, next_page, pages_done, total_pages, total_rows, items_seen, records_inserted, records_updated, drift_count, error, started_at, updated_at, completed_at
`

type CompleteCatalogSyncRunParams struct {
	ID         uuid.UUID
	DriftCount int32
}

func (q *Queries) CompleteCatalogSyncRun(ctx context.Context, arg CompleteCatalogSyncRunParams) (CatalogSyncRun, error) {
	row := q.db.QueryRow(ctx, completeCatalogSyncRun, arg.ID, arg.DriftCount)
	var i CatalogSyncRun
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Kind,
		&i.Status,
		&i.NextPage,
		&i.PagesDone,
		&i.TotalPages,
		&i.TotalRows,
		&i.ItemsSeen,
		&i.RecordsInserted,
		&i.RecordsUpdated,
		&i.DriftCount,
		&i.Error,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countCatalogSnapshots = `-- name: CountCatalogSnapshots :one
SELECT count(*) FROM catalog_payload_snapshots WHERE marketplace_account_id = $1
`

func (q *Queries) CountCatalogSnapshots(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogSnapshots, marketplaceAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDriftedOwnedOffers = `-- name: CountDriftedOwnedOffers :one
SELECT count(*) FROM owned_offers
WHERE marketplace_account_id = $1
  AND (last_seen_run_id IS DISTINCT FROM $2)
`

type CountDriftedOwnedOffersParams struct {
	MarketplaceAccountID uuid.UUID
	LastSeenRunID        pgtype.UUID
}

// Reconciliation: owned offers not observed by the given run are drift (missing
// from the latest full fetch). Reported, never silently deleted.
func (q *Queries) CountDriftedOwnedOffers(ctx context.Context, arg CountDriftedOwnedOffersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDriftedOwnedOffers, arg.MarketplaceAccountID, arg.LastSeenRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListings = `-- name: CountListings :one
SELECT count(*) FROM listings WHERE marketplace_account_id = $1
`

func (q *Queries) CountListings(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countListings, marketplaceAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnedOffers = `-- name: CountOwnedOffers :one
SELECT count(*) FROM owned_offers WHERE marketplace_account_id = $1
`

func (q *Queries) CountOwnedOffers(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedOffers, marketplaceAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products WHERE marketplace_account_id = $1
`

func (q *Queries) CountProducts(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, marketplaceAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVariants = `-- name: CountVariants :one
SELECT count(*) FROM variants WHERE marketplace_account_id = $1
`

func (q *Queries) CountVariants(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVariants, marketplaceAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCatalogSyncRun = `-- name: CreateCatalogSyncRun :one
INSERT INTO catalog_sync_runs (marketplace_account_id, kind, status, next_page)
VALUES ($1, $2, 'running', 1)
RETURNING id, marketplace_account_id, kind, status, next_page, pages_done, total_pages, total_rows, items_seen, records_inserted, records_updated, drift_count, error, started_at, updated_at, completed_at
`

type CreateCatalogSyncRunParams struct {
	MarketplaceAccountID uuid.UUID
	Kind                 string
}

func (q *Queries) CreateCatalogSyncRun(ctx context.Context, arg CreateCatalogSyncRunParams) (CatalogSyncRun, error) {
	row := q.db.QueryRow(ctx, createCatalogSyncRun, arg.MarketplaceAccountID, arg.Kind)
	var i CatalogSyncRun
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Kind,
		&i.Status,
		&i.NextPage,
		&i.PagesDone,
		&i.TotalPages,
		&i.TotalRows,
		&i.ItemsSeen,
		&i.RecordsInserted,
		&i.RecordsUpdated,
		&i.DriftCount,
		&i.Error,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failCatalogSyncRun = `-- name: FailCatalogSyncRun :one
UPDATE catalog_sync_runs SET
    status     = 'failed',
    error      = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, marketplace_account_id, kind, status, next_page, pages_done, total_pages, total_rows, items_seen, records_inserted, records_updated, drift_count, error, started_at, updated_at, completed_at
`

type FailCatalogSyncRunParams struct {
	ID    uuid.UUID
	Error string
}

func (q *Queries) FailCatalogSyncRun(ctx context.Context, arg FailCatalogSyncRunParams) (CatalogSyncRun, error) {
	row := q.db.QueryRow(ctx, failCatalogSyncRun, arg.ID, arg.Error)
	var i CatalogSyncRun
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Kind,
		&i.Status,
		&i.NextPage,
		&i.PagesDone,
		&i.TotalPages,
		&i.TotalRows,
		&i.ItemsSeen,
		&i.RecordsInserted,
		&i.RecordsUpdated,
		&i.DriftCount,
		&i.Error,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCatalogSyncRun = `-- name: GetCatalogSyncRun :one
SELECT id, marketplace_account_id, kind, status, next_page, pages_done, total_pages, total_rows, items_seen, records_inserted, records_updated, drift_count, error, started_at, updated_at, completed_at FROM catalog_sync_runs WHERE id = $1
`

func (q *Queries) GetCatalogSyncRun(ctx context.Context, id uuid.UUID) (CatalogSyncRun, error) {
	row := q.db.QueryRow(ctx, getCatalogSyncRun, id)
	var i CatalogSyncRun
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Kind,
		&i.Status,
		&i.NextPage,
		&i.PagesDone,
		&i.TotalPages,
		&i.TotalRows,
		&i.ItemsSeen,
		&i.RecordsInserted,
		&i.RecordsUpdated,
		&i.DriftCount,
		&i.Error,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLatestCatalogSyncRun = `-- name: GetLatestCatalogSyncRun :one
SELECT id, marketplace_account_id, kind, status, next_page, pages_done, total_pages, total_rows, items_seen, records_inserted, records_updated, drift_count, error, started_at, updated_at, completed_at FROM catalog_sync_runs
WHERE marketplace_account_id = $1
ORDER BY started_at DESC
LIMIT 1
`

// Backs the sync-status view the UI reads (data persisted for a later UI step).
func (q *Queries) GetLatestCatalogSyncRun(ctx context.Context, marketplaceAccountID uuid.UUID) (CatalogSyncRun, error) {
	row := q.db.QueryRow(ctx, getLatestCatalogSyncRun, marketplaceAccountID)
	var i CatalogSyncRun
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Kind,
		&i.Status,
		&i.NextPage,
		&i.PagesDone,
		&i.TotalPages,
		&i.TotalRows,
		&i.ItemsSeen,
		&i.RecordsInserted,
		&i.RecordsUpdated,
		&i.DriftCount,
		&i.Error,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertCatalogPayloadSnapshot = `-- name: InsertCatalogPayloadSnapshot :exec
INSERT INTO catalog_payload_snapshots (
    marketplace_account_id, sync_run_id, native_variant_id, page, payload
) VALUES ($1, $2, $3, $4, $5)
`

type InsertCatalogPayloadSnapshotParams struct {
	MarketplaceAccountID uuid.UUID
	SyncRunID            uuid.UUID
	NativeVariantID      int64
	Page                 int32
	Payload              []byte
}

// APPEND-ONLY: the only write path to this table is INSERT. Raw item JSON kept
// verbatim as evidence (plan §4.7). No UPDATE/DELETE query exists by design.
func (q *Queries) InsertCatalogPayloadSnapshot(ctx context.Context, arg InsertCatalogPayloadSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertCatalogPayloadSnapshot,
		arg.MarketplaceAccountID,
		arg.SyncRunID,
		arg.NativeVariantID,
		arg.Page,
		arg.Payload,
	)
	return err
}

const listRecentCatalogSyncOutcomes = `-- name: ListRecentCatalogSyncOutcomes :many
SELECT id, marketplace_account_id, status, error
FROM catalog_sync_runs
ORDER BY marketplace_account_id, started_at DESC
`

type ListRecentCatalogSyncOutcomesRow struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	Status               string
	Error                string
}

// READ-ONLY durable ordered sync-run state for restart re-derivation of the §20.1
// connector-sync failure streak (issue #146). Newest-first per account; the
// telemetry seam (catalog.deriveStreaks) counts the leading consecutive non-success
// runs since the last completed run. The run id is carried so the seam can re-seed
// its per-run idempotency guard: a run still being retried after a restart is never
// double-counted on the live path. Pure SELECT: never mutates a run row.
func (q *Queries) ListRecentCatalogSyncOutcomes(ctx context.Context) ([]ListRecentCatalogSyncOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listRecentCatalogSyncOutcomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentCatalogSyncOutcomesRow{}
	for rows.Next() {
		var i ListRecentCatalogSyncOutcomesRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCatalogSyncRunError = `-- name: SetCatalogSyncRunError :one
UPDATE catalog_sync_runs SET
    error      = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, marketplace_account_id, kind, status, next_page, pages_done, total_pages, total_rows, items_seen, records_inserted, records_updated, drift_count, error, started_at, updated_at, completed_at
`

type SetCatalogSyncRunErrorParams struct {
	ID    uuid.UUID
	Error string
}

// Record a retryable error WITHOUT marking the run failed: status stays 'running'
// and next_page is untouched, so a retry (River backoff) resumes from the same
// page. Used for transient fetch/apply faults (pagination fault, parser drift).
func (q *Queries) SetCatalogSyncRunError(ctx context.Context, arg SetCatalogSyncRunErrorParams) (CatalogSyncRun, error) {
	row := q.db.QueryRow(ctx, setCatalogSyncRunError, arg.ID, arg.Error)
	var i CatalogSyncRun
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Kind,
		&i.Status,
		&i.NextPage,
		&i.PagesDone,
		&i.TotalPages,
		&i.TotalRows,
		&i.ItemsSeen,
		&i.RecordsInserted,
		&i.RecordsUpdated,
		&i.DriftCount,
		&i.Error,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const upsertListing = `-- name: UpsertListing :one
INSERT INTO listings (
    marketplace_account_id, variant_id, native_listing_id, selling_channel, product_url, updated_at
) VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (marketplace_account_id, native_listing_id) DO UPDATE SET
    variant_id      = EXCLUDED.variant_id,
    selling_channel = EXCLUDED.selling_channel,
    product_url     = EXCLUDED.product_url,
    updated_at      = now()
RETURNING id, (xmax = 0) AS inserted
`

type UpsertListingParams struct {
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	NativeListingID      int64
	SellingChannel       string
	ProductUrl           string
}

type UpsertListingRow struct {
	ID       uuid.UUID
	Inserted bool
}

func (q *Queries) UpsertListing(ctx context.Context, arg UpsertListingParams) (UpsertListingRow, error) {
	row := q.db.QueryRow(ctx, upsertListing,
		arg.MarketplaceAccountID,
		arg.VariantID,
		arg.NativeListingID,
		arg.SellingChannel,
		arg.ProductUrl,
	)
	var i UpsertListingRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}

const upsertOwnedOffer = `-- name: UpsertOwnedOffer :one
INSERT INTO owned_offers (
    marketplace_account_id, variant_id, native_variant_id,
    price_raw_text, price_raw_value, price_raw_unit,
    seller_stock, warehouse_stock,
    last_seen_run_id, last_seen_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now())
ON CONFLICT (marketplace_account_id, native_variant_id) DO UPDATE SET
    variant_id       = EXCLUDED.variant_id,
    price_raw_text   = EXCLUDED.price_raw_text,
    price_raw_value  = EXCLUDED.price_raw_value,
    price_raw_unit   = EXCLUDED.price_raw_unit,
    seller_stock     = EXCLUDED.seller_stock,
    warehouse_stock  = EXCLUDED.warehouse_stock,
    last_seen_run_id = EXCLUDED.last_seen_run_id,
    last_seen_at     = now(),
    updated_at       = now()
RETURNING id, (xmax = 0) AS inserted
`

type UpsertOwnedOfferParams struct {
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	NativeVariantID      int64
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	SellerStock          pgtype.Int8
	WarehouseStock       pgtype.Int8
	LastSeenRunID        pgtype.UUID
}

type UpsertOwnedOfferRow struct {
	ID       uuid.UUID
	Inserted bool
}

// Money quarantine (§9.1): price is stored ONLY as raw evidence text; there is no
// Money/currency column and no conversion path. last_seen_run_id stamps the run
// that observed this offer for the reconciliation drift pass.
func (q *Queries) UpsertOwnedOffer(ctx context.Context, arg UpsertOwnedOfferParams) (UpsertOwnedOfferRow, error) {
	row := q.db.QueryRow(ctx, upsertOwnedOffer,
		arg.MarketplaceAccountID,
		arg.VariantID,
		arg.NativeVariantID,
		arg.PriceRawText,
		arg.PriceRawValue,
		arg.PriceRawUnit,
		arg.SellerStock,
		arg.WarehouseStock,
		arg.LastSeenRunID,
	)
	var i UpsertOwnedOfferRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}

const upsertProduct = `-- name: UpsertProduct :one

INSERT INTO products (
    marketplace_account_id, native_product_id, title, brand_title, product_url, updated_at
) VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (marketplace_account_id, native_product_id) DO UPDATE SET
    title       = EXCLUDED.title,
    brand_title = EXCLUDED.brand_title,
    product_url = EXCLUDED.product_url,
    updated_at  = now()
RETURNING id, (xmax = 0) AS inserted
`

type UpsertProductParams struct {
	MarketplaceAccountID uuid.UUID
	NativeProductID      int64
	Title                string
	BrandTitle           string
	ProductUrl           string
}

type UpsertProductRow struct {
	ID       uuid.UUID
	Inserted bool
}

// Catalog + owned-offer sync queries (S10, CAT-001, ACC-004/ACC-005).
// Every canonical upsert conflicts on the stable DK native identifier so a
// repeated or REORDERED payload replay updates in place and never inserts a
// duplicate. The `(xmax = 0) AS inserted` flag distinguishes an INSERT from an
// UPDATE (Postgres system-column idiom) so the sync run can count new vs changed
// records without a second round trip.
func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (UpsertProductRow, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.MarketplaceAccountID,
		arg.NativeProductID,
		arg.Title,
		arg.BrandTitle,
		arg.ProductUrl,
	)
	var i UpsertProductRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}

const upsertVariant = `-- name: UpsertVariant :one
INSERT INTO variants (
    marketplace_account_id, product_id, native_variant_id, native_product_id, supplier_code, title, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (marketplace_account_id, native_variant_id) DO UPDATE SET
    product_id        = EXCLUDED.product_id,
    native_product_id = EXCLUDED.native_product_id,
    supplier_code     = EXCLUDED.supplier_code,
    title             = EXCLUDED.title,
    updated_at        = now()
RETURNING id, (xmax = 0) AS inserted
`

type UpsertVariantParams struct {
	MarketplaceAccountID uuid.UUID
	ProductID            uuid.UUID
	NativeVariantID      int64
	NativeProductID      int64
	SupplierCode         string
	Title                string
}

type UpsertVariantRow struct {
	ID       uuid.UUID
	Inserted bool
}

func (q *Queries) UpsertVariant(ctx context.Context, arg UpsertVariantParams) (UpsertVariantRow, error) {
	row := q.db.QueryRow(ctx, upsertVariant,
		arg.MarketplaceAccountID,
		arg.ProductID,
		arg.NativeVariantID,
		arg.NativeProductID,
		arg.SupplierCode,
		arg.Title,
	)
	var i UpsertVariantRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}
