// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connector.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const disconnectConnectorConnection = `-- name: DisconnectConnectorConnection :one
UPDATE connector_connections SET
    connection_state     = 'disconnected',
    access_token_sealed  = NULL,
    refresh_token_sealed = NULL,
    access_expires_at    = NULL,
    refresh_expires_at   = NULL,
    key_version          = 0,
    updated_at           = now()
WHERE marketplace_account_id = $1
RETURNING id, marketplace_account_id, connection_state, access_token_sealed, refresh_token_sealed, access_expires_at, refresh_expires_at, key_version, created_at, updated_at
`

// Sever the connection and purge sealed tokens (ACC-001). Idempotent.
func (q *Queries) DisconnectConnectorConnection(ctx context.Context, marketplaceAccountID uuid.UUID) (ConnectorConnection, error) {
	row := q.db.QueryRow(ctx, disconnectConnectorConnection, marketplaceAccountID)
	var i ConnectorConnection
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.ConnectionState,
		&i.AccessTokenSealed,
		&i.RefreshTokenSealed,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorConnection = `-- name: GetConnectorConnection :one
SELECT id, marketplace_account_id, connection_state, access_token_sealed, refresh_token_sealed, access_expires_at, refresh_expires_at, key_version, created_at, updated_at FROM connector_connections
WHERE marketplace_account_id = $1
`

func (q *Queries) GetConnectorConnection(ctx context.Context, marketplaceAccountID uuid.UUID) (ConnectorConnection, error) {
	row := q.db.QueryRow(ctx, getConnectorConnection, marketplaceAccountID)
	var i ConnectorConnection
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.ConnectionState,
		&i.AccessTokenSealed,
		&i.RefreshTokenSealed,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectorCapabilities = `-- name: ListConnectorCapabilities :many
SELECT id, marketplace_account_id, capability, status, detail, last_verified_at, created_at, updated_at FROM connector_capabilities
WHERE marketplace_account_id = $1
ORDER BY capability
`

func (q *Queries) ListConnectorCapabilities(ctx context.Context, marketplaceAccountID uuid.UUID) ([]ConnectorCapability, error) {
	rows, err := q.db.Query(ctx, listConnectorCapabilities, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorCapability{}
	for rows.Next() {
		var i ConnectorCapability
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.Capability,
			&i.Status,
			&i.Detail,
			&i.LastVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetConnectorCapability = `-- name: ResetConnectorCapability :exec
UPDATE connector_capabilities SET
    status           = 'unknown',
    detail           = NULL,
    last_verified_at = NULL,
    updated_at       = now()
WHERE marketplace_account_id = $1
`

// Return a capability to 'unknown' (disconnect). Clears last_verified_at so a
// stale verification can never read as current.
func (q *Queries) ResetConnectorCapability(ctx context.Context, marketplaceAccountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetConnectorCapability, marketplaceAccountID)
	return err
}

const seedConnectorCapability = `-- name: SeedConnectorCapability :exec
INSERT INTO connector_capabilities (marketplace_account_id, capability, status)
VALUES ($1, $2, 'unknown')
ON CONFLICT (marketplace_account_id, capability) DO NOTHING
`

type SeedConnectorCapabilityParams struct {
	MarketplaceAccountID uuid.UUID
	Capability           string
}

// Insert a capability at 'unknown' if absent; leave an existing row untouched so
// a prior probe result is not clobbered by a re-seed (capability-gating invariant).
func (q *Queries) SeedConnectorCapability(ctx context.Context, arg SeedConnectorCapabilityParams) error {
	_, err := q.db.Exec(ctx, seedConnectorCapability, arg.MarketplaceAccountID, arg.Capability)
	return err
}

const setConnectorCapabilityStatus = `-- name: SetConnectorCapabilityStatus :one
UPDATE connector_capabilities SET
    status           = $3,
    detail           = $4,
    last_verified_at = $5,
    updated_at       = now()
WHERE marketplace_account_id = $1 AND capability = $2
RETURNING id, marketplace_account_id, capability, status, detail, last_verified_at, created_at, updated_at
`

type SetConnectorCapabilityStatusParams struct {
	MarketplaceAccountID uuid.UUID
	Capability           string
	Status               string
	Detail               pgtype.Text
	LastVerifiedAt       pgtype.Timestamptz
}

// Record a probe result. Only a probe calls this; status is set explicitly and
// last_verified_at stamps when it was determined.
func (q *Queries) SetConnectorCapabilityStatus(ctx context.Context, arg SetConnectorCapabilityStatusParams) (ConnectorCapability, error) {
	row := q.db.QueryRow(ctx, setConnectorCapabilityStatus,
		arg.MarketplaceAccountID,
		arg.Capability,
		arg.Status,
		arg.Detail,
		arg.LastVerifiedAt,
	)
	var i ConnectorCapability
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Capability,
		&i.Status,
		&i.Detail,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConnectorConnection = `-- name: UpsertConnectorConnection :one
INSERT INTO connector_connections (
    marketplace_account_id, connection_state,
    access_token_sealed, refresh_token_sealed,
    access_expires_at, refresh_expires_at, key_version, updated_at
) VALUES ($1, 'connected', $2, $3, $4, $5, $6, now())
ON CONFLICT (marketplace_account_id) DO UPDATE SET
    connection_state     = 'connected',
    access_token_sealed  = EXCLUDED.access_token_sealed,
    refresh_token_sealed = EXCLUDED.refresh_token_sealed,
    access_expires_at    = EXCLUDED.access_expires_at,
    refresh_expires_at   = EXCLUDED.refresh_expires_at,
    key_version          = EXCLUDED.key_version,
    updated_at           = now()
RETURNING id, marketplace_account_id, connection_state, access_token_sealed, refresh_token_sealed, access_expires_at, refresh_expires_at, key_version, created_at, updated_at
`

type UpsertConnectorConnectionParams struct {
	MarketplaceAccountID uuid.UUID
	AccessTokenSealed    []byte
	RefreshTokenSealed   []byte
	AccessExpiresAt      pgtype.Timestamptz
	RefreshExpiresAt     pgtype.Timestamptz
	KeyVersion           int32
}

// Establish or update the connection with sealed tokens (connect / refresh).
func (q *Queries) UpsertConnectorConnection(ctx context.Context, arg UpsertConnectorConnectionParams) (ConnectorConnection, error) {
	row := q.db.QueryRow(ctx, upsertConnectorConnection,
		arg.MarketplaceAccountID,
		arg.AccessTokenSealed,
		arg.RefreshTokenSealed,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
		arg.KeyVersion,
	)
	var i ConnectorConnection
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.ConnectionState,
		&i.AccessTokenSealed,
		&i.RefreshTokenSealed,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
