// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendConversationMessage = `-- name: AppendConversationMessage :one
INSERT INTO conversation_messages (conversation_id, author, body, envelope)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, author, body, envelope, created_at
`

type AppendConversationMessageParams struct {
	ConversationID uuid.UUID
	Author         string
	Body           string
	Envelope       []byte
}

// Appends one turn (user or assistant) to a conversation. APPEND-ONLY: message
// history is never updated or deleted. The assistant's typed response envelope is
// retained verbatim as JSONB evidence; it is NULL for a user turn.
func (q *Queries) AppendConversationMessage(ctx context.Context, arg AppendConversationMessageParams) (ConversationMessage, error) {
	row := q.db.QueryRow(ctx, appendConversationMessage,
		arg.ConversationID,
		arg.Author,
		arg.Body,
		arg.Envelope,
	)
	var i ConversationMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Author,
		&i.Body,
		&i.Envelope,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one

INSERT INTO conversations (organization_id, opened_by_user_id, marketplace_account_id)
VALUES ($1, $2, $3)
RETURNING id, organization_id, opened_by_user_id, marketplace_account_id, title, pinned, created_at, updated_at, retention_expires_at
`

type CreateConversationParams struct {
	OrganizationID       uuid.UUID
	OpenedByUserID       uuid.UUID
	MarketplaceAccountID pgtype.UUID
}

// Conversation durability queries (PRD §15.1 CHAT-008). These tables are
// GATEWAY-owned: the LLM plane holds NO DB credential (§19.3), so every write to
// conversation history flows through the gateway, never the model plane.
//
// conversation_messages is APPEND-ONLY (§4.6 never-cut): there is deliberately NO
// UPDATE and NO DELETE on message history here. The ONLY mutable column in this
// file is conversations.updated_at, advanced by the single org-scoped UPDATE
// below (activity recency for history ordering) — never a message row and never
// pinned/retention state.
//
// Audit independence (CHAT-008): these tables reference NOTHING in the
// append-only action/audit surface and hold no action/approval/execution column,
// so deleting a conversation leaves the complete action audit intact. Free text
// carries no authority (§8): a stored message can never approve or execute.
// Opens a new conversation under the caller's organization and author. title,
// pinned, created_at, updated_at, and retention_expires_at (now() + 90 days) take
// their schema defaults, so 90-day retention (CHAT-008) is set at creation without
// the caller computing a date.
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.OrganizationID, arg.OpenedByUserID, arg.MarketplaceAccountID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OpenedByUserID,
		&i.MarketplaceAccountID,
		&i.Title,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetentionExpiresAt,
	)
	return i, err
}

const getConversationForOrg = `-- name: GetConversationForOrg :one
SELECT id, organization_id, opened_by_user_id, marketplace_account_id, title, pinned, created_at, updated_at, retention_expires_at FROM conversations
WHERE id = $1 AND organization_id = $2
`

type GetConversationForOrgParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// Fetches a conversation scoped to the caller's organization. A conversation that
// does not exist OR belongs to another organization returns NO row, so a
// cross-org continued turn is denied at the query boundary (authorization), never
// served or appended to.
func (q *Queries) GetConversationForOrg(ctx context.Context, arg GetConversationForOrgParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationForOrg, arg.ID, arg.OrganizationID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OpenedByUserID,
		&i.MarketplaceAccountID,
		&i.Title,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetentionExpiresAt,
	)
	return i, err
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT id, conversation_id, author, body, envelope, created_at FROM conversation_messages
WHERE conversation_id = $1
ORDER BY created_at, id
`

// Reads a conversation's turns in order (history rendering + the cross-boundary
// persistence proof). APPEND-ONLY read.
func (q *Queries) ListConversationMessages(ctx context.Context, conversationID uuid.UUID) ([]ConversationMessage, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMessage{}
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Author,
			&i.Body,
			&i.Envelope,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :one
UPDATE conversations
SET updated_at = $2
WHERE id = $1 AND organization_id = $3
RETURNING id, organization_id, opened_by_user_id, marketplace_account_id, title, pinned, created_at, updated_at, retention_expires_at
`

type TouchConversationParams struct {
	ID             uuid.UUID
	UpdatedAt      time.Time
	OrganizationID uuid.UUID
}

// Advances conversations.updated_at for a conversation owned by the caller's
// organization. This is the ONLY UPDATE in this file: it touches NO message row
// and NO retention/pinned state, and a foreign conversation matches nothing and
// returns no row (no cross-org write).
func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, touchConversation, arg.ID, arg.UpdatedAt, arg.OrganizationID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OpenedByUserID,
		&i.MarketplaceAccountID,
		&i.Title,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetentionExpiresAt,
	)
	return i, err
}
