// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelCostImportBatch = `-- name: CancelCostImportBatch :one
UPDATE cost_import_batches
SET status = 'cancelled'
WHERE id = $1 AND status = 'preview'
RETURNING id, marketplace_account_id, filename, status, accept_count, reject_count, duplicate_count, created_by, created_at, committed_at
`

func (q *Queries) CancelCostImportBatch(ctx context.Context, id uuid.UUID) (CostImportBatch, error) {
	row := q.db.QueryRow(ctx, cancelCostImportBatch, id)
	var i CostImportBatch
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Filename,
		&i.Status,
		&i.AcceptCount,
		&i.RejectCount,
		&i.DuplicateCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const costProfileAt = `-- name: CostProfileAt :many
SELECT DISTINCT ON (component) id, marketplace_account_id, variant_id, component, version, amount_mantissa, amount_currency, amount_exponent, raw_text, raw_value, raw_unit, effective_from, stale_after, source, import_batch_id, created_by, created_at
FROM cost_profiles
WHERE variant_id = $1 AND effective_from <= $2
ORDER BY component, effective_from DESC, version DESC
`

type CostProfileAtParams struct {
	VariantID     uuid.UUID
	EffectiveFrom time.Time
}

// CST-002 point-in-time lookup: the EXACT in-force version of each component for
// a variant at timestamp $2 — the row with the greatest effective_from <= $2 per
// component. Reproduces the exact cost profile that produced a historical number,
// never the current one.
func (q *Queries) CostProfileAt(ctx context.Context, arg CostProfileAtParams) ([]CostProfile, error) {
	rows, err := q.db.Query(ctx, costProfileAt, arg.VariantID, arg.EffectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostProfile{}
	for rows.Next() {
		var i CostProfile
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.VariantID,
			&i.Component,
			&i.Version,
			&i.AmountMantissa,
			&i.AmountCurrency,
			&i.AmountExponent,
			&i.RawText,
			&i.RawValue,
			&i.RawUnit,
			&i.EffectiveFrom,
			&i.StaleAfter,
			&i.Source,
			&i.ImportBatchID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costProfileAtForAccount = `-- name: CostProfileAtForAccount :many
SELECT DISTINCT ON (component) id, marketplace_account_id, variant_id, component, version, amount_mantissa, amount_currency, amount_exponent, raw_text, raw_value, raw_unit, effective_from, stale_after, source, import_batch_id, created_by, created_at
FROM cost_profiles
WHERE variant_id = $1
  AND marketplace_account_id = $2
  AND effective_from <= $3
ORDER BY component, effective_from DESC, version DESC
`

type CostProfileAtForAccountParams struct {
	VariantID     uuid.UUID
	AccountID     uuid.UUID
	EffectiveFrom time.Time
}

// TENANT-SCOPED point-in-time lookup (issue #131, identity/tenant quarantine §4.6).
// Identical to CostProfileAt but the caller's RESOLVED marketplace account (derived
// from its authenticated organization, never a request param) bounds the read: a
// variant owned by another organization matches NO rows, so a foreign variant is
// indistinguishable from one with no cost profile (uniform empty result, no existence
// oracle). Reproduces the EXACT in-force version of each component at the instant.
func (q *Queries) CostProfileAtForAccount(ctx context.Context, arg CostProfileAtForAccountParams) ([]CostProfile, error) {
	rows, err := q.db.Query(ctx, costProfileAtForAccount, arg.VariantID, arg.AccountID, arg.EffectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostProfile{}
	for rows.Next() {
		var i CostProfile
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.VariantID,
			&i.Component,
			&i.Version,
			&i.AmountMantissa,
			&i.AmountCurrency,
			&i.AmountExponent,
			&i.RawText,
			&i.RawValue,
			&i.RawUnit,
			&i.EffectiveFrom,
			&i.StaleAfter,
			&i.Source,
			&i.ImportBatchID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMarginReadinessStates = `-- name: CountMarginReadinessStates :many
SELECT state, COUNT(*) AS n
FROM margin_readiness
WHERE marketplace_account_id = $1
GROUP BY state
`

type CountMarginReadinessStatesRow struct {
	State string
	N     int64
}

// The per-account readiness distribution backing the ≥70%-Complete beta gate
// (§20.2 / §21). The caller computes the Complete ratio from these counts.
func (q *Queries) CountMarginReadinessStates(ctx context.Context, marketplaceAccountID uuid.UUID) ([]CountMarginReadinessStatesRow, error) {
	rows, err := q.db.Query(ctx, countMarginReadinessStates, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMarginReadinessStatesRow{}
	for rows.Next() {
		var i CountMarginReadinessStatesRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCostImportBatch = `-- name: CreateCostImportBatch :one
INSERT INTO cost_import_batches (
    marketplace_account_id, filename, accept_count, reject_count, duplicate_count, created_by
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, marketplace_account_id, filename, status, accept_count, reject_count, duplicate_count, created_by, created_at, committed_at
`

type CreateCostImportBatchParams struct {
	MarketplaceAccountID uuid.UUID
	Filename             string
	AcceptCount          int32
	RejectCount          int32
	DuplicateCount       int32
	CreatedBy            pgtype.UUID
}

func (q *Queries) CreateCostImportBatch(ctx context.Context, arg CreateCostImportBatchParams) (CostImportBatch, error) {
	row := q.db.QueryRow(ctx, createCostImportBatch,
		arg.MarketplaceAccountID,
		arg.Filename,
		arg.AcceptCount,
		arg.RejectCount,
		arg.DuplicateCount,
		arg.CreatedBy,
	)
	var i CostImportBatch
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Filename,
		&i.Status,
		&i.AcceptCount,
		&i.RejectCount,
		&i.DuplicateCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const getAccountCostPolicy = `-- name: GetAccountCostPolicy :one

SELECT marketplace_account_id, entry_currency, entry_exponent, required_optional_components, created_at, updated_at FROM account_cost_policies WHERE marketplace_account_id = $1
`

// Cost profile / CSV import / margin readiness queries (PRD §7.2 CST-001..003,
// §9.2, §16). Write disciplines:
//   - cost_profiles is APPEND-ONLY (CST-002): there is NO UPDATE/DELETE here — a
//     new value is a new version row. effective_to is derived at read time.
//   - cost_import_batches/cost_import_rows are workflow state for the preview.
//   - margin_readiness and the two policy/requirement tables are current-state
//     projections (upserted).
func (q *Queries) GetAccountCostPolicy(ctx context.Context, marketplaceAccountID uuid.UUID) (AccountCostPolicy, error) {
	row := q.db.QueryRow(ctx, getAccountCostPolicy, marketplaceAccountID)
	var i AccountCostPolicy
	err := row.Scan(
		&i.MarketplaceAccountID,
		&i.EntryCurrency,
		&i.EntryExponent,
		&i.RequiredOptionalComponents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCostImportBatch = `-- name: GetCostImportBatch :one
SELECT id, marketplace_account_id, filename, status, accept_count, reject_count, duplicate_count, created_by, created_at, committed_at FROM cost_import_batches WHERE id = $1
`

func (q *Queries) GetCostImportBatch(ctx context.Context, id uuid.UUID) (CostImportBatch, error) {
	row := q.db.QueryRow(ctx, getCostImportBatch, id)
	var i CostImportBatch
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Filename,
		&i.Status,
		&i.AcceptCount,
		&i.RejectCount,
		&i.DuplicateCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const getMarginReadiness = `-- name: GetMarginReadiness :one
SELECT variant_id, marketplace_account_id, state, missing_components, stale_components, computed_at, stale_boundary FROM margin_readiness WHERE variant_id = $1
`

func (q *Queries) GetMarginReadiness(ctx context.Context, variantID uuid.UUID) (MarginReadiness, error) {
	row := q.db.QueryRow(ctx, getMarginReadiness, variantID)
	var i MarginReadiness
	err := row.Scan(
		&i.VariantID,
		&i.MarketplaceAccountID,
		&i.State,
		&i.MissingComponents,
		&i.StaleComponents,
		&i.ComputedAt,
		&i.StaleBoundary,
	)
	return i, err
}

const getSkuCostRequirements = `-- name: GetSkuCostRequirements :one
SELECT variant_id, marketplace_account_id, applicable_components, updated_at FROM sku_cost_requirements WHERE variant_id = $1
`

func (q *Queries) GetSkuCostRequirements(ctx context.Context, variantID uuid.UUID) (SkuCostRequirement, error) {
	row := q.db.QueryRow(ctx, getSkuCostRequirements, variantID)
	var i SkuCostRequirement
	err := row.Scan(
		&i.VariantID,
		&i.MarketplaceAccountID,
		&i.ApplicableComponents,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantAccountID = `-- name: GetVariantAccountID :one
SELECT marketplace_account_id FROM variants WHERE id = $1
`

// The account a variant belongs to — used to recompute readiness for a variant
// when the caller only has the variant id (e.g. the readiness read endpoint).
func (q *Queries) GetVariantAccountID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getVariantAccountID, id)
	var marketplace_account_id uuid.UUID
	err := row.Scan(&marketplace_account_id)
	return marketplace_account_id, err
}

const insertCostImportRow = `-- name: InsertCostImportRow :one
INSERT INTO cost_import_rows (
    batch_id, row_number, raw_sku, component, raw_value, normalized_value, raw_unit,
    resolved_variant_id, amount_mantissa, amount_currency, amount_exponent, disposition, reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, batch_id, row_number, raw_sku, component, raw_value, normalized_value, raw_unit, resolved_variant_id, amount_mantissa, amount_currency, amount_exponent, disposition, reason, created_at
`

type InsertCostImportRowParams struct {
	BatchID           uuid.UUID
	RowNumber         int32
	RawSku            string
	Component         string
	RawValue          string
	NormalizedValue   string
	RawUnit           string
	ResolvedVariantID pgtype.UUID
	AmountMantissa    pgtype.Int8
	AmountCurrency    string
	AmountExponent    int16
	Disposition       string
	Reason            string
}

func (q *Queries) InsertCostImportRow(ctx context.Context, arg InsertCostImportRowParams) (CostImportRow, error) {
	row := q.db.QueryRow(ctx, insertCostImportRow,
		arg.BatchID,
		arg.RowNumber,
		arg.RawSku,
		arg.Component,
		arg.RawValue,
		arg.NormalizedValue,
		arg.RawUnit,
		arg.ResolvedVariantID,
		arg.AmountMantissa,
		arg.AmountCurrency,
		arg.AmountExponent,
		arg.Disposition,
		arg.Reason,
	)
	var i CostImportRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.RowNumber,
		&i.RawSku,
		&i.Component,
		&i.RawValue,
		&i.NormalizedValue,
		&i.RawUnit,
		&i.ResolvedVariantID,
		&i.AmountMantissa,
		&i.AmountCurrency,
		&i.AmountExponent,
		&i.Disposition,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertCostProfileVersion = `-- name: InsertCostProfileVersion :one
INSERT INTO cost_profiles (
    marketplace_account_id, variant_id, component, version,
    amount_mantissa, amount_currency, amount_exponent,
    raw_text, raw_value, raw_unit, effective_from, stale_after, source, import_batch_id, created_by
) VALUES (
    $1, $2, $3,
    (SELECT COALESCE(MAX(version), 0) + 1 FROM cost_profiles WHERE variant_id = $2 AND component = $3),
    $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, marketplace_account_id, variant_id, component, version, amount_mantissa, amount_currency, amount_exponent, raw_text, raw_value, raw_unit, effective_from, stale_after, source, import_batch_id, created_by, created_at
`

type InsertCostProfileVersionParams struct {
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	Component            string
	AmountMantissa       int64
	AmountCurrency       string
	AmountExponent       int16
	RawText              string
	RawValue             string
	RawUnit              string
	EffectiveFrom        time.Time
	StaleAfter           pgtype.Timestamptz
	Source               string
	ImportBatchID        pgtype.UUID
	CreatedBy            pgtype.UUID
}

// APPEND-ONLY versioned cost value (CST-002). The version is MAX(version)+1 for
// this (variant, component); the UNIQUE (variant, component, version) constraint
// makes a concurrent double-insert fail closed rather than silently collide.
func (q *Queries) InsertCostProfileVersion(ctx context.Context, arg InsertCostProfileVersionParams) (CostProfile, error) {
	row := q.db.QueryRow(ctx, insertCostProfileVersion,
		arg.MarketplaceAccountID,
		arg.VariantID,
		arg.Component,
		arg.AmountMantissa,
		arg.AmountCurrency,
		arg.AmountExponent,
		arg.RawText,
		arg.RawValue,
		arg.RawUnit,
		arg.EffectiveFrom,
		arg.StaleAfter,
		arg.Source,
		arg.ImportBatchID,
		arg.CreatedBy,
	)
	var i CostProfile
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.Component,
		&i.Version,
		&i.AmountMantissa,
		&i.AmountCurrency,
		&i.AmountExponent,
		&i.RawText,
		&i.RawValue,
		&i.RawUnit,
		&i.EffectiveFrom,
		&i.StaleAfter,
		&i.Source,
		&i.ImportBatchID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAcceptedCostImportRows = `-- name: ListAcceptedCostImportRows :many
SELECT id, batch_id, row_number, raw_sku, component, raw_value, normalized_value, raw_unit, resolved_variant_id, amount_mantissa, amount_currency, amount_exponent, disposition, reason, created_at FROM cost_import_rows
WHERE batch_id = $1 AND disposition = 'accept' AND resolved_variant_id IS NOT NULL
ORDER BY row_number, component
`

// The rows a commit turns into cost_profile versions: accepted rows with a
// resolved variant. Duplicate/reject rows are excluded by construction.
func (q *Queries) ListAcceptedCostImportRows(ctx context.Context, batchID uuid.UUID) ([]CostImportRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedCostImportRows, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostImportRow{}
	for rows.Next() {
		var i CostImportRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.RowNumber,
			&i.RawSku,
			&i.Component,
			&i.RawValue,
			&i.NormalizedValue,
			&i.RawUnit,
			&i.ResolvedVariantID,
			&i.AmountMantissa,
			&i.AmountCurrency,
			&i.AmountExponent,
			&i.Disposition,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostImportRows = `-- name: ListCostImportRows :many
SELECT id, batch_id, row_number, raw_sku, component, raw_value, normalized_value, raw_unit, resolved_variant_id, amount_mantissa, amount_currency, amount_exponent, disposition, reason, created_at FROM cost_import_rows WHERE batch_id = $1 ORDER BY row_number, component
`

func (q *Queries) ListCostImportRows(ctx context.Context, batchID uuid.UUID) ([]CostImportRow, error) {
	rows, err := q.db.Query(ctx, listCostImportRows, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostImportRow{}
	for rows.Next() {
		var i CostImportRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.RowNumber,
			&i.RawSku,
			&i.Component,
			&i.RawValue,
			&i.NormalizedValue,
			&i.RawUnit,
			&i.ResolvedVariantID,
			&i.AmountMantissa,
			&i.AmountCurrency,
			&i.AmountExponent,
			&i.Disposition,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostProfileVersions = `-- name: ListCostProfileVersions :many
SELECT id, marketplace_account_id, variant_id, component, version, amount_mantissa, amount_currency, amount_exponent, raw_text, raw_value, raw_unit, effective_from, stale_after, source, import_batch_id, created_by, created_at FROM cost_profiles
WHERE variant_id = $1 AND component = $2
ORDER BY effective_from DESC, version DESC
`

type ListCostProfileVersionsParams struct {
	VariantID uuid.UUID
	Component string
}

// Full version history for one (variant, component), newest first — the versioned
// cost-profile list the product-detail screen renders.
func (q *Queries) ListCostProfileVersions(ctx context.Context, arg ListCostProfileVersionsParams) ([]CostProfile, error) {
	rows, err := q.db.Query(ctx, listCostProfileVersions, arg.VariantID, arg.Component)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostProfile{}
	for rows.Next() {
		var i CostProfile
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.VariantID,
			&i.Component,
			&i.Version,
			&i.AmountMantissa,
			&i.AmountCurrency,
			&i.AmountExponent,
			&i.RawText,
			&i.RawValue,
			&i.RawUnit,
			&i.EffectiveFrom,
			&i.StaleAfter,
			&i.Source,
			&i.ImportBatchID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarginReadinessByAccount = `-- name: ListMarginReadinessByAccount :many
SELECT variant_id, marketplace_account_id, state, missing_components, stale_components, computed_at, stale_boundary FROM margin_readiness WHERE marketplace_account_id = $1 ORDER BY state, variant_id
`

func (q *Queries) ListMarginReadinessByAccount(ctx context.Context, marketplaceAccountID uuid.UUID) ([]MarginReadiness, error) {
	rows, err := q.db.Query(ctx, listMarginReadinessByAccount, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarginReadiness{}
	for rows.Next() {
		var i MarginReadiness
		if err := rows.Scan(
			&i.VariantID,
			&i.MarketplaceAccountID,
			&i.State,
			&i.MissingComponents,
			&i.StaleComponents,
			&i.ComputedAt,
			&i.StaleBoundary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCostImportBatchCommitted = `-- name: MarkCostImportBatchCommitted :one
UPDATE cost_import_batches
SET status = 'committed', committed_at = now()
WHERE id = $1 AND status = 'preview' AND duplicate_count = 0
RETURNING id, marketplace_account_id, filename, status, accept_count, reject_count, duplicate_count, created_by, created_at, committed_at
`

// Commit a preview batch. The WHERE clause is a guard: only a batch that is still
// in 'preview' AND carries NO unresolved duplicate conflict (§16) may be
// committed. A batch that is already committed/cancelled, or that still has
// duplicate rows, matches nothing and returns no row — the service treats that as
// a refusal (no silent re-commit, no commit over an unresolved conflict).
func (q *Queries) MarkCostImportBatchCommitted(ctx context.Context, id uuid.UUID) (CostImportBatch, error) {
	row := q.db.QueryRow(ctx, markCostImportBatchCommitted, id)
	var i CostImportBatch
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.Filename,
		&i.Status,
		&i.AcceptCount,
		&i.RejectCount,
		&i.DuplicateCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const resolveVariantsBySupplierCode = `-- name: ResolveVariantsBySupplierCode :many
SELECT id, native_variant_id, supplier_code
FROM variants
WHERE marketplace_account_id = $1 AND supplier_code = $2
`

type ResolveVariantsBySupplierCodeParams struct {
	MarketplaceAccountID uuid.UUID
	SupplierCode         string
}

type ResolveVariantsBySupplierCodeRow struct {
	ID              uuid.UUID
	NativeVariantID int64
	SupplierCode    string
}

// Resolve a CSV SKU token to variants within an account. Zero rows ⇒ unknown SKU;
// more than one ⇒ ambiguous (both are preview rejects with a stated reason).
func (q *Queries) ResolveVariantsBySupplierCode(ctx context.Context, arg ResolveVariantsBySupplierCodeParams) ([]ResolveVariantsBySupplierCodeRow, error) {
	rows, err := q.db.Query(ctx, resolveVariantsBySupplierCode, arg.MarketplaceAccountID, arg.SupplierCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveVariantsBySupplierCodeRow{}
	for rows.Next() {
		var i ResolveVariantsBySupplierCodeRow
		if err := rows.Scan(&i.ID, &i.NativeVariantID, &i.SupplierCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountCostPolicy = `-- name: UpsertAccountCostPolicy :one
INSERT INTO account_cost_policies (
    marketplace_account_id, entry_currency, entry_exponent, required_optional_components
) VALUES ($1, $2, $3, $4)
ON CONFLICT (marketplace_account_id) DO UPDATE
SET entry_currency = EXCLUDED.entry_currency,
    entry_exponent = EXCLUDED.entry_exponent,
    required_optional_components = EXCLUDED.required_optional_components,
    updated_at = now()
RETURNING marketplace_account_id, entry_currency, entry_exponent, required_optional_components, created_at, updated_at
`

type UpsertAccountCostPolicyParams struct {
	MarketplaceAccountID       uuid.UUID
	EntryCurrency              string
	EntryExponent              int16
	RequiredOptionalComponents []byte
}

func (q *Queries) UpsertAccountCostPolicy(ctx context.Context, arg UpsertAccountCostPolicyParams) (AccountCostPolicy, error) {
	row := q.db.QueryRow(ctx, upsertAccountCostPolicy,
		arg.MarketplaceAccountID,
		arg.EntryCurrency,
		arg.EntryExponent,
		arg.RequiredOptionalComponents,
	)
	var i AccountCostPolicy
	err := row.Scan(
		&i.MarketplaceAccountID,
		&i.EntryCurrency,
		&i.EntryExponent,
		&i.RequiredOptionalComponents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMarginReadiness = `-- name: UpsertMarginReadiness :one
INSERT INTO margin_readiness (
    variant_id, marketplace_account_id, state, missing_components, stale_components, computed_at, stale_boundary
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (variant_id) DO UPDATE
SET state = EXCLUDED.state,
    missing_components = EXCLUDED.missing_components,
    stale_components = EXCLUDED.stale_components,
    computed_at = EXCLUDED.computed_at,
    stale_boundary = EXCLUDED.stale_boundary
RETURNING variant_id, marketplace_account_id, state, missing_components, stale_components, computed_at, stale_boundary
`

type UpsertMarginReadinessParams struct {
	VariantID            uuid.UUID
	MarketplaceAccountID uuid.UUID
	State                string
	MissingComponents    []byte
	StaleComponents      []byte
	ComputedAt           time.Time
	StaleBoundary        pgtype.Timestamptz
}

// Recompute the derived readiness projection (CST-003). Upsert: readiness is a
// current-state projection, recomputed on any input change. stale_boundary is the
// earliest review-by instant at which this projection must next age into Stale even
// with no new input (issue #39); NULL ⇒ nothing can age by time alone.
func (q *Queries) UpsertMarginReadiness(ctx context.Context, arg UpsertMarginReadinessParams) (MarginReadiness, error) {
	row := q.db.QueryRow(ctx, upsertMarginReadiness,
		arg.VariantID,
		arg.MarketplaceAccountID,
		arg.State,
		arg.MissingComponents,
		arg.StaleComponents,
		arg.ComputedAt,
		arg.StaleBoundary,
	)
	var i MarginReadiness
	err := row.Scan(
		&i.VariantID,
		&i.MarketplaceAccountID,
		&i.State,
		&i.MissingComponents,
		&i.StaleComponents,
		&i.ComputedAt,
		&i.StaleBoundary,
	)
	return i, err
}

const upsertSkuCostRequirements = `-- name: UpsertSkuCostRequirements :one
INSERT INTO sku_cost_requirements (
    variant_id, marketplace_account_id, applicable_components
) VALUES ($1, $2, $3)
ON CONFLICT (variant_id) DO UPDATE
SET applicable_components = EXCLUDED.applicable_components,
    updated_at = now()
RETURNING variant_id, marketplace_account_id, applicable_components, updated_at
`

type UpsertSkuCostRequirementsParams struct {
	VariantID            uuid.UUID
	MarketplaceAccountID uuid.UUID
	ApplicableComponents []byte
}

func (q *Queries) UpsertSkuCostRequirements(ctx context.Context, arg UpsertSkuCostRequirementsParams) (SkuCostRequirement, error) {
	row := q.db.QueryRow(ctx, upsertSkuCostRequirements, arg.VariantID, arg.MarketplaceAccountID, arg.ApplicableComponents)
	var i SkuCostRequirement
	err := row.Scan(
		&i.VariantID,
		&i.MarketplaceAccountID,
		&i.ApplicableComponents,
		&i.UpdatedAt,
	)
	return i, err
}
