// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregatePendingReconciliation = `-- name: AggregatePendingReconciliation :many
SELECT
    ac.marketplace_account_id AS account_id,
    count(*)                  AS pending_count,
    min(ae.created_at)::timestamptz AS oldest_created_at
FROM action_executions ae
JOIN approval_cards ac ON ac.id = ae.card_id
WHERE ae.external_state = 'pending_reconciliation'
GROUP BY ac.marketplace_account_id
`

type AggregatePendingReconciliationRow struct {
	AccountID       uuid.UUID
	PendingCount    int64
	OldestCreatedAt time.Time
}

// Per-account aggregate of the DURABLE pending_reconciliation set (EXE-003, §20.1):
// the current count of parked-unknown write results and the OLDEST park instant.
// This is the authoritative backlog measurement — the same durable rows
// ListPendingReconciliationByAccount renders in the Operations queue — read LIVE by
// the execution.pending_reconciliation_current / _oldest_age_seconds observable
// gauges. Because it reads current state, a resolved item simply leaves the set
// (count drops, never negative), an unrelated terminal result cannot cancel a still-
// pending item, and a process restart re-reads the same rows (no in-memory counter
// to zero). Grouped by the bound approval_cards account (action_executions carries
// no account column of its own), a bounded label. Pure SELECT — no UPDATE/DELETE, no
// Money arithmetic; the age is derived in Go as plain time subtraction on
// oldest_created_at.
func (q *Queries) AggregatePendingReconciliation(ctx context.Context) ([]AggregatePendingReconciliationRow, error) {
	rows, err := q.db.Query(ctx, aggregatePendingReconciliation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregatePendingReconciliationRow{}
	for rows.Next() {
		var i AggregatePendingReconciliationRow
		if err := rows.Scan(&i.AccountID, &i.PendingCount, &i.OldestCreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimActionExecution = `-- name: ClaimActionExecution :one

INSERT INTO action_executions (
    card_id, action_id, idempotency_key, mode, external_state, request_payload
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, card_id, action_id, idempotency_key, mode, external_state, external_ref, request_payload, response_payload, reconciled_at, created_at, updated_at
`

type ClaimActionExecutionParams struct {
	CardID         uuid.UUID
	ActionID       uuid.UUID
	IdempotencyKey string
	Mode           string
	ExternalState  string
	RequestPayload []byte
}

// Execution + recommend-only + write-verification queries (PRD §7.5 EXE-002..005).
// Discipline:
//   - action_executions is the EXE-002 SINGLE record per action, keyed by the
//     stable idempotency_key (UNIQUE). Claiming is an INSERT ... ON CONFLICT DO
//     NOTHING: a duplicate request finds the existing row and performs NO second
//     external write. The external_state projection is advanced by a FROM-guarded
//     UPDATE (pending_reconciliation → terminal), never a blind overwrite.
//   - account_write_verification is the S35 write-verification flag; ABSENT/false
//     means writes are OFF (the read returns false when there is no row).
//
// Claim the idempotency key. ON CONFLICT DO NOTHING makes this idempotent: a
// second request for the same key returns NO row (the service then reads the
// existing record and writes nothing external).
func (q *Queries) ClaimActionExecution(ctx context.Context, arg ClaimActionExecutionParams) (ActionExecution, error) {
	row := q.db.QueryRow(ctx, claimActionExecution,
		arg.CardID,
		arg.ActionID,
		arg.IdempotencyKey,
		arg.Mode,
		arg.ExternalState,
		arg.RequestPayload,
	)
	var i ActionExecution
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ActionID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.ExternalState,
		&i.ExternalRef,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.ReconciledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActionExecution = `-- name: GetActionExecution :one
SELECT id, card_id, action_id, idempotency_key, mode, external_state, external_ref, request_payload, response_payload, reconciled_at, created_at, updated_at FROM action_executions WHERE id = $1
`

func (q *Queries) GetActionExecution(ctx context.Context, id uuid.UUID) (ActionExecution, error) {
	row := q.db.QueryRow(ctx, getActionExecution, id)
	var i ActionExecution
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ActionID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.ExternalState,
		&i.ExternalRef,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.ReconciledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActionExecutionByAction = `-- name: GetActionExecutionByAction :one
SELECT id, card_id, action_id, idempotency_key, mode, external_state, external_ref, request_payload, response_payload, reconciled_at, created_at, updated_at FROM action_executions WHERE action_id = $1
`

func (q *Queries) GetActionExecutionByAction(ctx context.Context, actionID uuid.UUID) (ActionExecution, error) {
	row := q.db.QueryRow(ctx, getActionExecutionByAction, actionID)
	var i ActionExecution
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ActionID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.ExternalState,
		&i.ExternalRef,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.ReconciledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActionExecutionByKey = `-- name: GetActionExecutionByKey :one
SELECT id, card_id, action_id, idempotency_key, mode, external_state, external_ref, request_payload, response_payload, reconciled_at, created_at, updated_at FROM action_executions WHERE idempotency_key = $1
`

func (q *Queries) GetActionExecutionByKey(ctx context.Context, idempotencyKey string) (ActionExecution, error) {
	row := q.db.QueryRow(ctx, getActionExecutionByKey, idempotencyKey)
	var i ActionExecution
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ActionID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.ExternalState,
		&i.ExternalRef,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.ReconciledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentExecutionContext = `-- name: GetCurrentExecutionContext :one
SELECT
    base.marketplace_account_id AS account_id,
    base.variant_id             AS variant_id,
    v.native_variant_id         AS native_variant_id,
    cur.cost_profile_version    AS current_cost_profile_version,
    cur.policy_version          AS current_policy_version,
    cur.context_version         AS current_context_version,
    cur.parameter_version       AS current_parameter_version
FROM recommendations base
JOIN variants v ON v.id = base.variant_id
JOIN LATERAL (
    SELECT cost_profile_version, policy_version, context_version, parameter_version
    FROM recommendations
    WHERE lineage_id = base.lineage_id
    ORDER BY version DESC
    LIMIT 1
) cur ON true
WHERE base.id = $1
`

type GetCurrentExecutionContextRow struct {
	AccountID                 uuid.UUID
	VariantID                 uuid.UUID
	NativeVariantID           int64
	CurrentCostProfileVersion int64
	CurrentPolicyVersion      int64
	CurrentContextVersion     int64
	CurrentParameterVersion   int64
}

// Server-side re-resolution for the Revalidating gate (EXE-001): the account,
// variant, and native variant id for a card's recommendation, PLUS the CURRENT
// (greatest-version) cost/policy/context/parameter versions in the recommendation
// lineage. Comparing these to the card's BOUND versions catches an out-of-band
// version change that never passed through a state-machine invalidation.
func (q *Queries) GetCurrentExecutionContext(ctx context.Context, id uuid.UUID) (GetCurrentExecutionContextRow, error) {
	row := q.db.QueryRow(ctx, getCurrentExecutionContext, id)
	var i GetCurrentExecutionContextRow
	err := row.Scan(
		&i.AccountID,
		&i.VariantID,
		&i.NativeVariantID,
		&i.CurrentCostProfileVersion,
		&i.CurrentPolicyVersion,
		&i.CurrentContextVersion,
		&i.CurrentParameterVersion,
	)
	return i, err
}

const getRecommendOnlyAction = `-- name: GetRecommendOnlyAction :one
SELECT id, card_id, action_id, marketplace_account_id, variant_id, approved_price_mantissa, approved_price_currency, approved_price_exponent, approved_at, window_expires_at, state, matched_observation_at, created_at, updated_at FROM recommend_only_actions WHERE action_id = $1
`

func (q *Queries) GetRecommendOnlyAction(ctx context.Context, actionID uuid.UUID) (RecommendOnlyAction, error) {
	row := q.db.QueryRow(ctx, getRecommendOnlyAction, actionID)
	var i RecommendOnlyAction
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ActionID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.ApprovedPriceMantissa,
		&i.ApprovedPriceCurrency,
		&i.ApprovedPriceExponent,
		&i.ApprovedAt,
		&i.WindowExpiresAt,
		&i.State,
		&i.MatchedObservationAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWriteVerification = `-- name: GetWriteVerification :one
SELECT marketplace_account_id, region_code, verified, parameter_contract_version, verified_at, note, updated_at FROM account_write_verification WHERE marketplace_account_id = $1
`

func (q *Queries) GetWriteVerification(ctx context.Context, marketplaceAccountID uuid.UUID) (AccountWriteVerification, error) {
	row := q.db.QueryRow(ctx, getWriteVerification, marketplaceAccountID)
	var i AccountWriteVerification
	err := row.Scan(
		&i.MarketplaceAccountID,
		&i.RegionCode,
		&i.Verified,
		&i.ParameterContractVersion,
		&i.VerifiedAt,
		&i.Note,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecommendOnlyAction = `-- name: InsertRecommendOnlyAction :one
INSERT INTO recommend_only_actions (
    card_id, action_id, marketplace_account_id, variant_id,
    approved_price_mantissa, approved_price_currency, approved_price_exponent,
    approved_at, window_expires_at, state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'awaiting_external_execution')
ON CONFLICT (action_id) DO NOTHING
RETURNING id, card_id, action_id, marketplace_account_id, variant_id, approved_price_mantissa, approved_price_currency, approved_price_exponent, approved_at, window_expires_at, state, matched_observation_at, created_at, updated_at
`

type InsertRecommendOnlyActionParams struct {
	CardID                uuid.UUID
	ActionID              uuid.UUID
	MarketplaceAccountID  uuid.UUID
	VariantID             uuid.UUID
	ApprovedPriceMantissa int64
	ApprovedPriceCurrency string
	ApprovedPriceExponent int16
	ApprovedAt            time.Time
	WindowExpiresAt       time.Time
}

func (q *Queries) InsertRecommendOnlyAction(ctx context.Context, arg InsertRecommendOnlyActionParams) (RecommendOnlyAction, error) {
	row := q.db.QueryRow(ctx, insertRecommendOnlyAction,
		arg.CardID,
		arg.ActionID,
		arg.MarketplaceAccountID,
		arg.VariantID,
		arg.ApprovedPriceMantissa,
		arg.ApprovedPriceCurrency,
		arg.ApprovedPriceExponent,
		arg.ApprovedAt,
		arg.WindowExpiresAt,
	)
	var i RecommendOnlyAction
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ActionID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.ApprovedPriceMantissa,
		&i.ApprovedPriceCurrency,
		&i.ApprovedPriceExponent,
		&i.ApprovedAt,
		&i.WindowExpiresAt,
		&i.State,
		&i.MatchedObservationAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isWriteVerified = `-- name: IsWriteVerified :one
SELECT EXISTS (
    SELECT 1 FROM account_write_verification
    WHERE marketplace_account_id = $1 AND verified
) AS verified
`

// The S35 write-verification flag for an account. Returns false when there is no
// row (writes OFF by default) — the two-key write gate's second key.
func (q *Queries) IsWriteVerified(ctx context.Context, marketplaceAccountID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isWriteVerified, marketplaceAccountID)
	var verified bool
	err := row.Scan(&verified)
	return verified, err
}

const listAwaitingRecommendOnlyActions = `-- name: ListAwaitingRecommendOnlyActions :many
SELECT id, card_id, action_id, marketplace_account_id, variant_id, approved_price_mantissa, approved_price_currency, approved_price_exponent, approved_at, window_expires_at, state, matched_observation_at, created_at, updated_at FROM recommend_only_actions
WHERE state = 'awaiting_external_execution'
ORDER BY approved_at
LIMIT $1
`

// Every awaiting recommend-only action (the periodic matcher job iterates these,
// matching each against fresh owned-price observations or lapsing it once its 24h
// window has passed). Bounded batch to bound the job's work per pass.
func (q *Queries) ListAwaitingRecommendOnlyActions(ctx context.Context, limit int32) ([]RecommendOnlyAction, error) {
	rows, err := q.db.Query(ctx, listAwaitingRecommendOnlyActions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendOnlyAction{}
	for rows.Next() {
		var i RecommendOnlyAction
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ActionID,
			&i.MarketplaceAccountID,
			&i.VariantID,
			&i.ApprovedPriceMantissa,
			&i.ApprovedPriceCurrency,
			&i.ApprovedPriceExponent,
			&i.ApprovedAt,
			&i.WindowExpiresAt,
			&i.State,
			&i.MatchedObservationAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAwaitingRecommendOnlyForVariant = `-- name: ListAwaitingRecommendOnlyForVariant :many
SELECT id, card_id, action_id, marketplace_account_id, variant_id, approved_price_mantissa, approved_price_currency, approved_price_exponent, approved_at, window_expires_at, state, matched_observation_at, created_at, updated_at FROM recommend_only_actions
WHERE variant_id = $1 AND state = 'awaiting_external_execution'
ORDER BY approved_at
`

// Awaiting recommend-only actions for a variant (the recommend-only matcher runs
// these against fresh owned-price observations).
func (q *Queries) ListAwaitingRecommendOnlyForVariant(ctx context.Context, variantID uuid.UUID) ([]RecommendOnlyAction, error) {
	rows, err := q.db.Query(ctx, listAwaitingRecommendOnlyForVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendOnlyAction{}
	for rows.Next() {
		var i RecommendOnlyAction
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ActionID,
			&i.MarketplaceAccountID,
			&i.VariantID,
			&i.ApprovedPriceMantissa,
			&i.ApprovedPriceCurrency,
			&i.ApprovedPriceExponent,
			&i.ApprovedAt,
			&i.WindowExpiresAt,
			&i.State,
			&i.MatchedObservationAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReconciliationByAccount = `-- name: ListPendingReconciliationByAccount :many
SELECT ae.id, ae.card_id, ae.action_id, ae.idempotency_key, ae.mode, ae.external_state, ae.external_ref, ae.request_payload, ae.response_payload, ae.reconciled_at, ae.created_at, ae.updated_at
FROM action_executions ae
JOIN approval_cards ac ON ac.id = ae.card_id
WHERE ac.marketplace_account_id = $1 AND ae.external_state = 'pending_reconciliation'
ORDER BY ae.created_at
LIMIT $2
`

type ListPendingReconciliationByAccountParams struct {
	MarketplaceAccountID uuid.UUID
	Limit                int32
}

// The account's action_executions still in pending_reconciliation (PD-3 item 8,
// S37 Operations queue) — an unknown external write result that must resolve
// before any retry (EXE-003, never inferred). Scoped via the bound
// approval_cards row (action_executions carries no account column of its own).
func (q *Queries) ListPendingReconciliationByAccount(ctx context.Context, arg ListPendingReconciliationByAccountParams) ([]ActionExecution, error) {
	rows, err := q.db.Query(ctx, listPendingReconciliationByAccount, arg.MarketplaceAccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionExecution{}
	for rows.Next() {
		var i ActionExecution
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ActionID,
			&i.IdempotencyKey,
			&i.Mode,
			&i.ExternalState,
			&i.ExternalRef,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.ReconciledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileActionExecution = `-- name: ReconcileActionExecution :one
UPDATE action_executions
SET external_state = $2,
    external_ref = $3,
    reconciled_at = now(),
    updated_at = now()
WHERE id = $1 AND external_state = 'pending_reconciliation'
RETURNING id, card_id, action_id, idempotency_key, mode, external_state, external_ref, request_payload, response_payload, reconciled_at, created_at, updated_at
`

type ReconcileActionExecutionParams struct {
	ID            uuid.UUID
	ExternalState string
	ExternalRef   string
}

// Resolve a pending_reconciliation record to a terminal state (post-write
// read-back or periodic reconciliation, §16). FROM-guarded on pending so only an
// unresolved record is reconciled; the retry endpoint refuses any record still
// pending (EXE-003). The observed external ref (batch handle) is recorded verbatim.
func (q *Queries) ReconcileActionExecution(ctx context.Context, arg ReconcileActionExecutionParams) (ActionExecution, error) {
	row := q.db.QueryRow(ctx, reconcileActionExecution, arg.ID, arg.ExternalState, arg.ExternalRef)
	var i ActionExecution
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ActionID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.ExternalState,
		&i.ExternalRef,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.ReconciledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordExecutionResult = `-- name: RecordExecutionResult :one
UPDATE action_executions
SET external_state = $2,
    external_ref = $3,
    response_payload = $4,
    reconciled_at = CASE WHEN $2 <> 'pending_reconciliation' THEN now() ELSE reconciled_at END,
    updated_at = now()
WHERE id = $1 AND external_state = 'pending_reconciliation'
RETURNING id, card_id, action_id, idempotency_key, mode, external_state, external_ref, request_payload, response_payload, reconciled_at, created_at, updated_at
`

type RecordExecutionResultParams struct {
	ID              uuid.UUID
	ExternalState   string
	ExternalRef     string
	ResponsePayload []byte
}

// Record the classified write result. FROM-guarded on the pending state so a
// definitive result is written exactly once; a row already resolved to a terminal
// state is not overwritten (idempotent result recording).
func (q *Queries) RecordExecutionResult(ctx context.Context, arg RecordExecutionResultParams) (ActionExecution, error) {
	row := q.db.QueryRow(ctx, recordExecutionResult,
		arg.ID,
		arg.ExternalState,
		arg.ExternalRef,
		arg.ResponsePayload,
	)
	var i ActionExecution
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ActionID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.ExternalState,
		&i.ExternalRef,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.ReconciledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRecommendOnlyState = `-- name: SetRecommendOnlyState :one
UPDATE recommend_only_actions
SET state = $2,
    matched_observation_at = $3,
    updated_at = now()
WHERE action_id = $1 AND state = 'awaiting_external_execution'
RETURNING id, card_id, action_id, marketplace_account_id, variant_id, approved_price_mantissa, approved_price_currency, approved_price_exponent, approved_at, window_expires_at, state, matched_observation_at, created_at, updated_at
`

type SetRecommendOnlyStateParams struct {
	ActionID             uuid.UUID
	State                string
	MatchedObservationAt pgtype.Timestamptz
}

// Advance a recommend-only action to a terminal EXE-005 state. FROM-guarded on
// the awaiting state so a resolved action is not re-resolved.
func (q *Queries) SetRecommendOnlyState(ctx context.Context, arg SetRecommendOnlyStateParams) (RecommendOnlyAction, error) {
	row := q.db.QueryRow(ctx, setRecommendOnlyState, arg.ActionID, arg.State, arg.MatchedObservationAt)
	var i RecommendOnlyAction
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ActionID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.ApprovedPriceMantissa,
		&i.ApprovedPriceCurrency,
		&i.ApprovedPriceExponent,
		&i.ApprovedAt,
		&i.WindowExpiresAt,
		&i.State,
		&i.MatchedObservationAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWriteVerification = `-- name: UpsertWriteVerification :one
INSERT INTO account_write_verification (
    marketplace_account_id, region_code, verified, parameter_contract_version, verified_at, note
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (marketplace_account_id) DO UPDATE
SET region_code = EXCLUDED.region_code,
    verified = EXCLUDED.verified,
    parameter_contract_version = EXCLUDED.parameter_contract_version,
    verified_at = EXCLUDED.verified_at,
    note = EXCLUDED.note,
    updated_at = now()
RETURNING marketplace_account_id, region_code, verified, parameter_contract_version, verified_at, note, updated_at
`

type UpsertWriteVerificationParams struct {
	MarketplaceAccountID     uuid.UUID
	RegionCode               string
	Verified                 bool
	ParameterContractVersion int64
	VerifiedAt               pgtype.Timestamptz
	Note                     string
}

// Set the S35 write-verification flag (called only by the gated S35 probe path,
// never at runtime). Present for completeness of the seam.
func (q *Queries) UpsertWriteVerification(ctx context.Context, arg UpsertWriteVerificationParams) (AccountWriteVerification, error) {
	row := q.db.QueryRow(ctx, upsertWriteVerification,
		arg.MarketplaceAccountID,
		arg.RegionCode,
		arg.Verified,
		arg.ParameterContractVersion,
		arg.VerifiedAt,
		arg.Note,
	)
	var i AccountWriteVerification
	err := row.Scan(
		&i.MarketplaceAccountID,
		&i.RegionCode,
		&i.Verified,
		&i.ParameterContractVersion,
		&i.VerifiedAt,
		&i.Note,
		&i.UpdatedAt,
	)
	return i, err
}
