// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardrail.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getGuardrailSettings = `-- name: GetGuardrailSettings :one

SELECT marketplace_account_id, contribution_floor_mantissa, contribution_floor_currency, contribution_floor_exponent, movement_cap_basis_points, cooldown_seconds, strategy, strategy_enabled, updated_by, updated_at FROM guardrail_settings WHERE marketplace_account_id = $1
`

// L3 commercial guardrail persistence (PD-3 item 6, S37). One row per account;
// a write is an upsert (Owner-only, audited atomically by the caller in the SAME
// transaction — see internal/guardrail).
func (q *Queries) GetGuardrailSettings(ctx context.Context, marketplaceAccountID uuid.UUID) (GuardrailSetting, error) {
	row := q.db.QueryRow(ctx, getGuardrailSettings, marketplaceAccountID)
	var i GuardrailSetting
	err := row.Scan(
		&i.MarketplaceAccountID,
		&i.ContributionFloorMantissa,
		&i.ContributionFloorCurrency,
		&i.ContributionFloorExponent,
		&i.MovementCapBasisPoints,
		&i.CooldownSeconds,
		&i.Strategy,
		&i.StrategyEnabled,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGuardrailSettings = `-- name: UpsertGuardrailSettings :one
INSERT INTO guardrail_settings (
    marketplace_account_id, contribution_floor_mantissa, contribution_floor_currency,
    contribution_floor_exponent, movement_cap_basis_points, cooldown_seconds,
    strategy, strategy_enabled, updated_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (marketplace_account_id) DO UPDATE
SET contribution_floor_mantissa = EXCLUDED.contribution_floor_mantissa,
    contribution_floor_currency = EXCLUDED.contribution_floor_currency,
    contribution_floor_exponent = EXCLUDED.contribution_floor_exponent,
    movement_cap_basis_points   = EXCLUDED.movement_cap_basis_points,
    cooldown_seconds            = EXCLUDED.cooldown_seconds,
    strategy                    = EXCLUDED.strategy,
    strategy_enabled            = EXCLUDED.strategy_enabled,
    updated_by                  = EXCLUDED.updated_by,
    updated_at                  = now()
RETURNING marketplace_account_id, contribution_floor_mantissa, contribution_floor_currency, contribution_floor_exponent, movement_cap_basis_points, cooldown_seconds, strategy, strategy_enabled, updated_by, updated_at
`

type UpsertGuardrailSettingsParams struct {
	MarketplaceAccountID      uuid.UUID
	ContributionFloorMantissa int64
	ContributionFloorCurrency string
	ContributionFloorExponent int16
	MovementCapBasisPoints    int64
	CooldownSeconds           int64
	Strategy                  string
	StrategyEnabled           bool
	UpdatedBy                 string
}

func (q *Queries) UpsertGuardrailSettings(ctx context.Context, arg UpsertGuardrailSettingsParams) (GuardrailSetting, error) {
	row := q.db.QueryRow(ctx, upsertGuardrailSettings,
		arg.MarketplaceAccountID,
		arg.ContributionFloorMantissa,
		arg.ContributionFloorCurrency,
		arg.ContributionFloorExponent,
		arg.MovementCapBasisPoints,
		arg.CooldownSeconds,
		arg.Strategy,
		arg.StrategyEnabled,
		arg.UpdatedBy,
	)
	var i GuardrailSetting
	err := row.Scan(
		&i.MarketplaceAccountID,
		&i.ContributionFloorMantissa,
		&i.ContributionFloorCurrency,
		&i.ContributionFloorExponent,
		&i.MovementCapBasisPoints,
		&i.CooldownSeconds,
		&i.Strategy,
		&i.StrategyEnabled,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
