// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: level2.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLevel2Proposal = `-- name: GetLevel2Proposal :one
SELECT id, marketplace_account_id, action_id, setting_key, before_key, after_key, scope_key, consequence_key, context_version, parameter_version, expires_at, actor, actor_role, surface, created_at FROM level2_proposals WHERE id = $1
`

func (q *Queries) GetLevel2Proposal(ctx context.Context, id uuid.UUID) (Level2Proposal, error) {
	row := q.db.QueryRow(ctx, getLevel2Proposal, id)
	var i Level2Proposal
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.ActionID,
		&i.SettingKey,
		&i.BeforeKey,
		&i.AfterKey,
		&i.ScopeKey,
		&i.ConsequenceKey,
		&i.ContextVersion,
		&i.ParameterVersion,
		&i.ExpiresAt,
		&i.Actor,
		&i.ActorRole,
		&i.Surface,
		&i.CreatedAt,
	)
	return i, err
}

const insertLevel2Proposal = `-- name: InsertLevel2Proposal :one

INSERT INTO level2_proposals (
    marketplace_account_id, action_id, setting_key, before_key, after_key,
    scope_key, consequence_key, context_version, parameter_version, expires_at,
    actor, actor_role, surface
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13
)
RETURNING id, marketplace_account_id, action_id, setting_key, before_key, after_key, scope_key, consequence_key, context_version, parameter_version, expires_at, actor, actor_role, surface, created_at
`

type InsertLevel2ProposalParams struct {
	MarketplaceAccountID uuid.UUID
	ActionID             uuid.UUID
	SettingKey           string
	BeforeKey            string
	AfterKey             string
	ScopeKey             string
	ConsequenceKey       string
	ContextVersion       int64
	ParameterVersion     int64
	ExpiresAt            time.Time
	Actor                string
	ActorRole            string
	Surface              string
}

// Level-2 reversible-config proposal queries (PRD §8.3 CHAT-061/062).
// level2_proposals is APPEND-ONLY: INSERT/SELECT only. The proposal write and its
// AUD-001 audit row are committed in ONE transaction by the service (fail-closed
// on audit error). TERMINAL AT DRAFT — no state advance, no approval control.
func (q *Queries) InsertLevel2Proposal(ctx context.Context, arg InsertLevel2ProposalParams) (Level2Proposal, error) {
	row := q.db.QueryRow(ctx, insertLevel2Proposal,
		arg.MarketplaceAccountID,
		arg.ActionID,
		arg.SettingKey,
		arg.BeforeKey,
		arg.AfterKey,
		arg.ScopeKey,
		arg.ConsequenceKey,
		arg.ContextVersion,
		arg.ParameterVersion,
		arg.ExpiresAt,
		arg.Actor,
		arg.ActorRole,
		arg.Surface,
	)
	var i Level2Proposal
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.ActionID,
		&i.SettingKey,
		&i.BeforeKey,
		&i.AfterKey,
		&i.ScopeKey,
		&i.ConsequenceKey,
		&i.ContextVersion,
		&i.ParameterVersion,
		&i.ExpiresAt,
		&i.Actor,
		&i.ActorRole,
		&i.Surface,
		&i.CreatedAt,
	)
	return i, err
}
