// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marketplace_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMarketplaceAccount = `-- name: CreateMarketplaceAccount :one
INSERT INTO marketplace_accounts (organization_id, native_account_id, display_name)
VALUES ($1, $2, $3)
RETURNING id, organization_id, native_account_id, display_name, created_at, updated_at
`

type CreateMarketplaceAccountParams struct {
	OrganizationID  uuid.UUID
	NativeAccountID string
	DisplayName     string
}

func (q *Queries) CreateMarketplaceAccount(ctx context.Context, arg CreateMarketplaceAccountParams) (MarketplaceAccount, error) {
	row := q.db.QueryRow(ctx, createMarketplaceAccount, arg.OrganizationID, arg.NativeAccountID, arg.DisplayName)
	var i MarketplaceAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NativeAccountID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketplaceAccount = `-- name: GetMarketplaceAccount :one
SELECT id, organization_id, native_account_id, display_name, created_at, updated_at FROM marketplace_accounts
WHERE id = $1
`

func (q *Queries) GetMarketplaceAccount(ctx context.Context, id uuid.UUID) (MarketplaceAccount, error) {
	row := q.db.QueryRow(ctx, getMarketplaceAccount, id)
	var i MarketplaceAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NativeAccountID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketplaceAccountByNativeID = `-- name: GetMarketplaceAccountByNativeID :one
SELECT id, organization_id, native_account_id, display_name, created_at, updated_at FROM marketplace_accounts
WHERE native_account_id = $1
`

func (q *Queries) GetMarketplaceAccountByNativeID(ctx context.Context, nativeAccountID string) (MarketplaceAccount, error) {
	row := q.db.QueryRow(ctx, getMarketplaceAccountByNativeID, nativeAccountID)
	var i MarketplaceAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NativeAccountID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketplaceAccountByOrganization = `-- name: GetMarketplaceAccountByOrganization :one
SELECT id, organization_id, native_account_id, display_name, created_at, updated_at FROM marketplace_accounts
WHERE organization_id = $1
`

func (q *Queries) GetMarketplaceAccountByOrganization(ctx context.Context, organizationID uuid.UUID) (MarketplaceAccount, error) {
	row := q.db.QueryRow(ctx, getMarketplaceAccountByOrganization, organizationID)
	var i MarketplaceAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NativeAccountID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgMarketplaceAccountID = `-- name: GetOrgMarketplaceAccountID :one
SELECT id FROM marketplace_accounts
WHERE id = $1 AND organization_id = $2
`

type GetOrgMarketplaceAccountIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// Ownership guard: resolve an account id ONLY when it belongs to the given
// organization. A foreign or unknown account id yields no row (pgx.ErrNoRows),
// so possession of a UUID never grants cross-organization access (S8-AUTHZ-001).
func (q *Queries) GetOrgMarketplaceAccountID(ctx context.Context, arg GetOrgMarketplaceAccountIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOrgMarketplaceAccountID, arg.ID, arg.OrganizationID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listMarketplaceAccountIDs = `-- name: ListMarketplaceAccountIDs :many
SELECT id FROM marketplace_accounts
ORDER BY created_at, id
`

// Every marketplace account id, in a stable order — the per-account fan-out for
// platform passes (e.g. the daily briefing job, CHAT-010).
func (q *Queries) ListMarketplaceAccountIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMarketplaceAccountIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
