// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type MarketplaceAccount struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	NativeAccountID string
	DisplayName     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	Role           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
