// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogPayloadSnapshot struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	SyncRunID            uuid.UUID
	NativeVariantID      int64
	Page                 int32
	Payload              []byte
	CapturedAt           time.Time
}

type CatalogSyncRun struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	Kind                 string
	Status               string
	NextPage             int32
	PagesDone            int32
	TotalPages           int32
	TotalRows            int32
	ItemsSeen            int32
	RecordsInserted      int32
	RecordsUpdated       int32
	DriftCount           int32
	Error                string
	StartedAt            time.Time
	UpdatedAt            time.Time
	CompletedAt          pgtype.Timestamptz
}

type ConnectorCapability struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	Capability           string
	Status               string
	Detail               pgtype.Text
	LastVerifiedAt       pgtype.Timestamptz
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type ConnectorConnection struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	ConnectionState      string
	AccessTokenSealed    []byte
	RefreshTokenSealed   []byte
	AccessExpiresAt      pgtype.Timestamptz
	RefreshExpiresAt     pgtype.Timestamptz
	KeyVersion           int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Conversation struct {
	ID                   uuid.UUID
	OrganizationID       uuid.UUID
	OpenedByUserID       uuid.UUID
	MarketplaceAccountID pgtype.UUID
	Title                string
	Pinned               bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
	RetentionExpiresAt   time.Time
}

type ConversationMessage struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Author         string
	Body           string
	Envelope       []byte
	CreatedAt      time.Time
}

type Listing struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	NativeListingID      int64
	SellingChannel       string
	ProductUrl           string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type MarketProductIdentity struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	NativeVariantID      int64
	NativeProductID      int64
	State                string
	Active               bool
	CandidateSource      string
	Version              int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type MarketProductIdentityDecision struct {
	ID                   uuid.UUID
	IdentityID           uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	Decision             string
	FromState            string
	ToState              string
	Reason               string
	Evidence             []byte
	DecidedBy            pgtype.UUID
	DecidedAt            time.Time
}

type MarketplaceAccount struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	NativeAccountID string
	DisplayName     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Observation struct {
	ID                   uuid.UUID
	CapturedAt           time.Time
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	NativeVariantID      int64
	NativeSellerID       string
	OfferIdentity        string
	Route                string
	SubRoute             string
	ParserVersion        string
	ConnectorVersion     string
	SourceUrl            string
	SourceType           string
	EvidenceRef          string
	RawFixtureRef        string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	FreshnessDeadline    time.Time
	DedupKey             string
	SchemaValid          bool
	IdentityValid        bool
	Confidence           string
	ParsingWarnings      []byte
}

type ObservationDedup struct {
	DedupKey      string
	TargetID      uuid.UUID
	Route         string
	OfferIdentity string
	FirstSeenAt   time.Time
}

type ObservationTarget struct {
	ID                       uuid.UUID
	MarketplaceAccountID     uuid.UUID
	IdentityID               uuid.UUID
	VariantID                uuid.UUID
	NativeVariantID          int64
	NativeProductID          int64
	Tier                     string
	CadenceSeconds           int32
	FreshnessDeadlineSeconds int32
	Active                   bool
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type ObservationsDefault struct {
	ID                   uuid.UUID
	CapturedAt           time.Time
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	NativeVariantID      int64
	NativeSellerID       string
	OfferIdentity        string
	Route                string
	SubRoute             string
	ParserVersion        string
	ConnectorVersion     string
	SourceUrl            string
	SourceType           string
	EvidenceRef          string
	RawFixtureRef        string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	FreshnessDeadline    time.Time
	DedupKey             string
	SchemaValid          bool
	IdentityValid        bool
	Confidence           string
	ParsingWarnings      []byte
}

type ObservedOffer struct {
	ID                   uuid.UUID
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	OfferIdentity        string
	NativeVariantID      int64
	NativeSellerID       string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	CapturedAt           time.Time
	FreshnessDeadline    time.Time
	Routes               []byte
	LastObservationID    uuid.UUID
	EndedAt              pgtype.Timestamptz
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OwnedOffer struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	NativeVariantID      int64
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	SellerStock          pgtype.Int8
	WarehouseStock       pgtype.Int8
	LastSeenRunID        pgtype.UUID
	LastSeenAt           pgtype.Timestamptz
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Product struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	NativeProductID      int64
	Title                string
	BrandTitle           string
	ProductUrl           string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type RecommendationInvalidationEvent struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	IdentityID           uuid.UUID
	Reason               string
	DedupKey             string
	EmittedAt            time.Time
}

type RouteKillSwitch struct {
	ID        uuid.UUID
	Scope     string
	AccountID pgtype.UUID
	TargetID  pgtype.UUID
	Reason    string
	EngagedBy pgtype.UUID
	EngagedAt time.Time
}

type Session struct {
	TokenHash string
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	Role           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UserCredential struct {
	UserID       uuid.UUID
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Variant struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	ProductID            uuid.UUID
	NativeVariantID      int64
	NativeProductID      int64
	SupplierCode         string
	Title                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
