// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountCostPolicy struct {
	MarketplaceAccountID       uuid.UUID
	EntryCurrency              string
	EntryExponent              int16
	RequiredOptionalComponents []byte
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type AccountWriteVerification struct {
	MarketplaceAccountID     uuid.UUID
	RegionCode               string
	Verified                 bool
	ParameterContractVersion int64
	VerifiedAt               pgtype.Timestamptz
	Note                     string
	UpdatedAt                time.Time
}

type ActionExecution struct {
	ID              uuid.UUID
	CardID          uuid.UUID
	ActionID        uuid.UUID
	IdempotencyKey  string
	Mode            string
	ExternalState   string
	ExternalRef     string
	RequestPayload  []byte
	ResponsePayload []byte
	ReconciledAt    pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ApprovalCard struct {
	ID                   uuid.UUID
	RecommendationID     uuid.UUID
	MarketplaceAccountID uuid.UUID
	LineageID            uuid.UUID
	Version              int32
	ActionID             uuid.UUID
	ParameterVersion     int64
	ContextVersion       int64
	PolicyVersion        int64
	CostProfileVersion   int64
	EvidenceVersions     []byte
	IdempotencyKey       string
	State                string
	PriceMantissa        int64
	PriceCurrency        string
	PriceExponent        int16
	ExpiresAt            time.Time
	CreatedAt            time.Time
}

type ApprovalCardState struct {
	ID          uuid.UUID
	CardID      uuid.UUID
	CardVersion int32
	FromState   pgtype.Text
	ToState     string
	Reason      string
	OccurredAt  time.Time
}

type AuditRecord struct {
	ID                   uuid.UUID
	ActionID             uuid.UUID
	CardID               pgtype.UUID
	MarketplaceAccountID pgtype.UUID
	EventType            string
	Actor                string
	ActorRole            string
	Surface              string
	ContextVersion       int64
	ParameterVersion     int64
	PolicyVersion        int64
	CostProfileVersion   int64
	EvidenceVersions     []byte
	CardSnapshot         []byte
	Detail               []byte
	TerminalState        string
	OccurredAt           time.Time
}

type CatalogPayloadSnapshot struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	SyncRunID            uuid.UUID
	NativeVariantID      int64
	Page                 int32
	Payload              []byte
	CapturedAt           time.Time
}

type CatalogSyncRun struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	Kind                 string
	Status               string
	NextPage             int32
	PagesDone            int32
	TotalPages           int32
	TotalRows            int32
	ItemsSeen            int32
	RecordsInserted      int32
	RecordsUpdated       int32
	DriftCount           int32
	Error                string
	StartedAt            time.Time
	UpdatedAt            time.Time
	CompletedAt          pgtype.Timestamptz
}

type ConnectorCapability struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	Capability           string
	Status               string
	Detail               pgtype.Text
	LastVerifiedAt       pgtype.Timestamptz
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type ConnectorConnection struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	ConnectionState      string
	AccessTokenSealed    []byte
	RefreshTokenSealed   []byte
	AccessExpiresAt      pgtype.Timestamptz
	RefreshExpiresAt     pgtype.Timestamptz
	KeyVersion           int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Conversation struct {
	ID                   uuid.UUID
	OrganizationID       uuid.UUID
	OpenedByUserID       uuid.UUID
	MarketplaceAccountID pgtype.UUID
	Title                string
	Pinned               bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
	RetentionExpiresAt   time.Time
}

type ConversationMessage struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Author         string
	Body           string
	Envelope       []byte
	CreatedAt      time.Time
}

type CostImportBatch struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	Filename             string
	Status               string
	AcceptCount          int32
	RejectCount          int32
	DuplicateCount       int32
	CreatedBy            pgtype.UUID
	CreatedAt            time.Time
	CommittedAt          pgtype.Timestamptz
}

type CostImportRow struct {
	ID                uuid.UUID
	BatchID           uuid.UUID
	RowNumber         int32
	RawSku            string
	Component         string
	RawValue          string
	NormalizedValue   string
	RawUnit           string
	ResolvedVariantID pgtype.UUID
	AmountMantissa    pgtype.Int8
	AmountCurrency    string
	AmountExponent    int16
	Disposition       string
	Reason            string
	CreatedAt         time.Time
}

type CostProfile struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	Component            string
	Version              int32
	AmountMantissa       int64
	AmountCurrency       string
	AmountExponent       int16
	RawText              string
	RawValue             string
	RawUnit              string
	EffectiveFrom        time.Time
	StaleAfter           pgtype.Timestamptz
	Source               string
	ImportBatchID        pgtype.UUID
	CreatedBy            pgtype.UUID
	CreatedAt            time.Time
}

type EventRelevanceFeedback struct {
	ID        uuid.UUID
	EventID   uuid.UUID
	UserID    pgtype.UUID
	Relevance string
	Note      string
	CreatedAt time.Time
}

type Listing struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	NativeListingID      int64
	SellingChannel       string
	ProductUrl           string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type MarginReadiness struct {
	VariantID            uuid.UUID
	MarketplaceAccountID uuid.UUID
	State                string
	MissingComponents    []byte
	StaleComponents      []byte
	ComputedAt           time.Time
}

type MarketEvent struct {
	ID                    uuid.UUID
	MarketplaceAccountID  uuid.UUID
	VariantID             uuid.UUID
	TargetID              pgtype.UUID
	EventType             string
	Severity              string
	State                 string
	DedupKey              string
	ThresholdID           pgtype.UUID
	ThresholdVersion      pgtype.Int4
	ExposureKnown         bool
	ExposureMantissa      pgtype.Int8
	ExposureCurrency      string
	ExposureExponent      int16
	ConfidenceBp          int32
	UrgencyBp             int32
	EvidenceObservationID pgtype.UUID
	EvidenceQuality       string
	EvidenceRef           string
	EvidenceDetail        []byte
	FirstDetectedAt       time.Time
	LastEvidenceAt        time.Time
	ExpiresAt             time.Time
	ResolvedAt            pgtype.Timestamptz
	UpdatedAt             time.Time
	EvidenceUpdateCount   int32
}

type MarketProductIdentity struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	NativeVariantID      int64
	NativeProductID      int64
	State                string
	Active               bool
	CandidateSource      string
	Version              int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type MarketProductIdentityDecision struct {
	ID                   uuid.UUID
	IdentityID           uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	Decision             string
	FromState            string
	ToState              string
	Reason               string
	Evidence             []byte
	DecidedBy            pgtype.UUID
	DecidedAt            time.Time
}

type MarketplaceAccount struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	NativeAccountID string
	DisplayName     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MaterialityThreshold struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	Category             string
	EventType            string
	Version              int32
	MoveBp               pgtype.Int4
	SellerCountDelta     pgtype.Int4
	ChallengeMarginBp    pgtype.Int4
	EffectiveFrom        time.Time
	CreatedBy            pgtype.UUID
	CreatedAt            time.Time
}

type Observation struct {
	ID                   uuid.UUID
	CapturedAt           time.Time
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	NativeVariantID      int64
	NativeSellerID       string
	OfferIdentity        string
	Route                string
	SubRoute             string
	ParserVersion        string
	ConnectorVersion     string
	SourceUrl            string
	SourceType           string
	EvidenceRef          string
	RawFixtureRef        string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	FreshnessDeadline    time.Time
	DedupKey             string
	SchemaValid          bool
	IdentityValid        bool
	Confidence           string
	ParsingWarnings      []byte
}

type ObservationDedup struct {
	DedupKey      string
	TargetID      uuid.UUID
	Route         string
	OfferIdentity string
	FirstSeenAt   time.Time
}

type ObservationTarget struct {
	ID                       uuid.UUID
	MarketplaceAccountID     uuid.UUID
	IdentityID               uuid.UUID
	VariantID                uuid.UUID
	NativeVariantID          int64
	NativeProductID          int64
	Tier                     string
	CadenceSeconds           int32
	FreshnessDeadlineSeconds int32
	Active                   bool
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type ObservationsDefault struct {
	ID                   uuid.UUID
	CapturedAt           time.Time
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	NativeVariantID      int64
	NativeSellerID       string
	OfferIdentity        string
	Route                string
	SubRoute             string
	ParserVersion        string
	ConnectorVersion     string
	SourceUrl            string
	SourceType           string
	EvidenceRef          string
	RawFixtureRef        string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	FreshnessDeadline    time.Time
	DedupKey             string
	SchemaValid          bool
	IdentityValid        bool
	Confidence           string
	ParsingWarnings      []byte
}

type ObservedOffer struct {
	ID                   uuid.UUID
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	OfferIdentity        string
	NativeVariantID      int64
	NativeSellerID       string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	CapturedAt           time.Time
	FreshnessDeadline    time.Time
	Routes               []byte
	LastObservationID    uuid.UUID
	EndedAt              pgtype.Timestamptz
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OutcomeResult struct {
	ID         uuid.UUID
	WindowID   uuid.UUID
	Result     string
	Confidence string
	ComputedAt time.Time
}

type OutcomeWindow struct {
	ID        uuid.UUID
	ActionID  uuid.UUID
	CardID    pgtype.UUID
	OpenedAt  time.Time
	ClosesAt  time.Time
	CreatedAt time.Time
}

type OwnedOffer struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	NativeVariantID      int64
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	SellerStock          pgtype.Int8
	WarehouseStock       pgtype.Int8
	LastSeenRunID        pgtype.UUID
	LastSeenAt           pgtype.Timestamptz
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Product struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	NativeProductID      int64
	Title                string
	BrandTitle           string
	ProductUrl           string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type RecommendOnlyAction struct {
	ID                    uuid.UUID
	CardID                uuid.UUID
	ActionID              uuid.UUID
	MarketplaceAccountID  uuid.UUID
	VariantID             uuid.UUID
	ApprovedPriceMantissa int64
	ApprovedPriceCurrency string
	ApprovedPriceExponent int16
	ApprovedAt            time.Time
	WindowExpiresAt       time.Time
	State                 string
	MatchedObservationAt  pgtype.Timestamptz
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Recommendation struct {
	ID                            uuid.UUID
	MarketplaceAccountID          uuid.UUID
	VariantID                     uuid.UUID
	LineageID                     uuid.UUID
	Version                       int32
	EventID                       pgtype.UUID
	Objective                     string
	CurrentPriceMantissa          int64
	CurrentPriceCurrency          string
	CurrentPriceExponent          int16
	ProposedPriceAvailable        bool
	ProposedPriceMantissa         pgtype.Int8
	ProposedPriceCurrency         string
	ProposedPriceExponent         int16
	ProposedPriceReason           string
	CurrentContributionAvailable  bool
	CurrentContributionMantissa   pgtype.Int8
	CurrentContributionCurrency   string
	CurrentContributionExponent   int16
	CurrentContributionReason     string
	ProposedContributionAvailable bool
	ProposedContributionMantissa  pgtype.Int8
	ProposedContributionCurrency  string
	ProposedContributionExponent  int16
	ProposedContributionReason    string
	AllowedRangeAvailable         bool
	AllowedRangeMinMantissa       pgtype.Int8
	AllowedRangeMaxMantissa       pgtype.Int8
	AllowedRangeCurrency          string
	AllowedRangeExponent          int16
	AllowedRangeReason            string
	Readiness                     string
	EvidenceQuality               string
	EvidenceObservationID         pgtype.UUID
	EvidenceRefs                  []byte
	EvidenceAsOf                  pgtype.Timestamptz
	CostProfileVersion            int64
	PolicyVersion                 int64
	ContextVersion                int64
	ParameterVersion              int64
	Inputs                        []byte
	Assumptions                   []byte
	Blockers                      []byte
	Approvable                    bool
	Simulation                    bool
	ExpiresAt                     pgtype.Timestamptz
	CreatedAt                     time.Time
}

type RecommendationInvalidationEvent struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	IdentityID           uuid.UUID
	Reason               string
	DedupKey             string
	EmittedAt            time.Time
}

type RouteKillSwitch struct {
	ID        uuid.UUID
	Scope     string
	AccountID pgtype.UUID
	TargetID  pgtype.UUID
	Reason    string
	EngagedBy pgtype.UUID
	EngagedAt time.Time
}

type SelectionSet struct {
	ID                      uuid.UUID
	MarketplaceAccountID    uuid.UUID
	LineageID               uuid.UUID
	Version                 int32
	Name                    string
	Criteria                []byte
	MemberCount             int32
	AggregateImpactKnown    bool
	AggregateImpactMantissa pgtype.Int8
	AggregateImpactCurrency string
	AggregateImpactExponent int16
	CreatedAt               time.Time
}

type SelectionSetMember struct {
	ID               uuid.UUID
	SelectionSetID   uuid.UUID
	VariantID        uuid.UUID
	RecommendationID pgtype.UUID
	Disposition      string
	CreatedAt        time.Time
}

type Session struct {
	TokenHash string
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type SkuCostRequirement struct {
	VariantID            uuid.UUID
	MarketplaceAccountID uuid.UUID
	ApplicableComponents []byte
	UpdatedAt            time.Time
}

type User struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	Role           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UserCredential struct {
	UserID       uuid.UUID
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Variant struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	ProductID            uuid.UUID
	NativeVariantID      int64
	NativeProductID      int64
	SupplierCode         string
	Title                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
