// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpDigestDeliveryAttempt = `-- name: BumpDigestDeliveryAttempt :one
UPDATE notification_digest_deliveries
SET attempts = attempts + 1, updated_at = $3, last_reason = $4, last_status_code = $5
WHERE marketplace_account_id = $1 AND business_day = $2 AND delivery_state = 'pending'
RETURNING id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous
`

type BumpDigestDeliveryAttemptParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	UpdatedAt            time.Time
	LastReason           pgtype.Text
	LastStatusCode       int32
}

// Records a TRANSIENT failed attempt while the row stays pending (attempts + bounded
// reason), so a retry is observable without a state transition. Guarded on 'pending'.
func (q *Queries) BumpDigestDeliveryAttempt(ctx context.Context, arg BumpDigestDeliveryAttemptParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, bumpDigestDeliveryAttempt,
		arg.MarketplaceAccountID,
		arg.BusinessDay,
		arg.UpdatedAt,
		arg.LastReason,
		arg.LastStatusCode,
	)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}

const bumpUrgentOutboxAttempt = `-- name: BumpUrgentOutboxAttempt :one
UPDATE notification_urgent_outbox
SET attempts = attempts + 1, updated_at = $3, last_error = $4
WHERE notification_id = $1 AND channel = $2 AND delivery_state = 'pending'
RETURNING id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at
`

type BumpUrgentOutboxAttemptParams struct {
	NotificationID uuid.UUID
	Channel        string
	UpdatedAt      time.Time
	LastError      pgtype.Text
}

// Records a TRANSIENT failed attempt while the row stays pending (attempts + bounded
// last_error), so a retry is observable without a state transition. Guarded by
// delivery_state = 'pending'.
func (q *Queries) BumpUrgentOutboxAttempt(ctx context.Context, arg BumpUrgentOutboxAttemptParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, bumpUrgentOutboxAttempt,
		arg.NotificationID,
		arg.Channel,
		arg.UpdatedAt,
		arg.LastError,
	)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE marketplace_account_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, marketplaceAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deliverNotification = `-- name: DeliverNotification :one

INSERT INTO notifications (
    marketplace_account_id, event_id, dedup_key, category, severity,
    bypass_digest, title_key, body_key, body_params
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (marketplace_account_id, dedup_key) DO NOTHING
RETURNING id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at
`

type DeliverNotificationParams struct {
	MarketplaceAccountID uuid.UUID
	EventID              uuid.UUID
	DedupKey             string
	Category             string
	Severity             string
	BypassDigest         bool
	TitleKey             string
	BodyKey              string
	BodyParams           []byte
}

// Notification queries (PRD §7.5 NOT-001). notifications, notification_digests,
// and notification_digest_items are APPEND-ONLY (INSERT/SELECT); the sole mutable
// column is notifications.read_at, advanced by ONE FROM-guarded UPDATE below.
// Delivers one in-app notification (NOT-001). ON CONFLICT DO NOTHING on the
// (marketplace_account_id, dedup_key) key: a duplicate delivery inserts nothing
// and returns NO row, so duplicate delivery can NEVER create a duplicate product
// event. The caller treats pgx.ErrNoRows as "already delivered" (idempotent).
func (q *Queries) DeliverNotification(ctx context.Context, arg DeliverNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, deliverNotification,
		arg.MarketplaceAccountID,
		arg.EventID,
		arg.DedupKey,
		arg.Category,
		arg.Severity,
		arg.BypassDigest,
		arg.TitleKey,
		arg.BodyKey,
		arg.BodyParams,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.EventID,
		&i.DedupKey,
		&i.Category,
		&i.Severity,
		&i.BypassDigest,
		&i.TitleKey,
		&i.BodyKey,
		&i.BodyParams,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const ensureDigestDelivery = `-- name: EnsureDigestDelivery :one

INSERT INTO notification_digest_deliveries (marketplace_account_id, business_day)
VALUES ($1, $2)
ON CONFLICT (marketplace_account_id, business_day) DO NOTHING
RETURNING id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous
`

type EnsureDigestDeliveryParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
}

// --- Per-(account, business_day) digest delivery-state projection (issue #124) ------
//
// The DURABLE per-account/day work record that isolates one tenant's digest failure
// from every other tenant. (marketplace_account_id, business_day) is the stable
// idempotency key; the state machine below is the ONLY mutable surface (the digest
// header + items stay append-only). Every transition is GUARDED on its source state,
// so a duplicate/concurrent drive matches nothing and is an idempotent no-op — a
// retry or a recovery re-enqueue can never resend a digest.
// Opens the durable delivery row for (account, business_day). ON CONFLICT DO NOTHING
// on the idempotency key: a re-discovery inserts nothing and returns no row (the
// caller treats pgx.ErrNoRows as "already tracked" and reads the existing row). The
// caller enqueues the per-account job in the SAME transaction (transactional enqueue),
// so a committed work record always has a driving job and a rollback discards both.
func (q *Queries) EnsureDigestDelivery(ctx context.Context, arg EnsureDigestDeliveryParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, ensureDigestDelivery, arg.MarketplaceAccountID, arg.BusinessDay)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}

const getDigestByAccountDay = `-- name: GetDigestByAccountDay :one
SELECT id, marketplace_account_id, business_day, generated_at, item_count FROM notification_digests
WHERE marketplace_account_id = $1 AND business_day = $2
`

type GetDigestByAccountDayParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
}

func (q *Queries) GetDigestByAccountDay(ctx context.Context, arg GetDigestByAccountDayParams) (NotificationDigest, error) {
	row := q.db.QueryRow(ctx, getDigestByAccountDay, arg.MarketplaceAccountID, arg.BusinessDay)
	var i NotificationDigest
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.GeneratedAt,
		&i.ItemCount,
	)
	return i, err
}

const getDigestDelivery = `-- name: GetDigestDelivery :one
SELECT id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous FROM notification_digest_deliveries
WHERE marketplace_account_id = $1 AND business_day = $2
`

type GetDigestDeliveryParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
}

// Reads the durable delivery row so the worker can make its idempotent decision (a
// terminal state → no-op, no duplicate digest).
func (q *Queries) GetDigestDelivery(ctx context.Context, arg GetDigestDeliveryParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, getDigestDelivery, arg.MarketplaceAccountID, arg.BusinessDay)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}

const getDigestRecipientEmail = `-- name: GetDigestRecipientEmail :one
SELECT u.email
FROM marketplace_accounts ma
JOIN users u ON u.organization_id = ma.organization_id
WHERE ma.id = $1
ORDER BY (u.role = 'owner') DESC, u.created_at, u.id
LIMIT 1
`

// The digest recipient for an account: the organization's owner user email,
// falling back to the earliest user when no owner role exists. Returns no row when
// the organization has no users (the digest is then unsendable — fail closed).
func (q *Queries) GetDigestRecipientEmail(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getDigestRecipientEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getNotificationByDedup = `-- name: GetNotificationByDedup :one
SELECT id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at FROM notifications
WHERE marketplace_account_id = $1 AND dedup_key = $2
`

type GetNotificationByDedupParams struct {
	MarketplaceAccountID uuid.UUID
	DedupKey             string
}

// Reads the existing notification for a dedup key (used to return the SAME row on
// an idempotent re-delivery so both surfaces reference the SAME event id).
func (q *Queries) GetNotificationByDedup(ctx context.Context, arg GetNotificationByDedupParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByDedup, arg.MarketplaceAccountID, arg.DedupKey)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.EventID,
		&i.DedupKey,
		&i.Category,
		&i.Severity,
		&i.BypassDigest,
		&i.TitleKey,
		&i.BodyKey,
		&i.BodyParams,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getUrgentOutbox = `-- name: GetUrgentOutbox :one
SELECT id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at FROM notification_urgent_outbox
WHERE notification_id = $1 AND channel = $2
`

type GetUrgentOutboxParams struct {
	NotificationID uuid.UUID
	Channel        string
}

// Reads the urgent outbox row for a notification+channel so the dispatcher can make
// its idempotent decision (already delivered / dead-lettered → no-op).
func (q *Queries) GetUrgentOutbox(ctx context.Context, arg GetUrgentOutboxParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, getUrgentOutbox, arg.NotificationID, arg.Channel)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const insertDigest = `-- name: InsertDigest :one
INSERT INTO notification_digests (marketplace_account_id, business_day, generated_at, item_count)
VALUES ($1, $2, $3, $4)
ON CONFLICT (marketplace_account_id, business_day) DO NOTHING
RETURNING id, marketplace_account_id, business_day, generated_at, item_count
`

type InsertDigestParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	GeneratedAt          time.Time
	ItemCount            int32
}

// Opens the once-per-business-day digest header. ON CONFLICT DO NOTHING makes the
// River digest job idempotent per business day: a retry inserts nothing and
// returns no row (no duplicate digest, no duplicate send).
func (q *Queries) InsertDigest(ctx context.Context, arg InsertDigestParams) (NotificationDigest, error) {
	row := q.db.QueryRow(ctx, insertDigest,
		arg.MarketplaceAccountID,
		arg.BusinessDay,
		arg.GeneratedAt,
		arg.ItemCount,
	)
	var i NotificationDigest
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.GeneratedAt,
		&i.ItemCount,
	)
	return i, err
}

const insertDigestItem = `-- name: InsertDigestItem :one
INSERT INTO notification_digest_items (digest_id, notification_id, event_id)
VALUES ($1, $2, $3)
RETURNING id, digest_id, notification_id, event_id
`

type InsertDigestItemParams struct {
	DigestID       uuid.UUID
	NotificationID uuid.UUID
	EventID        uuid.UUID
}

// Appends one notification (with its SHARED event id) to a digest's membership
// snapshot. APPEND-ONLY.
func (q *Queries) InsertDigestItem(ctx context.Context, arg InsertDigestItemParams) (NotificationDigestItem, error) {
	row := q.db.QueryRow(ctx, insertDigestItem, arg.DigestID, arg.NotificationID, arg.EventID)
	var i NotificationDigestItem
	err := row.Scan(
		&i.ID,
		&i.DigestID,
		&i.NotificationID,
		&i.EventID,
	)
	return i, err
}

const insertUrgentOutbox = `-- name: InsertUrgentOutbox :one
INSERT INTO notification_urgent_outbox (notification_id, marketplace_account_id, channel)
VALUES ($1, $2, $3)
ON CONFLICT (notification_id, channel) DO NOTHING
RETURNING id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at
`

type InsertUrgentOutboxParams struct {
	NotificationID       uuid.UUID
	MarketplaceAccountID uuid.UUID
	Channel              string
}

// Opens the DURABLE urgent-delivery outbox row for a bypass (execution/safety)
// notification. Inserted in the SAME transaction that commits the notification, so a
// crash before the email sends still completes delivery on restart (issue #122). ON
// CONFLICT DO NOTHING on the (notification_id, channel) idempotency key: a re-driven
// delivery inserts nothing and returns no row (the caller treats pgx.ErrNoRows as
// "already enqueued" — no duplicate logical email). APPEND on this projection; state
// is mutated only by the guarded transitions below (never on notifications/audit).
func (q *Queries) InsertUrgentOutbox(ctx context.Context, arg InsertUrgentOutboxParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, insertUrgentOutbox, arg.NotificationID, arg.MarketplaceAccountID, arg.Channel)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const listDigestItems = `-- name: ListDigestItems :many
SELECT id, digest_id, notification_id, event_id FROM notification_digest_items
WHERE digest_id = $1
ORDER BY id
`

// The membership of one digest, in insertion order (the shared event ids).
func (q *Queries) ListDigestItems(ctx context.Context, digestID uuid.UUID) ([]NotificationDigestItem, error) {
	rows, err := q.db.Query(ctx, listDigestItems, digestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDigestItem{}
	for rows.Next() {
		var i NotificationDigestItem
		if err := rows.Scan(
			&i.ID,
			&i.DigestID,
			&i.NotificationID,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonterminalDigestDeliveries = `-- name: ListNonterminalDigestDeliveries :many
SELECT id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous FROM notification_digest_deliveries
WHERE (
        delivery_state = 'pending'
        OR (delivery_state = 'sending' AND updated_at < $1::timestamptz)
      )
ORDER BY business_day, updated_at, id
LIMIT $2
`

type ListNonterminalDigestDeliveriesParams struct {
	StaleBefore time.Time
	RowLimit    int32
}

// The OWNED RECOVERY source (issue #124 / PD-4): every NONTERMINAL (account, day)
// delivery row, of ANY historical business day, rediscovered directly from this table
// and re-enqueued by the fan-out pass. It deliberately consults NO River state: River's
// completion/snooze write and the terminal projection write share the same PostgreSQL
// dependency, so a correlated outage can leave a job `running` at its final attempt
// (the rescuer then DISCARDS it) while the row is still nonterminal. Recovery anchored
// here survives that window, and it survives day advancement because business_day is
// pinned on the row rather than recomputed.
//
// A 'sending' row is only rediscovered once it is STALE (updated_at older than the
// cutoff), so a live in-flight attempt is never raced by a recovery re-enqueue. The
// LIMIT bounds the pass (§17 bounded reads / backpressure: the recovery queue never
// grows unbounded in one tick). Oldest work first.
func (q *Queries) ListNonterminalDigestDeliveries(ctx context.Context, arg ListNonterminalDigestDeliveriesParams) ([]NotificationDigestDelivery, error) {
	rows, err := q.db.Query(ctx, listNonterminalDigestDeliveries, arg.StaleBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDigestDelivery{}
	for rows.Next() {
		var i NotificationDigestDelivery
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.BusinessDay,
			&i.DeliveryState,
			&i.Attempts,
			&i.LastReason,
			&i.LastStatusCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinalizedAt,
			&i.Ambiguous,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsPage = `-- name: ListNotificationsPage :many
SELECT id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at FROM notifications
WHERE marketplace_account_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListNotificationsPageParams struct {
	MarketplaceAccountID uuid.UUID
	CursorCreatedAt      pgtype.Timestamptz
	CursorID             pgtype.UUID
	PageLimit            int32
}

// The in-app notification feed for an account, newest first, BOUNDED by a keyset
// cursor (§17 bounded reads). Deterministic order is (created_at DESC, id DESC);
// the row-value comparison (created_at, id) < (cursor_created_at, cursor_id) reads
// STRICTLY OLDER rows than the cursor position, so ties on created_at are broken by
// id and every row is returned EXACTLY ONCE across pages (no duplicate, no skip). A
// NULL cursor (cursor_created_at IS NULL) is the first (newest) page. The caller
// passes page_limit = requested_limit + 1 and treats the extra row as the hasMore
// signal (then trims it). SELECT-only: the notifications store stays append-only.
// Backed by idx_notifications_account_created_id (marketplace_account_id,
// created_at DESC, id DESC) so the plan is an index range scan, never a full history
// scan. account-scoped WHERE is the authorization; the cursor is only a position.
func (q *Queries) ListNotificationsPage(ctx context.Context, arg ListNotificationsPageParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsPage,
		arg.MarketplaceAccountID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.EventID,
			&i.DedupKey,
			&i.Category,
			&i.Severity,
			&i.BypassDigest,
			&i.TitleKey,
			&i.BodyKey,
			&i.BodyParams,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDigestNotifications = `-- name: ListPendingDigestNotifications :many
SELECT id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at FROM notifications
WHERE marketplace_account_id = $1
  AND bypass_digest = false
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at, id
`

type ListPendingDigestNotificationsParams struct {
	MarketplaceAccountID uuid.UUID
	CreatedAt            time.Time
	CreatedAt_2          time.Time
}

// The notifications eligible for the batched daily digest for one account and
// business day: NOT bypass_digest (execution/safety failures bypass the digest and
// were delivered immediately) and created within the business-day window. Oldest
// first so the digest reads in occurrence order. Shared event ids flow through.
func (q *Queries) ListPendingDigestNotifications(ctx context.Context, arg ListPendingDigestNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listPendingDigestNotifications, arg.MarketplaceAccountID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.EventID,
			&i.DedupKey,
			&i.Category,
			&i.Severity,
			&i.BypassDigest,
			&i.TitleKey,
			&i.BodyKey,
			&i.BodyParams,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDigestDeliveryAmbiguous = `-- name: MarkDigestDeliveryAmbiguous :one
UPDATE notification_digest_deliveries
SET ambiguous = true, updated_at = $3
WHERE marketplace_account_id = $1 AND business_day = $2 AND delivery_state = 'sending'
RETURNING id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous
`

type MarkDigestDeliveryAmbiguousParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	UpdatedAt            time.Time
}

// Raises the AMBIGUITY marker on an in-flight send at the moment the exchange enters
// its genuinely ambiguous window (the body terminator is about to be written and the
// relay's verdict awaited). From here acceptance cannot be disproven, so a row
// abandoned after this point is finalized 'unconfirmed' and never resent. Guarded on
// 'sending': it can only ever narrow a live claim.
func (q *Queries) MarkDigestDeliveryAmbiguous(ctx context.Context, arg MarkDigestDeliveryAmbiguousParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, markDigestDeliveryAmbiguous, arg.MarketplaceAccountID, arg.BusinessDay, arg.UpdatedAt)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}

const markDigestDeliveryDeadLetter = `-- name: MarkDigestDeliveryDeadLetter :one
UPDATE notification_digest_deliveries
SET delivery_state = 'dead_letter', attempts = attempts + 1, updated_at = $3, finalized_at = $3,
    last_reason = $4, last_status_code = $5
WHERE marketplace_account_id = $1 AND business_day = $2 AND delivery_state = 'pending'
RETURNING id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous
`

type MarkDigestDeliveryDeadLetterParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	UpdatedAt            time.Time
	LastReason           pgtype.Text
	LastStatusCode       int32
}

// pending → dead_letter: a PERMANENT failure that definitively did NOT deliver
// (unsendable target, unsupported locale, render error, permanent relay rejection, or
// exhausted attempts before any send). An OBSERVABLE terminal state; it does NOT mark
// the digest delivered (no false "delivered"). Guarded on 'pending'.
func (q *Queries) MarkDigestDeliveryDeadLetter(ctx context.Context, arg MarkDigestDeliveryDeadLetterParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, markDigestDeliveryDeadLetter,
		arg.MarketplaceAccountID,
		arg.BusinessDay,
		arg.UpdatedAt,
		arg.LastReason,
		arg.LastStatusCode,
	)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}

const markDigestDeliveryDelivered = `-- name: MarkDigestDeliveryDelivered :one
UPDATE notification_digest_deliveries
SET delivery_state = 'delivered', attempts = attempts + 1, updated_at = $3, finalized_at = $3,
    ambiguous = false, last_reason = NULL, last_status_code = 0
WHERE marketplace_account_id = $1 AND business_day = $2 AND delivery_state = 'sending'
RETURNING id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous
`

type MarkDigestDeliveryDeliveredParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	UpdatedAt            time.Time
}

// sending → delivered: the relay ACCEPTED the message and this write landed. The sole
// success transition; guarded on 'sending' so a re-drive after delivery matches nothing
// (idempotent no-op — zero resend).
func (q *Queries) MarkDigestDeliveryDelivered(ctx context.Context, arg MarkDigestDeliveryDeliveredParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, markDigestDeliveryDelivered, arg.MarketplaceAccountID, arg.BusinessDay, arg.UpdatedAt)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}

const markDigestDeliverySending = `-- name: MarkDigestDeliverySending :one

UPDATE notification_digest_deliveries
SET delivery_state = 'sending', ambiguous = $4, updated_at = $3
WHERE marketplace_account_id = $1 AND business_day = $2 AND delivery_state = 'pending'
RETURNING id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous
`

type MarkDigestDeliverySendingParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	UpdatedAt            time.Time
	Ambiguous            bool
}

// ATTEMPT ACCOUNTING. `attempts` is incremented EXACTLY ONCE per attempt, by whichever
// write CONCLUDES that attempt (bump, delivered, skipped, dead_letter, unconfirmed).
// The mid-attempt transitions — the 'sending' claim and the release back to 'pending'
// after a definitive non-acceptance — deliberately do NOT increment: incrementing on
// both the claim and the concluding write made the column read roughly double the truth,
// which silently halves the apparent headroom of the bounded per-account retry budget.
// pending → sending: the send is about to be INITIATED and its outcome becomes
// unknown until the relay answers. Committed BEFORE the SMTP conversation starts, so a
// crash mid-send leaves an ambiguity marker instead of a resend hazard. Guarded on
// 'pending' so a concurrent drive claims it at most once.
//
// $4 is the AMBIGUITY marker this attempt starts with. A mailer that can report its
// post-DATA boundary starts DEFINITIVE (false) and is narrowed upward by
// MarkDigestDeliveryAmbiguous at the real boundary; a mailer that cannot report it
// starts true, so the whole exchange is treated conservatively as the ambiguous window.
//
// last_reason / last_status_code are PRESERVED across the claim: erasing them at the
// start of every retry destroyed the previous attempt's diagnosis, so a flapping
// tenant's history could not be read off its own row.
func (q *Queries) MarkDigestDeliverySending(ctx context.Context, arg MarkDigestDeliverySendingParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, markDigestDeliverySending,
		arg.MarketplaceAccountID,
		arg.BusinessDay,
		arg.UpdatedAt,
		arg.Ambiguous,
	)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}

const markDigestDeliverySkipped = `-- name: MarkDigestDeliverySkipped :one
UPDATE notification_digest_deliveries
SET delivery_state = 'skipped', attempts = attempts + 1, updated_at = $3, finalized_at = $3,
    last_reason = $4, last_status_code = 0
WHERE marketplace_account_id = $1 AND business_day = $2 AND delivery_state = 'pending'
RETURNING id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous
`

type MarkDigestDeliverySkippedParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	UpdatedAt            time.Time
	LastReason           pgtype.Text
}

// pending → skipped: the day had nothing sendable (no eligible notification, or every
// eligible row was isolated by the closed message-schema check). Terminal and OBSERVED
// — not a failure, and never a silent drop.
func (q *Queries) MarkDigestDeliverySkipped(ctx context.Context, arg MarkDigestDeliverySkippedParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, markDigestDeliverySkipped,
		arg.MarketplaceAccountID,
		arg.BusinessDay,
		arg.UpdatedAt,
		arg.LastReason,
	)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}

const markDigestDeliveryUnconfirmed = `-- name: MarkDigestDeliveryUnconfirmed :one
UPDATE notification_digest_deliveries
SET delivery_state = 'unconfirmed', attempts = attempts + 1, updated_at = $3, finalized_at = $3,
    last_reason = $4, last_status_code = $5
WHERE marketplace_account_id = $1 AND business_day = $2
  AND delivery_state = 'sending' AND ambiguous
RETURNING id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous
`

type MarkDigestDeliveryUnconfirmedParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	UpdatedAt            time.Time
	LastReason           pgtype.Text
	LastStatusCode       int32
}

// sending → unconfirmed: TERMINAL AMBIGUOUS. The send was initiated, the exchange
// entered its post-DATA window, and acceptance could never be established (lost verdict,
// process crash, or exhausted attempts while still ambiguous). It does NOT claim
// delivery, and the row is never re-driven: zero resend outranks a speculative re-send
// repair (idempotency is never-cut; a duplicate delivery must never create a duplicate
// product event). Guarded on 'sending' AND on the durable ambiguity marker, so a row
// that provably never entered the window can NOT be written off as unconfirmed.
func (q *Queries) MarkDigestDeliveryUnconfirmed(ctx context.Context, arg MarkDigestDeliveryUnconfirmedParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, markDigestDeliveryUnconfirmed,
		arg.MarketplaceAccountID,
		arg.BusinessDay,
		arg.UpdatedAt,
		arg.LastReason,
		arg.LastStatusCode,
	)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = $3
WHERE id = $1 AND marketplace_account_id = $2 AND read_at IS NULL
RETURNING id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at
`

type MarkNotificationReadParams struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	ReadAt               pgtype.Timestamptz
}

// FROM-guarded read-state projection: only an UNREAD row owned by the account is
// marked read; an already-read or foreign row matches nothing and returns no row
// (the service treats that as an idempotent no-op — never a blind overwrite). This
// is the ONLY UPDATE on the append-only notification store.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.MarketplaceAccountID, arg.ReadAt)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.EventID,
		&i.DedupKey,
		&i.Category,
		&i.Severity,
		&i.BypassDigest,
		&i.TitleKey,
		&i.BodyKey,
		&i.BodyParams,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const markUrgentOutboxDeadLetter = `-- name: MarkUrgentOutboxDeadLetter :one
UPDATE notification_urgent_outbox
SET delivery_state = 'dead_letter', attempts = attempts + 1, updated_at = $3, last_error = $4
WHERE notification_id = $1 AND channel = $2 AND delivery_state = 'pending'
RETURNING id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at
`

type MarkUrgentOutboxDeadLetterParams struct {
	NotificationID uuid.UUID
	Channel        string
	UpdatedAt      time.Time
	LastError      pgtype.Text
}

// pending → dead_letter transition: a PERMANENT send failure becomes an OBSERVABLE
// terminal state (this durable row + a metric + a structured log). It does NOT mark
// the email delivered (no false "delivered"). Guarded by delivery_state = 'pending'.
// last_error is a bounded technical reason (never free text / Persian copy).
func (q *Queries) MarkUrgentOutboxDeadLetter(ctx context.Context, arg MarkUrgentOutboxDeadLetterParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, markUrgentOutboxDeadLetter,
		arg.NotificationID,
		arg.Channel,
		arg.UpdatedAt,
		arg.LastError,
	)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const markUrgentOutboxDelivered = `-- name: MarkUrgentOutboxDelivered :one
UPDATE notification_urgent_outbox
SET delivery_state = 'delivered', delivered_at = $3, attempts = attempts + 1, updated_at = $3, last_error = NULL
WHERE notification_id = $1 AND channel = $2 AND delivery_state = 'pending'
RETURNING id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at
`

type MarkUrgentOutboxDeliveredParams struct {
	NotificationID uuid.UUID
	Channel        string
	DeliveredAt    pgtype.Timestamptz
}

// pending → delivered transition (the ONLY success write; on the outbox projection,
// never on the append-only notification). Guarded by delivery_state = 'pending' so a
// concurrent/duplicate dispatch marks it at most once and a re-drive after delivery
// matches nothing (idempotent no-op — no duplicate logical email).
func (q *Queries) MarkUrgentOutboxDelivered(ctx context.Context, arg MarkUrgentOutboxDeliveredParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, markUrgentOutboxDelivered, arg.NotificationID, arg.Channel, arg.DeliveredAt)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const releaseDigestDeliveryToPending = `-- name: ReleaseDigestDeliveryToPending :one
UPDATE notification_digest_deliveries
SET delivery_state = 'pending', updated_at = $3, ambiguous = false,
    last_reason = $4, last_status_code = $5
WHERE marketplace_account_id = $1 AND business_day = $2 AND delivery_state = 'sending'
RETURNING id, marketplace_account_id, business_day, delivery_state, attempts, last_reason, last_status_code, created_at, updated_at, finalized_at, ambiguous
`

type ReleaseDigestDeliveryToPendingParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	UpdatedAt            time.Time
	LastReason           pgtype.Text
	LastStatusCode       int32
}

// sending → pending: the relay DEFINITIVELY did not accept the message (a typed SMTP
// response, or a failure before the body terminator was written), so a retry cannot
// duplicate it. Releasing the claim is only ever driven by a definitive non-acceptance —
// an UNKNOWN outcome stays 'sending' and is never released. last_reason is a bounded
// machine token; last_status_code is the numeric relay code (0 when none). The ambiguity
// marker is cleared with the release: the next attempt starts its own window.
func (q *Queries) ReleaseDigestDeliveryToPending(ctx context.Context, arg ReleaseDigestDeliveryToPendingParams) (NotificationDigestDelivery, error) {
	row := q.db.QueryRow(ctx, releaseDigestDeliveryToPending,
		arg.MarketplaceAccountID,
		arg.BusinessDay,
		arg.UpdatedAt,
		arg.LastReason,
		arg.LastStatusCode,
	)
	var i NotificationDigestDelivery
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastReason,
		&i.LastStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.Ambiguous,
	)
	return i, err
}
