// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE marketplace_account_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, marketplaceAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deliverNotification = `-- name: DeliverNotification :one

INSERT INTO notifications (
    marketplace_account_id, event_id, dedup_key, category, severity,
    bypass_digest, title_key, body_key, body_params
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (marketplace_account_id, dedup_key) DO NOTHING
RETURNING id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at
`

type DeliverNotificationParams struct {
	MarketplaceAccountID uuid.UUID
	EventID              uuid.UUID
	DedupKey             string
	Category             string
	Severity             string
	BypassDigest         bool
	TitleKey             string
	BodyKey              string
	BodyParams           []byte
}

// Notification queries (PRD §7.5 NOT-001). notifications, notification_digests,
// and notification_digest_items are APPEND-ONLY (INSERT/SELECT); the sole mutable
// column is notifications.read_at, advanced by ONE FROM-guarded UPDATE below.
// Delivers one in-app notification (NOT-001). ON CONFLICT DO NOTHING on the
// (marketplace_account_id, dedup_key) key: a duplicate delivery inserts nothing
// and returns NO row, so duplicate delivery can NEVER create a duplicate product
// event. The caller treats pgx.ErrNoRows as "already delivered" (idempotent).
func (q *Queries) DeliverNotification(ctx context.Context, arg DeliverNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, deliverNotification,
		arg.MarketplaceAccountID,
		arg.EventID,
		arg.DedupKey,
		arg.Category,
		arg.Severity,
		arg.BypassDigest,
		arg.TitleKey,
		arg.BodyKey,
		arg.BodyParams,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.EventID,
		&i.DedupKey,
		&i.Category,
		&i.Severity,
		&i.BypassDigest,
		&i.TitleKey,
		&i.BodyKey,
		&i.BodyParams,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getDigestByAccountDay = `-- name: GetDigestByAccountDay :one
SELECT id, marketplace_account_id, business_day, generated_at, item_count FROM notification_digests
WHERE marketplace_account_id = $1 AND business_day = $2
`

type GetDigestByAccountDayParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
}

func (q *Queries) GetDigestByAccountDay(ctx context.Context, arg GetDigestByAccountDayParams) (NotificationDigest, error) {
	row := q.db.QueryRow(ctx, getDigestByAccountDay, arg.MarketplaceAccountID, arg.BusinessDay)
	var i NotificationDigest
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.GeneratedAt,
		&i.ItemCount,
	)
	return i, err
}

const getDigestRecipientEmail = `-- name: GetDigestRecipientEmail :one
SELECT u.email
FROM marketplace_accounts ma
JOIN users u ON u.organization_id = ma.organization_id
WHERE ma.id = $1
ORDER BY (u.role = 'owner') DESC, u.created_at, u.id
LIMIT 1
`

// The digest recipient for an account: the organization's owner user email,
// falling back to the earliest user when no owner role exists. Returns no row when
// the organization has no users (the digest is then unsendable — fail closed).
func (q *Queries) GetDigestRecipientEmail(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getDigestRecipientEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getNotificationByDedup = `-- name: GetNotificationByDedup :one
SELECT id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at FROM notifications
WHERE marketplace_account_id = $1 AND dedup_key = $2
`

type GetNotificationByDedupParams struct {
	MarketplaceAccountID uuid.UUID
	DedupKey             string
}

// Reads the existing notification for a dedup key (used to return the SAME row on
// an idempotent re-delivery so both surfaces reference the SAME event id).
func (q *Queries) GetNotificationByDedup(ctx context.Context, arg GetNotificationByDedupParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByDedup, arg.MarketplaceAccountID, arg.DedupKey)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.EventID,
		&i.DedupKey,
		&i.Category,
		&i.Severity,
		&i.BypassDigest,
		&i.TitleKey,
		&i.BodyKey,
		&i.BodyParams,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const insertDigest = `-- name: InsertDigest :one
INSERT INTO notification_digests (marketplace_account_id, business_day, generated_at, item_count)
VALUES ($1, $2, $3, $4)
ON CONFLICT (marketplace_account_id, business_day) DO NOTHING
RETURNING id, marketplace_account_id, business_day, generated_at, item_count
`

type InsertDigestParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	GeneratedAt          time.Time
	ItemCount            int32
}

// Opens the once-per-business-day digest header. ON CONFLICT DO NOTHING makes the
// River digest job idempotent per business day: a retry inserts nothing and
// returns no row (no duplicate digest, no duplicate send).
func (q *Queries) InsertDigest(ctx context.Context, arg InsertDigestParams) (NotificationDigest, error) {
	row := q.db.QueryRow(ctx, insertDigest,
		arg.MarketplaceAccountID,
		arg.BusinessDay,
		arg.GeneratedAt,
		arg.ItemCount,
	)
	var i NotificationDigest
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.GeneratedAt,
		&i.ItemCount,
	)
	return i, err
}

const insertDigestItem = `-- name: InsertDigestItem :one
INSERT INTO notification_digest_items (digest_id, notification_id, event_id)
VALUES ($1, $2, $3)
RETURNING id, digest_id, notification_id, event_id
`

type InsertDigestItemParams struct {
	DigestID       uuid.UUID
	NotificationID uuid.UUID
	EventID        uuid.UUID
}

// Appends one notification (with its SHARED event id) to a digest's membership
// snapshot. APPEND-ONLY.
func (q *Queries) InsertDigestItem(ctx context.Context, arg InsertDigestItemParams) (NotificationDigestItem, error) {
	row := q.db.QueryRow(ctx, insertDigestItem, arg.DigestID, arg.NotificationID, arg.EventID)
	var i NotificationDigestItem
	err := row.Scan(
		&i.ID,
		&i.DigestID,
		&i.NotificationID,
		&i.EventID,
	)
	return i, err
}

const listDigestItems = `-- name: ListDigestItems :many
SELECT id, digest_id, notification_id, event_id FROM notification_digest_items
WHERE digest_id = $1
ORDER BY id
`

// The membership of one digest, in insertion order (the shared event ids).
func (q *Queries) ListDigestItems(ctx context.Context, digestID uuid.UUID) ([]NotificationDigestItem, error) {
	rows, err := q.db.Query(ctx, listDigestItems, digestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDigestItem{}
	for rows.Next() {
		var i NotificationDigestItem
		if err := rows.Scan(
			&i.ID,
			&i.DigestID,
			&i.NotificationID,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at FROM notifications
WHERE marketplace_account_id = $1
ORDER BY created_at DESC, id
`

// The in-app notification feed for an account, newest first.
func (q *Queries) ListNotifications(ctx context.Context, marketplaceAccountID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.EventID,
			&i.DedupKey,
			&i.Category,
			&i.Severity,
			&i.BypassDigest,
			&i.TitleKey,
			&i.BodyKey,
			&i.BodyParams,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDigestNotifications = `-- name: ListPendingDigestNotifications :many
SELECT id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at FROM notifications
WHERE marketplace_account_id = $1
  AND bypass_digest = false
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at, id
`

type ListPendingDigestNotificationsParams struct {
	MarketplaceAccountID uuid.UUID
	CreatedAt            time.Time
	CreatedAt_2          time.Time
}

// The notifications eligible for the batched daily digest for one account and
// business day: NOT bypass_digest (execution/safety failures bypass the digest and
// were delivered immediately) and created within the business-day window. Oldest
// first so the digest reads in occurrence order. Shared event ids flow through.
func (q *Queries) ListPendingDigestNotifications(ctx context.Context, arg ListPendingDigestNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listPendingDigestNotifications, arg.MarketplaceAccountID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.EventID,
			&i.DedupKey,
			&i.Category,
			&i.Severity,
			&i.BypassDigest,
			&i.TitleKey,
			&i.BodyKey,
			&i.BodyParams,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = $3
WHERE id = $1 AND marketplace_account_id = $2 AND read_at IS NULL
RETURNING id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at
`

type MarkNotificationReadParams struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	ReadAt               pgtype.Timestamptz
}

// FROM-guarded read-state projection: only an UNREAD row owned by the account is
// marked read; an already-read or foreign row matches nothing and returns no row
// (the service treats that as an idempotent no-op — never a blind overwrite). This
// is the ONLY UPDATE on the append-only notification store.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.MarketplaceAccountID, arg.ReadAt)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.EventID,
		&i.DedupKey,
		&i.Category,
		&i.Severity,
		&i.BypassDigest,
		&i.TitleKey,
		&i.BodyKey,
		&i.BodyParams,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}
