// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpUrgentOutboxAttempt = `-- name: BumpUrgentOutboxAttempt :one
UPDATE notification_urgent_outbox
SET attempts = attempts + 1, updated_at = $3, last_error = $4
WHERE notification_id = $1 AND channel = $2 AND delivery_state = 'pending'
RETURNING id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at
`

type BumpUrgentOutboxAttemptParams struct {
	NotificationID uuid.UUID
	Channel        string
	UpdatedAt      time.Time
	LastError      pgtype.Text
}

// Records a TRANSIENT failed attempt while the row stays pending (attempts + bounded
// last_error), so a retry is observable without a state transition. Guarded by
// delivery_state = 'pending'.
func (q *Queries) BumpUrgentOutboxAttempt(ctx context.Context, arg BumpUrgentOutboxAttemptParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, bumpUrgentOutboxAttempt,
		arg.NotificationID,
		arg.Channel,
		arg.UpdatedAt,
		arg.LastError,
	)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE marketplace_account_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, marketplaceAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deliverNotification = `-- name: DeliverNotification :one

INSERT INTO notifications (
    marketplace_account_id, event_id, dedup_key, category, severity,
    bypass_digest, title_key, body_key, body_params
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (marketplace_account_id, dedup_key) DO NOTHING
RETURNING id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at
`

type DeliverNotificationParams struct {
	MarketplaceAccountID uuid.UUID
	EventID              uuid.UUID
	DedupKey             string
	Category             string
	Severity             string
	BypassDigest         bool
	TitleKey             string
	BodyKey              string
	BodyParams           []byte
}

// Notification queries (PRD §7.5 NOT-001). notifications, notification_digests,
// and notification_digest_items are APPEND-ONLY (INSERT/SELECT); the sole mutable
// column is notifications.read_at, advanced by ONE FROM-guarded UPDATE below.
// Delivers one in-app notification (NOT-001). ON CONFLICT DO NOTHING on the
// (marketplace_account_id, dedup_key) key: a duplicate delivery inserts nothing
// and returns NO row, so duplicate delivery can NEVER create a duplicate product
// event. The caller treats pgx.ErrNoRows as "already delivered" (idempotent).
func (q *Queries) DeliverNotification(ctx context.Context, arg DeliverNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, deliverNotification,
		arg.MarketplaceAccountID,
		arg.EventID,
		arg.DedupKey,
		arg.Category,
		arg.Severity,
		arg.BypassDigest,
		arg.TitleKey,
		arg.BodyKey,
		arg.BodyParams,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.EventID,
		&i.DedupKey,
		&i.Category,
		&i.Severity,
		&i.BypassDigest,
		&i.TitleKey,
		&i.BodyKey,
		&i.BodyParams,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getDigestByAccountDay = `-- name: GetDigestByAccountDay :one
SELECT id, marketplace_account_id, business_day, generated_at, item_count FROM notification_digests
WHERE marketplace_account_id = $1 AND business_day = $2
`

type GetDigestByAccountDayParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
}

func (q *Queries) GetDigestByAccountDay(ctx context.Context, arg GetDigestByAccountDayParams) (NotificationDigest, error) {
	row := q.db.QueryRow(ctx, getDigestByAccountDay, arg.MarketplaceAccountID, arg.BusinessDay)
	var i NotificationDigest
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.GeneratedAt,
		&i.ItemCount,
	)
	return i, err
}

const getDigestRecipientEmail = `-- name: GetDigestRecipientEmail :one
SELECT u.email
FROM marketplace_accounts ma
JOIN users u ON u.organization_id = ma.organization_id
WHERE ma.id = $1
ORDER BY (u.role = 'owner') DESC, u.created_at, u.id
LIMIT 1
`

// The digest recipient for an account: the organization's owner user email,
// falling back to the earliest user when no owner role exists. Returns no row when
// the organization has no users (the digest is then unsendable — fail closed).
func (q *Queries) GetDigestRecipientEmail(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getDigestRecipientEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getNotificationByDedup = `-- name: GetNotificationByDedup :one
SELECT id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at FROM notifications
WHERE marketplace_account_id = $1 AND dedup_key = $2
`

type GetNotificationByDedupParams struct {
	MarketplaceAccountID uuid.UUID
	DedupKey             string
}

// Reads the existing notification for a dedup key (used to return the SAME row on
// an idempotent re-delivery so both surfaces reference the SAME event id).
func (q *Queries) GetNotificationByDedup(ctx context.Context, arg GetNotificationByDedupParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByDedup, arg.MarketplaceAccountID, arg.DedupKey)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.EventID,
		&i.DedupKey,
		&i.Category,
		&i.Severity,
		&i.BypassDigest,
		&i.TitleKey,
		&i.BodyKey,
		&i.BodyParams,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getUrgentOutbox = `-- name: GetUrgentOutbox :one
SELECT id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at FROM notification_urgent_outbox
WHERE notification_id = $1 AND channel = $2
`

type GetUrgentOutboxParams struct {
	NotificationID uuid.UUID
	Channel        string
}

// Reads the urgent outbox row for a notification+channel so the dispatcher can make
// its idempotent decision (already delivered / dead-lettered → no-op).
func (q *Queries) GetUrgentOutbox(ctx context.Context, arg GetUrgentOutboxParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, getUrgentOutbox, arg.NotificationID, arg.Channel)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const insertDigest = `-- name: InsertDigest :one
INSERT INTO notification_digests (marketplace_account_id, business_day, generated_at, item_count)
VALUES ($1, $2, $3, $4)
ON CONFLICT (marketplace_account_id, business_day) DO NOTHING
RETURNING id, marketplace_account_id, business_day, generated_at, item_count
`

type InsertDigestParams struct {
	MarketplaceAccountID uuid.UUID
	BusinessDay          pgtype.Date
	GeneratedAt          time.Time
	ItemCount            int32
}

// Opens the once-per-business-day digest header. ON CONFLICT DO NOTHING makes the
// River digest job idempotent per business day: a retry inserts nothing and
// returns no row (no duplicate digest, no duplicate send).
func (q *Queries) InsertDigest(ctx context.Context, arg InsertDigestParams) (NotificationDigest, error) {
	row := q.db.QueryRow(ctx, insertDigest,
		arg.MarketplaceAccountID,
		arg.BusinessDay,
		arg.GeneratedAt,
		arg.ItemCount,
	)
	var i NotificationDigest
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.BusinessDay,
		&i.GeneratedAt,
		&i.ItemCount,
	)
	return i, err
}

const insertDigestItem = `-- name: InsertDigestItem :one
INSERT INTO notification_digest_items (digest_id, notification_id, event_id)
VALUES ($1, $2, $3)
RETURNING id, digest_id, notification_id, event_id
`

type InsertDigestItemParams struct {
	DigestID       uuid.UUID
	NotificationID uuid.UUID
	EventID        uuid.UUID
}

// Appends one notification (with its SHARED event id) to a digest's membership
// snapshot. APPEND-ONLY.
func (q *Queries) InsertDigestItem(ctx context.Context, arg InsertDigestItemParams) (NotificationDigestItem, error) {
	row := q.db.QueryRow(ctx, insertDigestItem, arg.DigestID, arg.NotificationID, arg.EventID)
	var i NotificationDigestItem
	err := row.Scan(
		&i.ID,
		&i.DigestID,
		&i.NotificationID,
		&i.EventID,
	)
	return i, err
}

const insertUrgentOutbox = `-- name: InsertUrgentOutbox :one
INSERT INTO notification_urgent_outbox (notification_id, marketplace_account_id, channel)
VALUES ($1, $2, $3)
ON CONFLICT (notification_id, channel) DO NOTHING
RETURNING id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at
`

type InsertUrgentOutboxParams struct {
	NotificationID       uuid.UUID
	MarketplaceAccountID uuid.UUID
	Channel              string
}

// Opens the DURABLE urgent-delivery outbox row for a bypass (execution/safety)
// notification. Inserted in the SAME transaction that commits the notification, so a
// crash before the email sends still completes delivery on restart (issue #122). ON
// CONFLICT DO NOTHING on the (notification_id, channel) idempotency key: a re-driven
// delivery inserts nothing and returns no row (the caller treats pgx.ErrNoRows as
// "already enqueued" — no duplicate logical email). APPEND on this projection; state
// is mutated only by the guarded transitions below (never on notifications/audit).
func (q *Queries) InsertUrgentOutbox(ctx context.Context, arg InsertUrgentOutboxParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, insertUrgentOutbox, arg.NotificationID, arg.MarketplaceAccountID, arg.Channel)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const listDigestItems = `-- name: ListDigestItems :many
SELECT id, digest_id, notification_id, event_id FROM notification_digest_items
WHERE digest_id = $1
ORDER BY id
`

// The membership of one digest, in insertion order (the shared event ids).
func (q *Queries) ListDigestItems(ctx context.Context, digestID uuid.UUID) ([]NotificationDigestItem, error) {
	rows, err := q.db.Query(ctx, listDigestItems, digestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDigestItem{}
	for rows.Next() {
		var i NotificationDigestItem
		if err := rows.Scan(
			&i.ID,
			&i.DigestID,
			&i.NotificationID,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsPage = `-- name: ListNotificationsPage :many
SELECT id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at FROM notifications
WHERE marketplace_account_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListNotificationsPageParams struct {
	MarketplaceAccountID uuid.UUID
	CursorCreatedAt      pgtype.Timestamptz
	CursorID             pgtype.UUID
	PageLimit            int32
}

// The in-app notification feed for an account, newest first, BOUNDED by a keyset
// cursor (§17 bounded reads). Deterministic order is (created_at DESC, id DESC);
// the row-value comparison (created_at, id) < (cursor_created_at, cursor_id) reads
// STRICTLY OLDER rows than the cursor position, so ties on created_at are broken by
// id and every row is returned EXACTLY ONCE across pages (no duplicate, no skip). A
// NULL cursor (cursor_created_at IS NULL) is the first (newest) page. The caller
// passes page_limit = requested_limit + 1 and treats the extra row as the hasMore
// signal (then trims it). SELECT-only: the notifications store stays append-only.
// Backed by idx_notifications_account_created_id (marketplace_account_id,
// created_at DESC, id DESC) so the plan is an index range scan, never a full history
// scan. account-scoped WHERE is the authorization; the cursor is only a position.
func (q *Queries) ListNotificationsPage(ctx context.Context, arg ListNotificationsPageParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsPage,
		arg.MarketplaceAccountID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.EventID,
			&i.DedupKey,
			&i.Category,
			&i.Severity,
			&i.BypassDigest,
			&i.TitleKey,
			&i.BodyKey,
			&i.BodyParams,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDigestNotifications = `-- name: ListPendingDigestNotifications :many
SELECT id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at FROM notifications
WHERE marketplace_account_id = $1
  AND bypass_digest = false
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at, id
`

type ListPendingDigestNotificationsParams struct {
	MarketplaceAccountID uuid.UUID
	CreatedAt            time.Time
	CreatedAt_2          time.Time
}

// The notifications eligible for the batched daily digest for one account and
// business day: NOT bypass_digest (execution/safety failures bypass the digest and
// were delivered immediately) and created within the business-day window. Oldest
// first so the digest reads in occurrence order. Shared event ids flow through.
func (q *Queries) ListPendingDigestNotifications(ctx context.Context, arg ListPendingDigestNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listPendingDigestNotifications, arg.MarketplaceAccountID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.EventID,
			&i.DedupKey,
			&i.Category,
			&i.Severity,
			&i.BypassDigest,
			&i.TitleKey,
			&i.BodyKey,
			&i.BodyParams,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = $3
WHERE id = $1 AND marketplace_account_id = $2 AND read_at IS NULL
RETURNING id, marketplace_account_id, event_id, dedup_key, category, severity, bypass_digest, title_key, body_key, body_params, created_at, read_at
`

type MarkNotificationReadParams struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	ReadAt               pgtype.Timestamptz
}

// FROM-guarded read-state projection: only an UNREAD row owned by the account is
// marked read; an already-read or foreign row matches nothing and returns no row
// (the service treats that as an idempotent no-op — never a blind overwrite). This
// is the ONLY UPDATE on the append-only notification store.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.MarketplaceAccountID, arg.ReadAt)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.EventID,
		&i.DedupKey,
		&i.Category,
		&i.Severity,
		&i.BypassDigest,
		&i.TitleKey,
		&i.BodyKey,
		&i.BodyParams,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const markUrgentOutboxDeadLetter = `-- name: MarkUrgentOutboxDeadLetter :one
UPDATE notification_urgent_outbox
SET delivery_state = 'dead_letter', attempts = attempts + 1, updated_at = $3, last_error = $4
WHERE notification_id = $1 AND channel = $2 AND delivery_state = 'pending'
RETURNING id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at
`

type MarkUrgentOutboxDeadLetterParams struct {
	NotificationID uuid.UUID
	Channel        string
	UpdatedAt      time.Time
	LastError      pgtype.Text
}

// pending → dead_letter transition: a PERMANENT send failure becomes an OBSERVABLE
// terminal state (this durable row + a metric + a structured log). It does NOT mark
// the email delivered (no false "delivered"). Guarded by delivery_state = 'pending'.
// last_error is a bounded technical reason (never free text / Persian copy).
func (q *Queries) MarkUrgentOutboxDeadLetter(ctx context.Context, arg MarkUrgentOutboxDeadLetterParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, markUrgentOutboxDeadLetter,
		arg.NotificationID,
		arg.Channel,
		arg.UpdatedAt,
		arg.LastError,
	)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const markUrgentOutboxDelivered = `-- name: MarkUrgentOutboxDelivered :one
UPDATE notification_urgent_outbox
SET delivery_state = 'delivered', delivered_at = $3, attempts = attempts + 1, updated_at = $3, last_error = NULL
WHERE notification_id = $1 AND channel = $2 AND delivery_state = 'pending'
RETURNING id, notification_id, marketplace_account_id, channel, delivery_state, attempts, last_error, created_at, updated_at, delivered_at
`

type MarkUrgentOutboxDeliveredParams struct {
	NotificationID uuid.UUID
	Channel        string
	DeliveredAt    pgtype.Timestamptz
}

// pending → delivered transition (the ONLY success write; on the outbox projection,
// never on the append-only notification). Guarded by delivery_state = 'pending' so a
// concurrent/duplicate dispatch marks it at most once and a re-drive after delivery
// matches nothing (idempotent no-op — no duplicate logical email).
func (q *Queries) MarkUrgentOutboxDelivered(ctx context.Context, arg MarkUrgentOutboxDeliveredParams) (NotificationUrgentOutbox, error) {
	row := q.db.QueryRow(ctx, markUrgentOutboxDelivered, arg.NotificationID, arg.Channel, arg.DeliveredAt)
	var i NotificationUrgentOutbox
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.MarketplaceAccountID,
		&i.Channel,
		&i.DeliveryState,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredAt,
	)
	return i, err
}
