// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observation.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceObservationCursor = `-- name: AdvanceObservationCursor :exec
INSERT INTO observation_consumer_cursors (
    target_id, marketplace_account_id, native_seller_id, offer_identity,
    last_observation_id, last_captured_at, last_price_raw_value
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (target_id, native_seller_id, offer_identity) DO UPDATE SET
    last_observation_id  = EXCLUDED.last_observation_id,
    last_captured_at     = EXCLUDED.last_captured_at,
    last_price_raw_value = EXCLUDED.last_price_raw_value,
    updated_at           = now()
WHERE (EXCLUDED.last_captured_at, EXCLUDED.last_observation_id)
    > (observation_consumer_cursors.last_captured_at, observation_consumer_cursors.last_observation_id)
`

type AdvanceObservationCursorParams struct {
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	NativeSellerID       string
	OfferIdentity        string
	LastObservationID    uuid.UUID
	LastCapturedAt       time.Time
	LastPriceRawValue    string
}

// Advance (or create) a stream's durable consumer position. MONOTONIC: an existing
// cursor moves forward only when the incoming (captured_at, observation_id) is
// strictly greater, so an out-of-order or replayed advance never rewinds the
// stream. Called inside the SAME transaction as the event write + ledger insert so
// the position, the event, and the ingestion-idempotency record commit atomically.
func (q *Queries) AdvanceObservationCursor(ctx context.Context, arg AdvanceObservationCursorParams) error {
	_, err := q.db.Exec(ctx, advanceObservationCursor,
		arg.TargetID,
		arg.MarketplaceAccountID,
		arg.NativeSellerID,
		arg.OfferIdentity,
		arg.LastObservationID,
		arg.LastCapturedAt,
		arg.LastPriceRawValue,
	)
	return err
}

const claimDedupKey = `-- name: ClaimDedupKey :one
WITH ins AS (
    INSERT INTO observation_dedup (dedup_key, target_id, route, offer_identity, evidence_hash)
    VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (dedup_key) DO NOTHING
    RETURNING dedup_key, evidence_hash
)
SELECT dedup_key, evidence_hash, true AS inserted FROM ins
UNION ALL
SELECT d.dedup_key, d.evidence_hash, false AS inserted
    FROM observation_dedup d
    WHERE d.dedup_key = $1 AND NOT EXISTS (SELECT 1 FROM ins)
`

type ClaimDedupKeyParams struct {
	DedupKey      string
	TargetID      uuid.UUID
	Route         string
	OfferIdentity string
	EvidenceHash  string
}

type ClaimDedupKeyRow struct {
	DedupKey     string
	EvidenceHash string
	Inserted     bool
}

// OBS-008 atomic dedup with evidence-hash comparison (issue #44). Returns EXACTLY
// one row describing the outcome of the claim:
//   - inserted = true  → first sighting: the row was freshly inserted with the
//     incoming evidence_hash (accept the observation).
//   - inserted = false → the key already existed: the row carries the STORED
//     (original) evidence_hash, so the caller can compare it to
//     the incoming hash. Equal ⇒ a true replay (idempotent
//     no-op); UNEQUAL ⇒ a material conflict (fail closed, record
//     it, never overwrite the authoritative current offer).
//
// The key carries the route, so a different route observing the same value is a
// distinct claim and is retained: route provenance is never collapsed away.
func (q *Queries) ClaimDedupKey(ctx context.Context, arg ClaimDedupKeyParams) (ClaimDedupKeyRow, error) {
	row := q.db.QueryRow(ctx, claimDedupKey,
		arg.DedupKey,
		arg.TargetID,
		arg.Route,
		arg.OfferIdentity,
		arg.EvidenceHash,
	)
	var i ClaimDedupKeyRow
	err := row.Scan(&i.DedupKey, &i.EvidenceHash, &i.Inserted)
	return i, err
}

const closeObservedOffer = `-- name: CloseObservedOffer :one
UPDATE observed_offers SET
    availability_status = 'disappeared',
    quality             = 'unavailable',
    ended_at            = $2,
    last_observation_id = $3,
    updated_at          = now()
WHERE target_id = $1 AND offer_identity = $4
RETURNING id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at
`

type CloseObservedOfferParams struct {
	TargetID          uuid.UUID
	EndedAt           pgtype.Timestamptz
	LastObservationID uuid.UUID
	OfferIdentity     string
}

// §16 offer disappearance: close the current offer with an END TIME. The last raw
// price is left intact — it is NEVER converted to a zero price. Availability
// becomes 'disappeared' and quality 'unavailable'.
func (q *Queries) CloseObservedOffer(ctx context.Context, arg CloseObservedOfferParams) (ObservedOffer, error) {
	row := q.db.QueryRow(ctx, closeObservedOffer,
		arg.TargetID,
		arg.EndedAt,
		arg.LastObservationID,
		arg.OfferIdentity,
	)
	var i ObservedOffer
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.MarketplaceAccountID,
		&i.OfferIdentity,
		&i.NativeVariantID,
		&i.NativeSellerID,
		&i.PriceRawText,
		&i.PriceRawValue,
		&i.PriceRawUnit,
		&i.ListPriceRawText,
		&i.ListPriceRawValue,
		&i.ListPriceRawUnit,
		&i.AvailabilityStatus,
		&i.StockSignal,
		&i.Quality,
		&i.CapturedAt,
		&i.FreshnessDeadline,
		&i.Routes,
		&i.LastObservationID,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveTargetsForIdentity = `-- name: CountActiveTargetsForIdentity :one
SELECT count(*) FROM observation_targets
WHERE identity_id = $1 AND active = true
`

// Test/introspection helper: how many ACTIVE targets an identity still owns.
func (q *Queries) CountActiveTargetsForIdentity(ctx context.Context, identityID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTargetsForIdentity, identityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createObservationTargetsFromConfirmed = `-- name: CreateObservationTargetsFromConfirmed :many
INSERT INTO observation_targets (
    marketplace_account_id, identity_id, variant_id, native_variant_id,
    native_product_id, tier, cadence_seconds, freshness_deadline_seconds
)
SELECT mpi.marketplace_account_id, mpi.id, mpi.variant_id, mpi.native_variant_id,
       mpi.native_product_id, $2, $3, $4
FROM market_product_identities mpi
WHERE mpi.marketplace_account_id = $1
  AND mpi.state = 'confirmed'
  AND mpi.active = true
ON CONFLICT (identity_id) DO NOTHING
RETURNING id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at
`

type CreateObservationTargetsFromConfirmedParams struct {
	MarketplaceAccountID     uuid.UUID
	Tier                     string
	CadenceSeconds           int32
	FreshnessDeadlineSeconds int32
}

// OBS-001 auto-create: a target for EXACTLY the account's active Confirmed
// mappings that do not yet have one. NeedsReview/Rejected/Obsolete are excluded by
// construction, and the trigger is a second guard. Idempotent via ON CONFLICT.
func (q *Queries) CreateObservationTargetsFromConfirmed(ctx context.Context, arg CreateObservationTargetsFromConfirmedParams) ([]ObservationTarget, error) {
	rows, err := q.db.Query(ctx, createObservationTargetsFromConfirmed,
		arg.MarketplaceAccountID,
		arg.Tier,
		arg.CadenceSeconds,
		arg.FreshnessDeadlineSeconds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationTarget{}
	for rows.Next() {
		var i ObservationTarget
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.IdentityID,
			&i.VariantID,
			&i.NativeVariantID,
			&i.NativeProductID,
			&i.Tier,
			&i.CadenceSeconds,
			&i.FreshnessDeadlineSeconds,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateObservationTargetsForIdentity = `-- name: DeactivateObservationTargetsForIdentity :many
UPDATE observation_targets SET
    active     = false,
    updated_at = now()
WHERE identity_id = $1 AND active = true
RETURNING id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at
`

// OBS-001 carry-forward from S13: when a Confirmed identity is REOPENED
// (NeedsReview/Rejected/Obsolete) its observation target must stop producing
// executable observations — an identity that has left the executable set can no
// longer own a live target. This DEACTIVATES (never deletes) the target so the
// append-only observation history and its provenance stay intact; the scheduler
// and executable-path queries filter on active = true, so a deactivated target is
// silently dropped from every fetch and recommendation. Idempotent: a re-delivery
// of the reopen event finds the target already inactive and changes nothing.
// OBS-007: this disables only the dependent capability; it never relabels the
// target's already-stored observations as current.
func (q *Queries) DeactivateObservationTargetsForIdentity(ctx context.Context, identityID uuid.UUID) ([]ObservationTarget, error) {
	rows, err := q.db.Query(ctx, deactivateObservationTargetsForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationTarget{}
	for rows.Next() {
		var i ObservationTarget
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.IdentityID,
			&i.VariantID,
			&i.NativeVariantID,
			&i.NativeProductID,
			&i.Tier,
			&i.CadenceSeconds,
			&i.FreshnessDeadlineSeconds,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downgradeObservedOffersForDrift = `-- name: DowngradeObservedOffersForDrift :execrows
UPDATE observed_offers SET
    quality    = CASE WHEN availability_status = 'disappeared'
                      THEN 'unavailable' ELSE 'stale' END,
    updated_at = now()
WHERE target_id = $1
  AND ended_at IS NULL
  AND quality NOT IN ('stale', 'unavailable', 'conflicted')
`

// §10.4 parser-drift stop rule on the derived current view: when Route C detects
// drift for a target (parse failure, failed canary, product-identity mismatch, or
// an already-paused guard), the target's LIVE current offers must stop reading as
// current before any consumer sees them. Each live offer is downgraded so it can no
// longer satisfy the current-data gate: to 'unavailable' when it carries no usable
// value (a disappeared offer), else to 'stale' (renders age-only). Mirrors
// PausedQuality (Stale if had value, else Unavailable). This touches ONLY the
// derived projection — the append-only observations evidence table is never
// modified. Idempotent and one-directional: offers already stale/unavailable/
// conflicted are excluded, so a re-run is a no-op and a more-restrictive state is
// never loosened.
func (q *Queries) DowngradeObservedOffersForDrift(ctx context.Context, targetID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, downgradeObservedOffersForDrift, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getObservationForAccount = `-- name: GetObservationForAccount :one
SELECT id, marketplace_account_id, target_id, quality, freshness_deadline,
       captured_at, evidence_ref
FROM observations
WHERE id = $1 AND marketplace_account_id = $2
LIMIT 1
`

type GetObservationForAccountParams struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
}

type GetObservationForAccountRow struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	TargetID             uuid.UUID
	Quality              string
	FreshnessDeadline    time.Time
	CapturedAt           time.Time
	EvidenceRef          string
}

// ACCOUNT-SCOPED single-observation load for the S15 event-evidence derivation
// (#70, evidence-quality never-cut §4.6). The event boundary must DERIVE its quality
// and provenance from a real, account-bound observation rather than trust a caller-
// supplied token, so RecordFor loads the cited observation inside the SAME account-
// scoped transaction as the event write and copies the quality/ref AS-IS. The predicate
// is (id, marketplace_account_id): a random or foreign-account id resolves to NO row
// (fail closed, no cross-tenant existence oracle). observations is PARTITIONED with PK
// (id, captured_at) so id is not independently unique across partitions; LIMIT 1
// returns the single logical row (id is a gen_random_uuid, unique in practice).
func (q *Queries) GetObservationForAccount(ctx context.Context, arg GetObservationForAccountParams) (GetObservationForAccountRow, error) {
	row := q.db.QueryRow(ctx, getObservationForAccount, arg.ID, arg.MarketplaceAccountID)
	var i GetObservationForAccountRow
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.TargetID,
		&i.Quality,
		&i.FreshnessDeadline,
		&i.CapturedAt,
		&i.EvidenceRef,
	)
	return i, err
}

const getObservationTarget = `-- name: GetObservationTarget :one
SELECT id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at FROM observation_targets WHERE id = $1
`

func (q *Queries) GetObservationTarget(ctx context.Context, id uuid.UUID) (ObservationTarget, error) {
	row := q.db.QueryRow(ctx, getObservationTarget, id)
	var i ObservationTarget
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.IdentityID,
		&i.VariantID,
		&i.NativeVariantID,
		&i.NativeProductID,
		&i.Tier,
		&i.CadenceSeconds,
		&i.FreshnessDeadlineSeconds,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getObservedOffer = `-- name: GetObservedOffer :one
SELECT id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at FROM observed_offers
WHERE target_id = $1 AND offer_identity = $2
`

type GetObservedOfferParams struct {
	TargetID      uuid.UUID
	OfferIdentity string
}

func (q *Queries) GetObservedOffer(ctx context.Context, arg GetObservedOfferParams) (ObservedOffer, error) {
	row := q.db.QueryRow(ctx, getObservedOffer, arg.TargetID, arg.OfferIdentity)
	var i ObservedOffer
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.MarketplaceAccountID,
		&i.OfferIdentity,
		&i.NativeVariantID,
		&i.NativeSellerID,
		&i.PriceRawText,
		&i.PriceRawValue,
		&i.PriceRawUnit,
		&i.ListPriceRawText,
		&i.ListPriceRawValue,
		&i.ListPriceRawUnit,
		&i.AvailabilityStatus,
		&i.StockSignal,
		&i.Quality,
		&i.CapturedAt,
		&i.FreshnessDeadline,
		&i.Routes,
		&i.LastObservationID,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDedupConflict = `-- name: InsertDedupConflict :one
INSERT INTO observation_dedup_conflicts (
    dedup_key, target_id, marketplace_account_id, route, offer_identity,
    stored_evidence_hash, conflicting_evidence_hash, conflicting_observation_id,
    conflicting_envelope
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, dedup_key, target_id, marketplace_account_id, route, offer_identity, stored_evidence_hash, conflicting_evidence_hash, conflicting_observation_id, conflicting_envelope, detected_at
`

type InsertDedupConflictParams struct {
	DedupKey                 string
	TargetID                 uuid.UUID
	MarketplaceAccountID     uuid.UUID
	Route                    string
	OfferIdentity            string
	StoredEvidenceHash       string
	ConflictingEvidenceHash  string
	ConflictingObservationID pgtype.UUID
	ConflictingEnvelope      []byte
}

// APPEND-ONLY dedup conflict record (issue #44). Written when a capture collides on
// the dedup key but carries a materially different evidence envelope (its canonical
// evidence hash differs from the stored one). Preserves BOTH hashes and the full
// conflicting envelope (raw tokens, money quarantine) so the dropped evidence is
// auditable — the second capture is never silently lost. INSERT-only.
func (q *Queries) InsertDedupConflict(ctx context.Context, arg InsertDedupConflictParams) (ObservationDedupConflict, error) {
	row := q.db.QueryRow(ctx, insertDedupConflict,
		arg.DedupKey,
		arg.TargetID,
		arg.MarketplaceAccountID,
		arg.Route,
		arg.OfferIdentity,
		arg.StoredEvidenceHash,
		arg.ConflictingEvidenceHash,
		arg.ConflictingObservationID,
		arg.ConflictingEnvelope,
	)
	var i ObservationDedupConflict
	err := row.Scan(
		&i.ID,
		&i.DedupKey,
		&i.TargetID,
		&i.MarketplaceAccountID,
		&i.Route,
		&i.OfferIdentity,
		&i.StoredEvidenceHash,
		&i.ConflictingEvidenceHash,
		&i.ConflictingObservationID,
		&i.ConflictingEnvelope,
		&i.DetectedAt,
	)
	return i, err
}

const insertObservation = `-- name: InsertObservation :one
INSERT INTO observations (
    captured_at, target_id, marketplace_account_id, native_variant_id,
    native_seller_id, offer_identity, route, sub_route, parser_version,
    connector_version, source_url, source_type, evidence_ref, raw_fixture_ref,
    price_raw_text, price_raw_value, price_raw_unit,
    list_price_raw_text, list_price_raw_value, list_price_raw_unit,
    availability_status, stock_signal, quality, freshness_deadline, dedup_key,
    schema_valid, identity_valid, confidence, parsing_warnings
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29
)
RETURNING id, captured_at
`

type InsertObservationParams struct {
	CapturedAt           time.Time
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	NativeVariantID      int64
	NativeSellerID       string
	OfferIdentity        string
	Route                string
	SubRoute             string
	ParserVersion        string
	ConnectorVersion     string
	SourceUrl            string
	SourceType           string
	EvidenceRef          string
	RawFixtureRef        string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	FreshnessDeadline    time.Time
	DedupKey             string
	SchemaValid          bool
	IdentityValid        bool
	Confidence           string
	ParsingWarnings      []byte
}

type InsertObservationRow struct {
	ID         uuid.UUID
	CapturedAt time.Time
}

// APPEND-ONLY evidence write (OBS-002). Every field of the evidence envelope is
// required; the domain rejects incomplete evidence before reaching here.
func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) (InsertObservationRow, error) {
	row := q.db.QueryRow(ctx, insertObservation,
		arg.CapturedAt,
		arg.TargetID,
		arg.MarketplaceAccountID,
		arg.NativeVariantID,
		arg.NativeSellerID,
		arg.OfferIdentity,
		arg.Route,
		arg.SubRoute,
		arg.ParserVersion,
		arg.ConnectorVersion,
		arg.SourceUrl,
		arg.SourceType,
		arg.EvidenceRef,
		arg.RawFixtureRef,
		arg.PriceRawText,
		arg.PriceRawValue,
		arg.PriceRawUnit,
		arg.ListPriceRawText,
		arg.ListPriceRawValue,
		arg.ListPriceRawUnit,
		arg.AvailabilityStatus,
		arg.StockSignal,
		arg.Quality,
		arg.FreshnessDeadline,
		arg.DedupKey,
		arg.SchemaValid,
		arg.IdentityValid,
		arg.Confidence,
		arg.ParsingWarnings,
	)
	var i InsertObservationRow
	err := row.Scan(&i.ID, &i.CapturedAt)
	return i, err
}

const insertObservationTarget = `-- name: InsertObservationTarget :one

INSERT INTO observation_targets (
    marketplace_account_id, identity_id, variant_id, native_variant_id,
    native_product_id, tier, cadence_seconds, freshness_deadline_seconds
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at
`

type InsertObservationTargetParams struct {
	MarketplaceAccountID     uuid.UUID
	IdentityID               uuid.UUID
	VariantID                uuid.UUID
	NativeVariantID          int64
	NativeProductID          int64
	Tier                     string
	CadenceSeconds           int32
	FreshnessDeadlineSeconds int32
}

// Observation store queries (PRD §7.3, §10.3, §16). Two write disciplines:
//   - observations + observation_dedup are APPEND-ONLY — there is deliberately NO
//     UPDATE or DELETE query here (never-cut invariant).
//   - observation_targets and observed_offers are current-state projections;
//     observed_offers is the derived current view, swept and upserted, never the
//     evidence of record.
//
// Create ONE observation target. The BEFORE INSERT trigger rejects this unless
// identity_id is an active Confirmed mapping (OBS-001) — the negative test drives
// exactly this path with an unconfirmed identity and asserts the raise.
func (q *Queries) InsertObservationTarget(ctx context.Context, arg InsertObservationTargetParams) (ObservationTarget, error) {
	row := q.db.QueryRow(ctx, insertObservationTarget,
		arg.MarketplaceAccountID,
		arg.IdentityID,
		arg.VariantID,
		arg.NativeVariantID,
		arg.NativeProductID,
		arg.Tier,
		arg.CadenceSeconds,
		arg.FreshnessDeadlineSeconds,
	)
	var i ObservationTarget
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.IdentityID,
		&i.VariantID,
		&i.NativeVariantID,
		&i.NativeProductID,
		&i.Tier,
		&i.CadenceSeconds,
		&i.FreshnessDeadlineSeconds,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTargetsByTier = `-- name: ListActiveTargetsByTier :many
SELECT id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at FROM observation_targets
WHERE tier = $1 AND active = true
ORDER BY marketplace_account_id, native_variant_id
`

// Route C scheduler enumeration (S14, OBS-005/§10.2): every ACTIVE target in a
// cadence tier, across all accounts, in a stable order. A target deactivated by
// identity reopen (DeactivateObservationTargetsForIdentity) is excluded here, so
// a reopened identity stops being fetched. Ordered by account then native id so
// per-account planning/capping is a simple contiguous group.
func (q *Queries) ListActiveTargetsByTier(ctx context.Context, tier string) ([]ObservationTarget, error) {
	rows, err := q.db.Query(ctx, listActiveTargetsByTier, tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationTarget{}
	for rows.Next() {
		var i ObservationTarget
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.IdentityID,
			&i.VariantID,
			&i.NativeVariantID,
			&i.NativeProductID,
			&i.Tier,
			&i.CadenceSeconds,
			&i.FreshnessDeadlineSeconds,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConflictedObservedOffers = `-- name: ListConflictedObservedOffers :many
SELECT id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at FROM observed_offers
WHERE marketplace_account_id = $1 AND quality = 'conflicted'
ORDER BY updated_at DESC
`

// Cross-route conflicted Observed Offers (PD-3 item 8, S37 Market conflict
// banner — §16 "routes disagree → Conflicted; block"). The price of record is
// untouched; only the quality state signals the conflict.
func (q *Queries) ListConflictedObservedOffers(ctx context.Context, marketplaceAccountID uuid.UUID) ([]ObservedOffer, error) {
	rows, err := q.db.Query(ctx, listConflictedObservedOffers, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservedOffer{}
	for rows.Next() {
		var i ObservedOffer
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.MarketplaceAccountID,
			&i.OfferIdentity,
			&i.NativeVariantID,
			&i.NativeSellerID,
			&i.PriceRawText,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.ListPriceRawText,
			&i.ListPriceRawValue,
			&i.ListPriceRawUnit,
			&i.AvailabilityStatus,
			&i.StockSignal,
			&i.Quality,
			&i.CapturedAt,
			&i.FreshnessDeadline,
			&i.Routes,
			&i.LastObservationID,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDedupConflictsByTarget = `-- name: ListDedupConflictsByTarget :many
SELECT id, dedup_key, target_id, marketplace_account_id, route, offer_identity, stored_evidence_hash, conflicting_evidence_hash, conflicting_observation_id, conflicting_envelope, detected_at FROM observation_dedup_conflicts
WHERE target_id = $1
ORDER BY detected_at DESC
LIMIT $2
`

type ListDedupConflictsByTargetParams struct {
	TargetID uuid.UUID
	Limit    int32
}

// Append-only dedup conflicts for a target, newest first (review/introspection).
func (q *Queries) ListDedupConflictsByTarget(ctx context.Context, arg ListDedupConflictsByTargetParams) ([]ObservationDedupConflict, error) {
	rows, err := q.db.Query(ctx, listDedupConflictsByTarget, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationDedupConflict{}
	for rows.Next() {
		var i ObservationDedupConflict
		if err := rows.Scan(
			&i.ID,
			&i.DedupKey,
			&i.TargetID,
			&i.MarketplaceAccountID,
			&i.Route,
			&i.OfferIdentity,
			&i.StoredEvidenceHash,
			&i.ConflictingEvidenceHash,
			&i.ConflictingObservationID,
			&i.ConflictingEnvelope,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInWindowRouteValues = `-- name: ListInWindowRouteValues :many
SELECT DISTINCT ON (route)
    route, price_raw_value, price_raw_unit, availability_status, freshness_deadline, captured_at
FROM observations
WHERE target_id = $1 AND offer_identity = $2 AND freshness_deadline > $3
  AND schema_valid = true
ORDER BY route, captured_at DESC
`

type ListInWindowRouteValuesParams struct {
	TargetID          uuid.UUID
	OfferIdentity     string
	FreshnessDeadline time.Time
}

type ListInWindowRouteValuesRow struct {
	Route              string
	PriceRawValue      string
	PriceRawUnit       string
	AvailabilityStatus string
	FreshnessDeadline  time.Time
	CapturedAt         time.Time
}

// OBS-003/§16 cross-route analysis from APPEND-ONLY evidence. For one offer,
// returns the LATEST observation per route that is STILL IN WINDOW at :now
// (freshness_deadline > now) — i.e. the routes whose evidence is currently fresh,
// with the value each currently attests. The domain derives Verified (a DIFFERENT
// route agreeing within window), Conflicted (a different route disagreeing within
// window), and recent history (a prior in-window sighting) from this — never from
// a retained string set that has no per-route freshness.
// Only schema_valid rows qualify (#154): a capture from an UNKNOWN/retired/malformed
// parser is persisted append-only with schema_valid=false and MUST NOT contribute
// qualifying history or corroboration to any other capture — "unknown never enables".
func (q *Queries) ListInWindowRouteValues(ctx context.Context, arg ListInWindowRouteValuesParams) ([]ListInWindowRouteValuesRow, error) {
	rows, err := q.db.Query(ctx, listInWindowRouteValues, arg.TargetID, arg.OfferIdentity, arg.FreshnessDeadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInWindowRouteValuesRow{}
	for rows.Next() {
		var i ListInWindowRouteValuesRow
		if err := rows.Scan(
			&i.Route,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.AvailabilityStatus,
			&i.FreshnessDeadline,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationCursorsByTarget = `-- name: ListObservationCursorsByTarget :many
SELECT target_id, marketplace_account_id, native_seller_id, offer_identity, last_observation_id, last_captured_at, last_price_raw_value, updated_at FROM observation_consumer_cursors
WHERE target_id = $1
`

// Every durable stream cursor for a target, so the producer can seed each stream's
// pairing anchor ("before") from the last consumed observation's raw value.
func (q *Queries) ListObservationCursorsByTarget(ctx context.Context, targetID uuid.UUID) ([]ObservationConsumerCursor, error) {
	rows, err := q.db.Query(ctx, listObservationCursorsByTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationConsumerCursor{}
	for rows.Next() {
		var i ObservationConsumerCursor
		if err := rows.Scan(
			&i.TargetID,
			&i.MarketplaceAccountID,
			&i.NativeSellerID,
			&i.OfferIdentity,
			&i.LastObservationID,
			&i.LastCapturedAt,
			&i.LastPriceRawValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationTargets = `-- name: ListObservationTargets :many
SELECT id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at FROM observation_targets
WHERE marketplace_account_id = $1 AND active = true
ORDER BY native_variant_id
`

func (q *Queries) ListObservationTargets(ctx context.Context, marketplaceAccountID uuid.UUID) ([]ObservationTarget, error) {
	rows, err := q.db.Query(ctx, listObservationTargets, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationTarget{}
	for rows.Next() {
		var i ObservationTarget
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.IdentityID,
			&i.VariantID,
			&i.NativeVariantID,
			&i.NativeProductID,
			&i.Tier,
			&i.CadenceSeconds,
			&i.FreshnessDeadlineSeconds,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByTarget = `-- name: ListObservationsByTarget :many
SELECT id, captured_at, target_id, marketplace_account_id, native_variant_id, native_seller_id, offer_identity, route, sub_route, parser_version, connector_version, source_url, source_type, evidence_ref, raw_fixture_ref, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, freshness_deadline, dedup_key, schema_valid, identity_valid, confidence, parsing_warnings FROM observations
WHERE target_id = $1
ORDER BY captured_at DESC
LIMIT $2
`

type ListObservationsByTargetParams struct {
	TargetID uuid.UUID
	Limit    int32
}

// Append-only evidence, newest first (bounded by the caller).
func (q *Queries) ListObservationsByTarget(ctx context.Context, arg ListObservationsByTargetParams) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsByTarget, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.CapturedAt,
			&i.TargetID,
			&i.MarketplaceAccountID,
			&i.NativeVariantID,
			&i.NativeSellerID,
			&i.OfferIdentity,
			&i.Route,
			&i.SubRoute,
			&i.ParserVersion,
			&i.ConnectorVersion,
			&i.SourceUrl,
			&i.SourceType,
			&i.EvidenceRef,
			&i.RawFixtureRef,
			&i.PriceRawText,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.ListPriceRawText,
			&i.ListPriceRawValue,
			&i.ListPriceRawUnit,
			&i.AvailabilityStatus,
			&i.StockSignal,
			&i.Quality,
			&i.FreshnessDeadline,
			&i.DedupKey,
			&i.SchemaValid,
			&i.IdentityValid,
			&i.Confidence,
			&i.ParsingWarnings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByTargetForAccount = `-- name: ListObservationsByTargetForAccount :many
SELECT id, captured_at, target_id, marketplace_account_id, native_variant_id, native_seller_id, offer_identity, route, sub_route, parser_version, connector_version, source_url, source_type, evidence_ref, raw_fixture_ref, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, freshness_deadline, dedup_key, schema_valid, identity_valid, confidence, parsing_warnings FROM observations
WHERE target_id = $1 AND marketplace_account_id = $2
ORDER BY captured_at DESC
LIMIT $3
`

type ListObservationsByTargetForAccountParams struct {
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	Limit                int32
}

// TENANT-SCOPED append-only evidence read (issue #131, identity/tenant quarantine
// §4.6). Identical to ListObservationsByTarget but the caller's RESOLVED marketplace
// account (derived from its authenticated organization, never a request param) bounds
// the read: a target owned by another organization matches NO rows, so a foreign
// target is indistinguishable from a target with no evidence (uniform empty result,
// no existence oracle). Newest first, bounded by the caller.
func (q *Queries) ListObservationsByTargetForAccount(ctx context.Context, arg ListObservationsByTargetForAccountParams) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsByTargetForAccount, arg.TargetID, arg.MarketplaceAccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.CapturedAt,
			&i.TargetID,
			&i.MarketplaceAccountID,
			&i.NativeVariantID,
			&i.NativeSellerID,
			&i.OfferIdentity,
			&i.Route,
			&i.SubRoute,
			&i.ParserVersion,
			&i.ConnectorVersion,
			&i.SourceUrl,
			&i.SourceType,
			&i.EvidenceRef,
			&i.RawFixtureRef,
			&i.PriceRawText,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.ListPriceRawText,
			&i.ListPriceRawValue,
			&i.ListPriceRawUnit,
			&i.AvailabilityStatus,
			&i.StockSignal,
			&i.Quality,
			&i.FreshnessDeadline,
			&i.DedupKey,
			&i.SchemaValid,
			&i.IdentityValid,
			&i.Confidence,
			&i.ParsingWarnings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservedOffers = `-- name: ListObservedOffers :many
SELECT id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at FROM observed_offers
WHERE marketplace_account_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListObservedOffers(ctx context.Context, marketplaceAccountID uuid.UUID) ([]ObservedOffer, error) {
	rows, err := q.db.Query(ctx, listObservedOffers, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservedOffer{}
	for rows.Next() {
		var i ObservedOffer
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.MarketplaceAccountID,
			&i.OfferIdentity,
			&i.NativeVariantID,
			&i.NativeSellerID,
			&i.PriceRawText,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.ListPriceRawText,
			&i.ListPriceRawValue,
			&i.ListPriceRawUnit,
			&i.AvailabilityStatus,
			&i.StockSignal,
			&i.Quality,
			&i.CapturedAt,
			&i.FreshnessDeadline,
			&i.Routes,
			&i.LastObservationID,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconsumedObservationsByTarget = `-- name: ListUnconsumedObservationsByTarget :many
SELECT o.id, o.captured_at, o.native_seller_id, o.offer_identity,
       o.price_raw_value, o.price_raw_unit, o.quality, o.evidence_ref
FROM (
    SELECT DISTINCT so.native_seller_id, so.offer_identity
    FROM observations so
    WHERE so.target_id = $1
      AND so.native_seller_id <> $2
) s
CROSS JOIN LATERAL (
    SELECT ob.id, ob.captured_at, ob.native_seller_id, ob.offer_identity,
           ob.price_raw_value, ob.price_raw_unit, ob.quality, ob.evidence_ref
    FROM observations ob
    LEFT JOIN observation_consumer_cursors c
           ON c.target_id = ob.target_id
          AND c.native_seller_id = ob.native_seller_id
          AND c.offer_identity = ob.offer_identity
    WHERE ob.target_id = $1
      AND ob.native_seller_id = s.native_seller_id
      AND ob.offer_identity = s.offer_identity
      AND (
            c.last_captured_at IS NULL
         OR ob.captured_at > c.last_captured_at
         OR (ob.captured_at = c.last_captured_at AND ob.id > c.last_observation_id)
          )
    ORDER BY ob.captured_at, ob.id
    LIMIT $3::int
) o
ORDER BY o.native_seller_id, o.offer_identity, o.captured_at, o.id
`

type ListUnconsumedObservationsByTargetParams struct {
	TargetID    uuid.UUID
	OwnedSeller string
	PageLimit   int32
}

type ListUnconsumedObservationsByTargetRow struct {
	ID             uuid.UUID
	CapturedAt     time.Time
	NativeSellerID string
	OfferIdentity  string
	PriceRawValue  string
	PriceRawUnit   string
	Quality        string
	EvidenceRef    string
}

// Durable, FAIRLY-PAGED forward drain for the market-event producer (issue #212 +
// REOPEN residual). Returns the target's append-only observations that lie STRICTLY
// AFTER each stream's durable consumer cursor, oldest-first per stream. A stream is
// (native_seller_id, offer_identity); the LEFT JOIN gives the stream's cursor (NULL
// when never consumed) and the (captured_at, id) tie-break makes "after" deterministic
// for equal timestamps. Seller identity is part of the stream key, so a reused offer
// identity across two sellers is TWO streams and is never paired.
//
// FAIRNESS (REOPEN residual): the per-pass bound is applied PER STREAM via a
// ROW_NUMBER window PARTITIONED by (native_seller_id, offer_identity), NOT as one
// global LIMIT over the whole target. A single high-backlog earlier-sorting seller can
// therefore NEVER monopolise the drain and starve later sellers: every stream advances
// by up to :page_limit of its own oldest-unconsumed observations each pass, so every
// seller stream makes progress within bounded passes. Total per-pass work stays bounded
// (page_limit × the target's naturally-bounded set of competing streams), and the
// durable cursor still provides continuation across passes (no fixed latest-N window).
// The owned seller's own stream is excluded here (sqlc.arg(owned_seller)) so it never
// consumes any per-stream budget — EVT-001 type 2 is a COMPETITOR movement, and the
// caller has already validated owned_seller as an authoritative decimal id.
// Ordered by (native_seller_id, offer_identity, captured_at, id) so the caller groups
// by stream and walks each in captured order. The per-stream slice is a CROSS JOIN
// LATERAL with its OWN LIMIT :page_limit, driven by the target's DISTINCT competing
// streams — the same bounded-per-group idiom the catalog streak read uses — so the
// built-in analyzer resolves the shape and no single seller can exhaust a shared page.
func (q *Queries) ListUnconsumedObservationsByTarget(ctx context.Context, arg ListUnconsumedObservationsByTargetParams) ([]ListUnconsumedObservationsByTargetRow, error) {
	rows, err := q.db.Query(ctx, listUnconsumedObservationsByTarget, arg.TargetID, arg.OwnedSeller, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnconsumedObservationsByTargetRow{}
	for rows.Next() {
		var i ListUnconsumedObservationsByTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.CapturedAt,
			&i.NativeSellerID,
			&i.OfferIdentity,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.Quality,
			&i.EvidenceRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpiredObservedOffersStale = `-- name: MarkExpiredObservedOffersStale :execrows
UPDATE observed_offers SET
    quality    = 'stale',
    updated_at = now()
WHERE marketplace_account_id = $1
  AND ended_at IS NULL
  AND freshness_deadline < $2
  AND quality NOT IN ('stale', 'unavailable')
`

type MarkExpiredObservedOffersStaleParams struct {
	MarketplaceAccountID uuid.UUID
	FreshnessDeadline    time.Time
}

// OBS-004 expiry sweep on the derived current view: any live offer past its
// freshness deadline becomes Stale (renders age-only, never satisfies a
// current-data gate — that decision is in the domain). Closed offers are left as
// Unavailable. Evidence rows are untouched (append-only).
func (q *Queries) MarkExpiredObservedOffersStale(ctx context.Context, arg MarkExpiredObservedOffersStaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, markExpiredObservedOffersStale, arg.MarketplaceAccountID, arg.FreshnessDeadline)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markObservedOfferConflicted = `-- name: MarkObservedOfferConflicted :one
UPDATE observed_offers SET
    quality             = 'conflicted',
    last_observation_id = $2,
    updated_at          = now()
WHERE target_id = $1 AND offer_identity = $3
RETURNING id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at
`

type MarkObservedOfferConflictedParams struct {
	TargetID          uuid.UUID
	LastObservationID uuid.UUID
	OfferIdentity     string
}

// §16 "Routes disagree → Conflicted; block". A newer disagreeing value must NOT
// silently overwrite the current offer: the price/availability of record are LEFT
// INTACT and only the quality is set to 'conflicted' (which blocks recommend and
// execute in the §10.3 matrix). The disagreeing capture is still retained as
// append-only evidence; last_observation_id points at it for traceability.
func (q *Queries) MarkObservedOfferConflicted(ctx context.Context, arg MarkObservedOfferConflictedParams) (ObservedOffer, error) {
	row := q.db.QueryRow(ctx, markObservedOfferConflicted, arg.TargetID, arg.LastObservationID, arg.OfferIdentity)
	var i ObservedOffer
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.MarketplaceAccountID,
		&i.OfferIdentity,
		&i.NativeVariantID,
		&i.NativeSellerID,
		&i.PriceRawText,
		&i.PriceRawValue,
		&i.PriceRawUnit,
		&i.ListPriceRawText,
		&i.ListPriceRawValue,
		&i.ListPriceRawUnit,
		&i.AvailabilityStatus,
		&i.StockSignal,
		&i.Quality,
		&i.CapturedAt,
		&i.FreshnessDeadline,
		&i.Routes,
		&i.LastObservationID,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertObservedOffer = `-- name: UpsertObservedOffer :one
INSERT INTO observed_offers (
    target_id, marketplace_account_id, offer_identity, native_variant_id,
    native_seller_id, price_raw_text, price_raw_value, price_raw_unit,
    list_price_raw_text, list_price_raw_value, list_price_raw_unit,
    availability_status, stock_signal, quality, captured_at, freshness_deadline,
    routes, last_observation_id, ended_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, NULL
)
ON CONFLICT (target_id, offer_identity) DO UPDATE SET
    native_seller_id     = EXCLUDED.native_seller_id,
    price_raw_text       = EXCLUDED.price_raw_text,
    price_raw_value      = EXCLUDED.price_raw_value,
    price_raw_unit       = EXCLUDED.price_raw_unit,
    list_price_raw_text  = EXCLUDED.list_price_raw_text,
    list_price_raw_value = EXCLUDED.list_price_raw_value,
    list_price_raw_unit  = EXCLUDED.list_price_raw_unit,
    availability_status  = EXCLUDED.availability_status,
    stock_signal         = EXCLUDED.stock_signal,
    quality              = EXCLUDED.quality,
    captured_at          = EXCLUDED.captured_at,
    freshness_deadline   = EXCLUDED.freshness_deadline,
    routes               = EXCLUDED.routes,
    last_observation_id  = EXCLUDED.last_observation_id,
    ended_at             = NULL,
    updated_at           = now()
RETURNING id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at
`

type UpsertObservedOfferParams struct {
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	OfferIdentity        string
	NativeVariantID      int64
	NativeSellerID       string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	CapturedAt           time.Time
	FreshnessDeadline    time.Time
	Routes               []byte
	LastObservationID    uuid.UUID
}

// Derived current view (OBS-008). One row per (target, offer identity); the latest
// accepted observation's fields, quality, freshness deadline, and the corroborating
// route-provenance set (computed by the domain and passed verbatim). Re-opening a
// previously closed offer clears ended_at.
func (q *Queries) UpsertObservedOffer(ctx context.Context, arg UpsertObservedOfferParams) (ObservedOffer, error) {
	row := q.db.QueryRow(ctx, upsertObservedOffer,
		arg.TargetID,
		arg.MarketplaceAccountID,
		arg.OfferIdentity,
		arg.NativeVariantID,
		arg.NativeSellerID,
		arg.PriceRawText,
		arg.PriceRawValue,
		arg.PriceRawUnit,
		arg.ListPriceRawText,
		arg.ListPriceRawValue,
		arg.ListPriceRawUnit,
		arg.AvailabilityStatus,
		arg.StockSignal,
		arg.Quality,
		arg.CapturedAt,
		arg.FreshnessDeadline,
		arg.Routes,
		arg.LastObservationID,
	)
	var i ObservedOffer
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.MarketplaceAccountID,
		&i.OfferIdentity,
		&i.NativeVariantID,
		&i.NativeSellerID,
		&i.PriceRawText,
		&i.PriceRawValue,
		&i.PriceRawUnit,
		&i.ListPriceRawText,
		&i.ListPriceRawValue,
		&i.ListPriceRawUnit,
		&i.AvailabilityStatus,
		&i.StockSignal,
		&i.Quality,
		&i.CapturedAt,
		&i.FreshnessDeadline,
		&i.Routes,
		&i.LastObservationID,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
