// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observation.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDedupKey = `-- name: ClaimDedupKey :many
INSERT INTO observation_dedup (dedup_key, target_id, route, offer_identity)
VALUES ($1, $2, $3, $4)
ON CONFLICT (dedup_key) DO NOTHING
RETURNING dedup_key, target_id, route, offer_identity, first_seen_at
`

type ClaimDedupKeyParams struct {
	DedupKey      string
	TargetID      uuid.UUID
	Route         string
	OfferIdentity string
}

// OBS-008 atomic dedup. A returned row = first sighting (accept the observation);
// an empty result = replay (dedup — create no duplicate current offer). The key
// carries the route, so a different route observing the same value is a distinct
// claim and is retained: route provenance is never collapsed away.
func (q *Queries) ClaimDedupKey(ctx context.Context, arg ClaimDedupKeyParams) ([]ObservationDedup, error) {
	rows, err := q.db.Query(ctx, claimDedupKey,
		arg.DedupKey,
		arg.TargetID,
		arg.Route,
		arg.OfferIdentity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationDedup{}
	for rows.Next() {
		var i ObservationDedup
		if err := rows.Scan(
			&i.DedupKey,
			&i.TargetID,
			&i.Route,
			&i.OfferIdentity,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeObservedOffer = `-- name: CloseObservedOffer :one
UPDATE observed_offers SET
    availability_status = 'disappeared',
    quality             = 'unavailable',
    ended_at            = $2,
    last_observation_id = $3,
    updated_at          = now()
WHERE target_id = $1 AND offer_identity = $4
RETURNING id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at
`

type CloseObservedOfferParams struct {
	TargetID          uuid.UUID
	EndedAt           pgtype.Timestamptz
	LastObservationID uuid.UUID
	OfferIdentity     string
}

// §16 offer disappearance: close the current offer with an END TIME. The last raw
// price is left intact — it is NEVER converted to a zero price. Availability
// becomes 'disappeared' and quality 'unavailable'.
func (q *Queries) CloseObservedOffer(ctx context.Context, arg CloseObservedOfferParams) (ObservedOffer, error) {
	row := q.db.QueryRow(ctx, closeObservedOffer,
		arg.TargetID,
		arg.EndedAt,
		arg.LastObservationID,
		arg.OfferIdentity,
	)
	var i ObservedOffer
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.MarketplaceAccountID,
		&i.OfferIdentity,
		&i.NativeVariantID,
		&i.NativeSellerID,
		&i.PriceRawText,
		&i.PriceRawValue,
		&i.PriceRawUnit,
		&i.ListPriceRawText,
		&i.ListPriceRawValue,
		&i.ListPriceRawUnit,
		&i.AvailabilityStatus,
		&i.StockSignal,
		&i.Quality,
		&i.CapturedAt,
		&i.FreshnessDeadline,
		&i.Routes,
		&i.LastObservationID,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveTargetsForIdentity = `-- name: CountActiveTargetsForIdentity :one
SELECT count(*) FROM observation_targets
WHERE identity_id = $1 AND active = true
`

// Test/introspection helper: how many ACTIVE targets an identity still owns.
func (q *Queries) CountActiveTargetsForIdentity(ctx context.Context, identityID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTargetsForIdentity, identityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createObservationTargetsFromConfirmed = `-- name: CreateObservationTargetsFromConfirmed :many
INSERT INTO observation_targets (
    marketplace_account_id, identity_id, variant_id, native_variant_id,
    native_product_id, tier, cadence_seconds, freshness_deadline_seconds
)
SELECT mpi.marketplace_account_id, mpi.id, mpi.variant_id, mpi.native_variant_id,
       mpi.native_product_id, $2, $3, $4
FROM market_product_identities mpi
WHERE mpi.marketplace_account_id = $1
  AND mpi.state = 'confirmed'
  AND mpi.active = true
ON CONFLICT (identity_id) DO NOTHING
RETURNING id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at
`

type CreateObservationTargetsFromConfirmedParams struct {
	MarketplaceAccountID     uuid.UUID
	Tier                     string
	CadenceSeconds           int32
	FreshnessDeadlineSeconds int32
}

// OBS-001 auto-create: a target for EXACTLY the account's active Confirmed
// mappings that do not yet have one. NeedsReview/Rejected/Obsolete are excluded by
// construction, and the trigger is a second guard. Idempotent via ON CONFLICT.
func (q *Queries) CreateObservationTargetsFromConfirmed(ctx context.Context, arg CreateObservationTargetsFromConfirmedParams) ([]ObservationTarget, error) {
	rows, err := q.db.Query(ctx, createObservationTargetsFromConfirmed,
		arg.MarketplaceAccountID,
		arg.Tier,
		arg.CadenceSeconds,
		arg.FreshnessDeadlineSeconds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationTarget{}
	for rows.Next() {
		var i ObservationTarget
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.IdentityID,
			&i.VariantID,
			&i.NativeVariantID,
			&i.NativeProductID,
			&i.Tier,
			&i.CadenceSeconds,
			&i.FreshnessDeadlineSeconds,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateObservationTargetsForIdentity = `-- name: DeactivateObservationTargetsForIdentity :many
UPDATE observation_targets SET
    active     = false,
    updated_at = now()
WHERE identity_id = $1 AND active = true
RETURNING id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at
`

// OBS-001 carry-forward from S13: when a Confirmed identity is REOPENED
// (NeedsReview/Rejected/Obsolete) its observation target must stop producing
// executable observations — an identity that has left the executable set can no
// longer own a live target. This DEACTIVATES (never deletes) the target so the
// append-only observation history and its provenance stay intact; the scheduler
// and executable-path queries filter on active = true, so a deactivated target is
// silently dropped from every fetch and recommendation. Idempotent: a re-delivery
// of the reopen event finds the target already inactive and changes nothing.
// OBS-007: this disables only the dependent capability; it never relabels the
// target's already-stored observations as current.
func (q *Queries) DeactivateObservationTargetsForIdentity(ctx context.Context, identityID uuid.UUID) ([]ObservationTarget, error) {
	rows, err := q.db.Query(ctx, deactivateObservationTargetsForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationTarget{}
	for rows.Next() {
		var i ObservationTarget
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.IdentityID,
			&i.VariantID,
			&i.NativeVariantID,
			&i.NativeProductID,
			&i.Tier,
			&i.CadenceSeconds,
			&i.FreshnessDeadlineSeconds,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObservationTarget = `-- name: GetObservationTarget :one
SELECT id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at FROM observation_targets WHERE id = $1
`

func (q *Queries) GetObservationTarget(ctx context.Context, id uuid.UUID) (ObservationTarget, error) {
	row := q.db.QueryRow(ctx, getObservationTarget, id)
	var i ObservationTarget
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.IdentityID,
		&i.VariantID,
		&i.NativeVariantID,
		&i.NativeProductID,
		&i.Tier,
		&i.CadenceSeconds,
		&i.FreshnessDeadlineSeconds,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getObservedOffer = `-- name: GetObservedOffer :one
SELECT id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at FROM observed_offers
WHERE target_id = $1 AND offer_identity = $2
`

type GetObservedOfferParams struct {
	TargetID      uuid.UUID
	OfferIdentity string
}

func (q *Queries) GetObservedOffer(ctx context.Context, arg GetObservedOfferParams) (ObservedOffer, error) {
	row := q.db.QueryRow(ctx, getObservedOffer, arg.TargetID, arg.OfferIdentity)
	var i ObservedOffer
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.MarketplaceAccountID,
		&i.OfferIdentity,
		&i.NativeVariantID,
		&i.NativeSellerID,
		&i.PriceRawText,
		&i.PriceRawValue,
		&i.PriceRawUnit,
		&i.ListPriceRawText,
		&i.ListPriceRawValue,
		&i.ListPriceRawUnit,
		&i.AvailabilityStatus,
		&i.StockSignal,
		&i.Quality,
		&i.CapturedAt,
		&i.FreshnessDeadline,
		&i.Routes,
		&i.LastObservationID,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertObservation = `-- name: InsertObservation :one
INSERT INTO observations (
    captured_at, target_id, marketplace_account_id, native_variant_id,
    native_seller_id, offer_identity, route, sub_route, parser_version,
    connector_version, source_url, source_type, evidence_ref, raw_fixture_ref,
    price_raw_text, price_raw_value, price_raw_unit,
    list_price_raw_text, list_price_raw_value, list_price_raw_unit,
    availability_status, stock_signal, quality, freshness_deadline, dedup_key,
    schema_valid, identity_valid, confidence, parsing_warnings
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29
)
RETURNING id, captured_at
`

type InsertObservationParams struct {
	CapturedAt           time.Time
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	NativeVariantID      int64
	NativeSellerID       string
	OfferIdentity        string
	Route                string
	SubRoute             string
	ParserVersion        string
	ConnectorVersion     string
	SourceUrl            string
	SourceType           string
	EvidenceRef          string
	RawFixtureRef        string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	FreshnessDeadline    time.Time
	DedupKey             string
	SchemaValid          bool
	IdentityValid        bool
	Confidence           string
	ParsingWarnings      []byte
}

type InsertObservationRow struct {
	ID         uuid.UUID
	CapturedAt time.Time
}

// APPEND-ONLY evidence write (OBS-002). Every field of the evidence envelope is
// required; the domain rejects incomplete evidence before reaching here.
func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) (InsertObservationRow, error) {
	row := q.db.QueryRow(ctx, insertObservation,
		arg.CapturedAt,
		arg.TargetID,
		arg.MarketplaceAccountID,
		arg.NativeVariantID,
		arg.NativeSellerID,
		arg.OfferIdentity,
		arg.Route,
		arg.SubRoute,
		arg.ParserVersion,
		arg.ConnectorVersion,
		arg.SourceUrl,
		arg.SourceType,
		arg.EvidenceRef,
		arg.RawFixtureRef,
		arg.PriceRawText,
		arg.PriceRawValue,
		arg.PriceRawUnit,
		arg.ListPriceRawText,
		arg.ListPriceRawValue,
		arg.ListPriceRawUnit,
		arg.AvailabilityStatus,
		arg.StockSignal,
		arg.Quality,
		arg.FreshnessDeadline,
		arg.DedupKey,
		arg.SchemaValid,
		arg.IdentityValid,
		arg.Confidence,
		arg.ParsingWarnings,
	)
	var i InsertObservationRow
	err := row.Scan(&i.ID, &i.CapturedAt)
	return i, err
}

const insertObservationTarget = `-- name: InsertObservationTarget :one

INSERT INTO observation_targets (
    marketplace_account_id, identity_id, variant_id, native_variant_id,
    native_product_id, tier, cadence_seconds, freshness_deadline_seconds
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at
`

type InsertObservationTargetParams struct {
	MarketplaceAccountID     uuid.UUID
	IdentityID               uuid.UUID
	VariantID                uuid.UUID
	NativeVariantID          int64
	NativeProductID          int64
	Tier                     string
	CadenceSeconds           int32
	FreshnessDeadlineSeconds int32
}

// Observation store queries (PRD §7.3, §10.3, §16). Two write disciplines:
//   - observations + observation_dedup are APPEND-ONLY — there is deliberately NO
//     UPDATE or DELETE query here (never-cut invariant).
//   - observation_targets and observed_offers are current-state projections;
//     observed_offers is the derived current view, swept and upserted, never the
//     evidence of record.
//
// Create ONE observation target. The BEFORE INSERT trigger rejects this unless
// identity_id is an active Confirmed mapping (OBS-001) — the negative test drives
// exactly this path with an unconfirmed identity and asserts the raise.
func (q *Queries) InsertObservationTarget(ctx context.Context, arg InsertObservationTargetParams) (ObservationTarget, error) {
	row := q.db.QueryRow(ctx, insertObservationTarget,
		arg.MarketplaceAccountID,
		arg.IdentityID,
		arg.VariantID,
		arg.NativeVariantID,
		arg.NativeProductID,
		arg.Tier,
		arg.CadenceSeconds,
		arg.FreshnessDeadlineSeconds,
	)
	var i ObservationTarget
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.IdentityID,
		&i.VariantID,
		&i.NativeVariantID,
		&i.NativeProductID,
		&i.Tier,
		&i.CadenceSeconds,
		&i.FreshnessDeadlineSeconds,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTargetsByTier = `-- name: ListActiveTargetsByTier :many
SELECT id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at FROM observation_targets
WHERE tier = $1 AND active = true
ORDER BY marketplace_account_id, native_variant_id
`

// Route C scheduler enumeration (S14, OBS-005/§10.2): every ACTIVE target in a
// cadence tier, across all accounts, in a stable order. A target deactivated by
// identity reopen (DeactivateObservationTargetsForIdentity) is excluded here, so
// a reopened identity stops being fetched. Ordered by account then native id so
// per-account planning/capping is a simple contiguous group.
func (q *Queries) ListActiveTargetsByTier(ctx context.Context, tier string) ([]ObservationTarget, error) {
	rows, err := q.db.Query(ctx, listActiveTargetsByTier, tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationTarget{}
	for rows.Next() {
		var i ObservationTarget
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.IdentityID,
			&i.VariantID,
			&i.NativeVariantID,
			&i.NativeProductID,
			&i.Tier,
			&i.CadenceSeconds,
			&i.FreshnessDeadlineSeconds,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConflictedObservedOffers = `-- name: ListConflictedObservedOffers :many
SELECT id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at FROM observed_offers
WHERE marketplace_account_id = $1 AND quality = 'conflicted'
ORDER BY updated_at DESC
`

// Cross-route conflicted Observed Offers (PD-3 item 8, S37 Market conflict
// banner — §16 "routes disagree → Conflicted; block"). The price of record is
// untouched; only the quality state signals the conflict.
func (q *Queries) ListConflictedObservedOffers(ctx context.Context, marketplaceAccountID uuid.UUID) ([]ObservedOffer, error) {
	rows, err := q.db.Query(ctx, listConflictedObservedOffers, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservedOffer{}
	for rows.Next() {
		var i ObservedOffer
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.MarketplaceAccountID,
			&i.OfferIdentity,
			&i.NativeVariantID,
			&i.NativeSellerID,
			&i.PriceRawText,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.ListPriceRawText,
			&i.ListPriceRawValue,
			&i.ListPriceRawUnit,
			&i.AvailabilityStatus,
			&i.StockSignal,
			&i.Quality,
			&i.CapturedAt,
			&i.FreshnessDeadline,
			&i.Routes,
			&i.LastObservationID,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInWindowRouteValues = `-- name: ListInWindowRouteValues :many
SELECT DISTINCT ON (route)
    route, price_raw_value, price_raw_unit, availability_status, freshness_deadline, captured_at
FROM observations
WHERE target_id = $1 AND offer_identity = $2 AND freshness_deadline > $3
ORDER BY route, captured_at DESC
`

type ListInWindowRouteValuesParams struct {
	TargetID          uuid.UUID
	OfferIdentity     string
	FreshnessDeadline time.Time
}

type ListInWindowRouteValuesRow struct {
	Route              string
	PriceRawValue      string
	PriceRawUnit       string
	AvailabilityStatus string
	FreshnessDeadline  time.Time
	CapturedAt         time.Time
}

// OBS-003/§16 cross-route analysis from APPEND-ONLY evidence. For one offer,
// returns the LATEST observation per route that is STILL IN WINDOW at :now
// (freshness_deadline > now) — i.e. the routes whose evidence is currently fresh,
// with the value each currently attests. The domain derives Verified (a DIFFERENT
// route agreeing within window), Conflicted (a different route disagreeing within
// window), and recent history (a prior in-window sighting) from this — never from
// a retained string set that has no per-route freshness.
func (q *Queries) ListInWindowRouteValues(ctx context.Context, arg ListInWindowRouteValuesParams) ([]ListInWindowRouteValuesRow, error) {
	rows, err := q.db.Query(ctx, listInWindowRouteValues, arg.TargetID, arg.OfferIdentity, arg.FreshnessDeadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInWindowRouteValuesRow{}
	for rows.Next() {
		var i ListInWindowRouteValuesRow
		if err := rows.Scan(
			&i.Route,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.AvailabilityStatus,
			&i.FreshnessDeadline,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationTargets = `-- name: ListObservationTargets :many
SELECT id, marketplace_account_id, identity_id, variant_id, native_variant_id, native_product_id, tier, cadence_seconds, freshness_deadline_seconds, active, created_at, updated_at FROM observation_targets
WHERE marketplace_account_id = $1 AND active = true
ORDER BY native_variant_id
`

func (q *Queries) ListObservationTargets(ctx context.Context, marketplaceAccountID uuid.UUID) ([]ObservationTarget, error) {
	rows, err := q.db.Query(ctx, listObservationTargets, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationTarget{}
	for rows.Next() {
		var i ObservationTarget
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.IdentityID,
			&i.VariantID,
			&i.NativeVariantID,
			&i.NativeProductID,
			&i.Tier,
			&i.CadenceSeconds,
			&i.FreshnessDeadlineSeconds,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByTarget = `-- name: ListObservationsByTarget :many
SELECT id, captured_at, target_id, marketplace_account_id, native_variant_id, native_seller_id, offer_identity, route, sub_route, parser_version, connector_version, source_url, source_type, evidence_ref, raw_fixture_ref, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, freshness_deadline, dedup_key, schema_valid, identity_valid, confidence, parsing_warnings FROM observations
WHERE target_id = $1
ORDER BY captured_at DESC
LIMIT $2
`

type ListObservationsByTargetParams struct {
	TargetID uuid.UUID
	Limit    int32
}

// Append-only evidence, newest first (bounded by the caller).
func (q *Queries) ListObservationsByTarget(ctx context.Context, arg ListObservationsByTargetParams) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsByTarget, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.CapturedAt,
			&i.TargetID,
			&i.MarketplaceAccountID,
			&i.NativeVariantID,
			&i.NativeSellerID,
			&i.OfferIdentity,
			&i.Route,
			&i.SubRoute,
			&i.ParserVersion,
			&i.ConnectorVersion,
			&i.SourceUrl,
			&i.SourceType,
			&i.EvidenceRef,
			&i.RawFixtureRef,
			&i.PriceRawText,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.ListPriceRawText,
			&i.ListPriceRawValue,
			&i.ListPriceRawUnit,
			&i.AvailabilityStatus,
			&i.StockSignal,
			&i.Quality,
			&i.FreshnessDeadline,
			&i.DedupKey,
			&i.SchemaValid,
			&i.IdentityValid,
			&i.Confidence,
			&i.ParsingWarnings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservedOffers = `-- name: ListObservedOffers :many
SELECT id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at FROM observed_offers
WHERE marketplace_account_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListObservedOffers(ctx context.Context, marketplaceAccountID uuid.UUID) ([]ObservedOffer, error) {
	rows, err := q.db.Query(ctx, listObservedOffers, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservedOffer{}
	for rows.Next() {
		var i ObservedOffer
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.MarketplaceAccountID,
			&i.OfferIdentity,
			&i.NativeVariantID,
			&i.NativeSellerID,
			&i.PriceRawText,
			&i.PriceRawValue,
			&i.PriceRawUnit,
			&i.ListPriceRawText,
			&i.ListPriceRawValue,
			&i.ListPriceRawUnit,
			&i.AvailabilityStatus,
			&i.StockSignal,
			&i.Quality,
			&i.CapturedAt,
			&i.FreshnessDeadline,
			&i.Routes,
			&i.LastObservationID,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpiredObservedOffersStale = `-- name: MarkExpiredObservedOffersStale :execrows
UPDATE observed_offers SET
    quality    = 'stale',
    updated_at = now()
WHERE marketplace_account_id = $1
  AND ended_at IS NULL
  AND freshness_deadline < $2
  AND quality NOT IN ('stale', 'unavailable')
`

type MarkExpiredObservedOffersStaleParams struct {
	MarketplaceAccountID uuid.UUID
	FreshnessDeadline    time.Time
}

// OBS-004 expiry sweep on the derived current view: any live offer past its
// freshness deadline becomes Stale (renders age-only, never satisfies a
// current-data gate — that decision is in the domain). Closed offers are left as
// Unavailable. Evidence rows are untouched (append-only).
func (q *Queries) MarkExpiredObservedOffersStale(ctx context.Context, arg MarkExpiredObservedOffersStaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, markExpiredObservedOffersStale, arg.MarketplaceAccountID, arg.FreshnessDeadline)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markObservedOfferConflicted = `-- name: MarkObservedOfferConflicted :one
UPDATE observed_offers SET
    quality             = 'conflicted',
    last_observation_id = $2,
    updated_at          = now()
WHERE target_id = $1 AND offer_identity = $3
RETURNING id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at
`

type MarkObservedOfferConflictedParams struct {
	TargetID          uuid.UUID
	LastObservationID uuid.UUID
	OfferIdentity     string
}

// §16 "Routes disagree → Conflicted; block". A newer disagreeing value must NOT
// silently overwrite the current offer: the price/availability of record are LEFT
// INTACT and only the quality is set to 'conflicted' (which blocks recommend and
// execute in the §10.3 matrix). The disagreeing capture is still retained as
// append-only evidence; last_observation_id points at it for traceability.
func (q *Queries) MarkObservedOfferConflicted(ctx context.Context, arg MarkObservedOfferConflictedParams) (ObservedOffer, error) {
	row := q.db.QueryRow(ctx, markObservedOfferConflicted, arg.TargetID, arg.LastObservationID, arg.OfferIdentity)
	var i ObservedOffer
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.MarketplaceAccountID,
		&i.OfferIdentity,
		&i.NativeVariantID,
		&i.NativeSellerID,
		&i.PriceRawText,
		&i.PriceRawValue,
		&i.PriceRawUnit,
		&i.ListPriceRawText,
		&i.ListPriceRawValue,
		&i.ListPriceRawUnit,
		&i.AvailabilityStatus,
		&i.StockSignal,
		&i.Quality,
		&i.CapturedAt,
		&i.FreshnessDeadline,
		&i.Routes,
		&i.LastObservationID,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertObservedOffer = `-- name: UpsertObservedOffer :one
INSERT INTO observed_offers (
    target_id, marketplace_account_id, offer_identity, native_variant_id,
    native_seller_id, price_raw_text, price_raw_value, price_raw_unit,
    list_price_raw_text, list_price_raw_value, list_price_raw_unit,
    availability_status, stock_signal, quality, captured_at, freshness_deadline,
    routes, last_observation_id, ended_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, NULL
)
ON CONFLICT (target_id, offer_identity) DO UPDATE SET
    native_seller_id     = EXCLUDED.native_seller_id,
    price_raw_text       = EXCLUDED.price_raw_text,
    price_raw_value      = EXCLUDED.price_raw_value,
    price_raw_unit       = EXCLUDED.price_raw_unit,
    list_price_raw_text  = EXCLUDED.list_price_raw_text,
    list_price_raw_value = EXCLUDED.list_price_raw_value,
    list_price_raw_unit  = EXCLUDED.list_price_raw_unit,
    availability_status  = EXCLUDED.availability_status,
    stock_signal         = EXCLUDED.stock_signal,
    quality              = EXCLUDED.quality,
    captured_at          = EXCLUDED.captured_at,
    freshness_deadline   = EXCLUDED.freshness_deadline,
    routes               = EXCLUDED.routes,
    last_observation_id  = EXCLUDED.last_observation_id,
    ended_at             = NULL,
    updated_at           = now()
RETURNING id, target_id, marketplace_account_id, offer_identity, native_variant_id, native_seller_id, price_raw_text, price_raw_value, price_raw_unit, list_price_raw_text, list_price_raw_value, list_price_raw_unit, availability_status, stock_signal, quality, captured_at, freshness_deadline, routes, last_observation_id, ended_at, created_at, updated_at
`

type UpsertObservedOfferParams struct {
	TargetID             uuid.UUID
	MarketplaceAccountID uuid.UUID
	OfferIdentity        string
	NativeVariantID      int64
	NativeSellerID       string
	PriceRawText         string
	PriceRawValue        string
	PriceRawUnit         string
	ListPriceRawText     string
	ListPriceRawValue    string
	ListPriceRawUnit     string
	AvailabilityStatus   string
	StockSignal          pgtype.Int8
	Quality              string
	CapturedAt           time.Time
	FreshnessDeadline    time.Time
	Routes               []byte
	LastObservationID    uuid.UUID
}

// Derived current view (OBS-008). One row per (target, offer identity); the latest
// accepted observation's fields, quality, freshness deadline, and the corroborating
// route-provenance set (computed by the domain and passed verbatim). Re-opening a
// previously closed offer clears ended_at.
func (q *Queries) UpsertObservedOffer(ctx context.Context, arg UpsertObservedOfferParams) (ObservedOffer, error) {
	row := q.db.QueryRow(ctx, upsertObservedOffer,
		arg.TargetID,
		arg.MarketplaceAccountID,
		arg.OfferIdentity,
		arg.NativeVariantID,
		arg.NativeSellerID,
		arg.PriceRawText,
		arg.PriceRawValue,
		arg.PriceRawUnit,
		arg.ListPriceRawText,
		arg.ListPriceRawValue,
		arg.ListPriceRawUnit,
		arg.AvailabilityStatus,
		arg.StockSignal,
		arg.Quality,
		arg.CapturedAt,
		arg.FreshnessDeadline,
		arg.Routes,
		arg.LastObservationID,
	)
	var i ObservedOffer
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.MarketplaceAccountID,
		&i.OfferIdentity,
		&i.NativeVariantID,
		&i.NativeSellerID,
		&i.PriceRawText,
		&i.PriceRawValue,
		&i.PriceRawUnit,
		&i.ListPriceRawText,
		&i.ListPriceRawValue,
		&i.ListPriceRawUnit,
		&i.AvailabilityStatus,
		&i.StockSignal,
		&i.Quality,
		&i.CapturedAt,
		&i.FreshnessDeadline,
		&i.Routes,
		&i.LastObservationID,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
