// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcome.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendOutcomeResult = `-- name: AppendOutcomeResult :one
INSERT INTO outcome_results (window_id, result, confidence)
VALUES ($1, $2, $3)
ON CONFLICT (window_id) DO NOTHING
RETURNING id, window_id, result, confidence, computed_at
`

type AppendOutcomeResultParams struct {
	WindowID   uuid.UUID
	Result     string
	Confidence string
}

// Append the §15.3 result + confidence at window close (once per window;
// UNIQUE(window_id)).
func (q *Queries) AppendOutcomeResult(ctx context.Context, arg AppendOutcomeResultParams) (OutcomeResult, error) {
	row := q.db.QueryRow(ctx, appendOutcomeResult, arg.WindowID, arg.Result, arg.Confidence)
	var i OutcomeResult
	err := row.Scan(
		&i.ID,
		&i.WindowID,
		&i.Result,
		&i.Confidence,
		&i.ComputedAt,
	)
	return i, err
}

const getOutcomeResult = `-- name: GetOutcomeResult :one
SELECT id, window_id, result, confidence, computed_at FROM outcome_results WHERE window_id = $1
`

func (q *Queries) GetOutcomeResult(ctx context.Context, windowID uuid.UUID) (OutcomeResult, error) {
	row := q.db.QueryRow(ctx, getOutcomeResult, windowID)
	var i OutcomeResult
	err := row.Scan(
		&i.ID,
		&i.WindowID,
		&i.Result,
		&i.Confidence,
		&i.ComputedAt,
	)
	return i, err
}

const getOutcomeWindowByAction = `-- name: GetOutcomeWindowByAction :one
SELECT id, action_id, card_id, opened_at, closes_at, created_at FROM outcome_windows WHERE action_id = $1
`

func (q *Queries) GetOutcomeWindowByAction(ctx context.Context, actionID uuid.UUID) (OutcomeWindow, error) {
	row := q.db.QueryRow(ctx, getOutcomeWindowByAction, actionID)
	var i OutcomeWindow
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.CardID,
		&i.OpenedAt,
		&i.ClosesAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOutcomeWindowByActionForAccount = `-- name: GetOutcomeWindowByActionForAccount :one
SELECT w.id, w.action_id, w.card_id, w.opened_at, w.closes_at, w.created_at
FROM outcome_windows w
JOIN approval_cards ac ON ac.id = w.card_id
WHERE w.action_id = $1 AND ac.marketplace_account_id = $2
`

type GetOutcomeWindowByActionForAccountParams struct {
	ActionID             uuid.UUID
	MarketplaceAccountID uuid.UUID
}

// Tenant-scoped outcome-window fetch (issue #102): outcome_windows carries no
// account column of its own, so it is scoped through its bound approval_cards row.
// A window whose card belongs to another account matches no row, so a foreign
// action's outcome is never disclosed.
func (q *Queries) GetOutcomeWindowByActionForAccount(ctx context.Context, arg GetOutcomeWindowByActionForAccountParams) (OutcomeWindow, error) {
	row := q.db.QueryRow(ctx, getOutcomeWindowByActionForAccount, arg.ActionID, arg.MarketplaceAccountID)
	var i OutcomeWindow
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.CardID,
		&i.OpenedAt,
		&i.ClosesAt,
		&i.CreatedAt,
	)
	return i, err
}

const listClosableOutcomeWindows = `-- name: ListClosableOutcomeWindows :many
SELECT w.id, w.action_id, w.card_id, w.opened_at, w.closes_at, w.created_at FROM outcome_windows w
LEFT JOIN outcome_results r ON r.window_id = w.id
WHERE r.id IS NULL AND w.closes_at <= $1
ORDER BY w.closes_at
`

// Windows whose seven days have elapsed and that have no computed result yet.
func (q *Queries) ListClosableOutcomeWindows(ctx context.Context, closesAt time.Time) ([]OutcomeWindow, error) {
	rows, err := q.db.Query(ctx, listClosableOutcomeWindows, closesAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutcomeWindow{}
	for rows.Next() {
		var i OutcomeWindow
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.CardID,
			&i.OpenedAt,
			&i.ClosesAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeWindowsByAccount = `-- name: ListOutcomeWindowsByAccount :many
SELECT
    w.action_id      AS action_id,
    w.card_id        AS card_id,
    w.opened_at      AS opened_at,
    w.closes_at      AS closes_at,
    r.result         AS result,
    r.confidence     AS confidence
FROM outcome_windows w
JOIN approval_cards ac ON ac.id = w.card_id
LEFT JOIN outcome_results r ON r.window_id = w.id
WHERE ac.marketplace_account_id = $1
ORDER BY w.opened_at DESC
LIMIT $2
`

type ListOutcomeWindowsByAccountParams struct {
	MarketplaceAccountID uuid.UUID
	Limit                int32
}

type ListOutcomeWindowsByAccountRow struct {
	ActionID   uuid.UUID
	CardID     pgtype.UUID
	OpenedAt   time.Time
	ClosesAt   time.Time
	Result     pgtype.Text
	Confidence pgtype.Text
}

// The account's outcome windows (PD-3 item 5, S37), newest first, with the
// §15.3 result/confidence when the window has closed (absent otherwise — never
// a fabricated Not Measurable before the window actually closes). Scoped via
// the window's bound approval_cards row (outcome_windows carries no account
// column of its own).
func (q *Queries) ListOutcomeWindowsByAccount(ctx context.Context, arg ListOutcomeWindowsByAccountParams) ([]ListOutcomeWindowsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listOutcomeWindowsByAccount, arg.MarketplaceAccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutcomeWindowsByAccountRow{}
	for rows.Next() {
		var i ListOutcomeWindowsByAccountRow
		if err := rows.Scan(
			&i.ActionID,
			&i.CardID,
			&i.OpenedAt,
			&i.ClosesAt,
			&i.Result,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openOutcomeWindow = `-- name: OpenOutcomeWindow :one

INSERT INTO outcome_windows (action_id, card_id, opened_at, closes_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (action_id) DO NOTHING
RETURNING id, action_id, card_id, opened_at, closes_at, created_at
`

type OpenOutcomeWindowParams struct {
	ActionID uuid.UUID
	CardID   pgtype.UUID
	OpenedAt time.Time
	ClosesAt time.Time
}

// Outcome window queries (PRD §7.5 OUT-001, §15.3). Both tables are APPEND-ONLY:
//   - outcome_windows — one seven-day window per reconciled action (INSERT/SELECT).
//   - outcome_results — the §15.3 result + confidence, computed once at close
//     (INSERT/SELECT). There is deliberately NO UPDATE/DELETE query on either.
//
// Open the seven-day window for a reconciled action. UNIQUE(action_id) makes this
// idempotent: a second open for the same action returns no row.
func (q *Queries) OpenOutcomeWindow(ctx context.Context, arg OpenOutcomeWindowParams) (OutcomeWindow, error) {
	row := q.db.QueryRow(ctx, openOutcomeWindow,
		arg.ActionID,
		arg.CardID,
		arg.OpenedAt,
		arg.ClosesAt,
	)
	var i OutcomeWindow
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.CardID,
		&i.OpenedAt,
		&i.ClosesAt,
		&i.CreatedAt,
	)
	return i, err
}
