// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pairing.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPairingCode = `-- name: ClaimPairingCode :one
UPDATE extension_pairings
SET credential_hash       = $2,
    credential_expires_at = $3,
    claimed_at            = now(),
    code_hash             = NULL
WHERE code_hash = $1
  AND claimed_at IS NULL
  AND revoked_at IS NULL
  AND code_expires_at > now()
RETURNING id, marketplace_account_id, code_hash, code_expires_at, credential_hash, credential_expires_at, claimed_at, revoked_at, created_at
`

type ClaimPairingCodeParams struct {
	CodeHash            pgtype.Text
	CredentialHash      pgtype.Text
	CredentialExpiresAt pgtype.Timestamptz
}

// Atomically claim an unclaimed, unexpired, unrevoked pairing code, minting the
// scoped capture credential in the same statement. The code_hash is cleared so a
// code is strictly single-use; a second claim matches no row. Returns the row
// (with credential id + expiry) only when the claim succeeds.
func (q *Queries) ClaimPairingCode(ctx context.Context, arg ClaimPairingCodeParams) (ExtensionPairing, error) {
	row := q.db.QueryRow(ctx, claimPairingCode, arg.CodeHash, arg.CredentialHash, arg.CredentialExpiresAt)
	var i ExtensionPairing
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.CodeHash,
		&i.CodeExpiresAt,
		&i.CredentialHash,
		&i.CredentialExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPairingCode = `-- name: CreatePairingCode :one
INSERT INTO extension_pairings (marketplace_account_id, code_hash, code_expires_at)
VALUES ($1, $2, $3)
RETURNING id, marketplace_account_id, code_hash, code_expires_at, credential_hash, credential_expires_at, claimed_at, revoked_at, created_at
`

type CreatePairingCodeParams struct {
	MarketplaceAccountID uuid.UUID
	CodeHash             pgtype.Text
	CodeExpiresAt        time.Time
}

// Mint a short-lived, single-use pairing code (EXT-001). code_hash is the
// SHA-256 of the raw code; the raw code is displayed to the user and never
// reaches the database.
func (q *Queries) CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) (ExtensionPairing, error) {
	row := q.db.QueryRow(ctx, createPairingCode, arg.MarketplaceAccountID, arg.CodeHash, arg.CodeExpiresAt)
	var i ExtensionPairing
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.CodeHash,
		&i.CodeExpiresAt,
		&i.CredentialHash,
		&i.CredentialExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPairings = `-- name: DeleteExpiredPairings :exec
DELETE FROM extension_pairings
WHERE code_expires_at <= now()
  AND (credential_expires_at IS NULL OR credential_expires_at <= now())
`

// Sweep pairings whose code and credential are both expired (housekeeping).
func (q *Queries) DeleteExpiredPairings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPairings)
	return err
}

const resolveCaptureCredential = `-- name: ResolveCaptureCredential :one
SELECT id, marketplace_account_id, credential_expires_at
FROM extension_pairings
WHERE credential_hash = $1
  AND revoked_at IS NULL
  AND credential_expires_at > now()
`

type ResolveCaptureCredentialRow struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
	CredentialExpiresAt  pgtype.Timestamptz
}

// Resolve a presented capture credential to its scoped account. Rows that are
// revoked or past credential expiry are excluded, so a revoked or stale
// credential fails closed (401).
func (q *Queries) ResolveCaptureCredential(ctx context.Context, credentialHash pgtype.Text) (ResolveCaptureCredentialRow, error) {
	row := q.db.QueryRow(ctx, resolveCaptureCredential, credentialHash)
	var i ResolveCaptureCredentialRow
	err := row.Scan(&i.ID, &i.MarketplaceAccountID, &i.CredentialExpiresAt)
	return i, err
}

const revokePairingsForAccount = `-- name: RevokePairingsForAccount :exec
UPDATE extension_pairings
SET revoked_at = now()
WHERE marketplace_account_id = $1
  AND revoked_at IS NULL
`

// Revoke every active capture credential for a marketplace account (EXT-001 kill
// switch). Idempotent: already-revoked rows are left unchanged.
func (q *Queries) RevokePairingsForAccount(ctx context.Context, marketplaceAccountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokePairingsForAccount, marketplaceAccountID)
	return err
}
