// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMarketplaceAccount(ctx context.Context, arg CreateMarketplaceAccountParams) (MarketplaceAccount, error)
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetMarketplaceAccount(ctx context.Context, id uuid.UUID) (MarketplaceAccount, error)
	GetMarketplaceAccountByNativeID(ctx context.Context, nativeAccountID string) (MarketplaceAccount, error)
	GetMarketplaceAccountByOrganization(ctx context.Context, organizationID uuid.UUID) (MarketplaceAccount, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListUsersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]User, error)
	RenameOrganization(ctx context.Context, arg RenameOrganizationParams) (Organization, error)
}

var _ Querier = (*Queries)(nil)
