// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Persist page progress after a page is fully applied. next_page is the resume
	// cursor an interrupted import continues from; counters accumulate.
	AdvanceCatalogSyncRun(ctx context.Context, arg AdvanceCatalogSyncRunParams) (CatalogSyncRun, error)
	CompleteCatalogSyncRun(ctx context.Context, arg CompleteCatalogSyncRunParams) (CatalogSyncRun, error)
	CountCatalogSnapshots(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error)
	// Reconciliation: owned offers not observed by the given run are drift (missing
	// from the latest full fetch). Reported, never silently deleted.
	CountDriftedOwnedOffers(ctx context.Context, arg CountDriftedOwnedOffersParams) (int64, error)
	CountListings(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error)
	CountOwnedOffers(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error)
	CountProducts(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error)
	CountVariants(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error)
	CreateCatalogSyncRun(ctx context.Context, arg CreateCatalogSyncRunParams) (CatalogSyncRun, error)
	CreateMarketplaceAccount(ctx context.Context, arg CreateMarketplaceAccountParams) (MarketplaceAccount, error)
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	// Open a server-side session. token_hash is the SHA-256 of the opaque cookie
	// token; the raw token never reaches the database.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Sweep expired sessions.
	DeleteExpiredSessions(ctx context.Context) error
	// Close a single session (logout). Idempotent: deleting an absent row is a no-op.
	DeleteSession(ctx context.Context, tokenHash string) error
	// Revoke every session for a user (role change / password rotation).
	DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error
	// Sever the connection and purge sealed tokens (ACC-001). Idempotent.
	DisconnectConnectorConnection(ctx context.Context, marketplaceAccountID uuid.UUID) (ConnectorConnection, error)
	FailCatalogSyncRun(ctx context.Context, arg FailCatalogSyncRunParams) (CatalogSyncRun, error)
	GetCatalogSyncRun(ctx context.Context, id uuid.UUID) (CatalogSyncRun, error)
	GetConnectorConnection(ctx context.Context, marketplaceAccountID uuid.UUID) (ConnectorConnection, error)
	// Backs the sync-status view the UI reads (data persisted for a later UI step).
	GetLatestCatalogSyncRun(ctx context.Context, marketplaceAccountID uuid.UUID) (CatalogSyncRun, error)
	GetMarketplaceAccount(ctx context.Context, id uuid.UUID) (MarketplaceAccount, error)
	GetMarketplaceAccountByNativeID(ctx context.Context, nativeAccountID string) (MarketplaceAccount, error)
	GetMarketplaceAccountByOrganization(ctx context.Context, organizationID uuid.UUID) (MarketplaceAccount, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	// Resolve a live session to its principal (user + role + organization). Rows
	// at/after expiry are excluded, so an expired cookie fails closed.
	GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	// Login identifier lookup. Emails are unique per organization; in P0 the beta
	// runs one organization, so this resolves the login user. A duplicate email
	// across organizations would return the earliest-created row deterministically.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserCredential(ctx context.Context, userID uuid.UUID) (UserCredential, error)
	// APPEND-ONLY: the only write path to this table is INSERT. Raw item JSON kept
	// verbatim as evidence (plan §4.7). No UPDATE/DELETE query exists by design.
	InsertCatalogPayloadSnapshot(ctx context.Context, arg InsertCatalogPayloadSnapshotParams) error
	ListConnectorCapabilities(ctx context.Context, marketplaceAccountID uuid.UUID) ([]ConnectorCapability, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListUsersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]User, error)
	RenameOrganization(ctx context.Context, arg RenameOrganizationParams) (Organization, error)
	// Return a capability to 'unknown' (disconnect). Clears last_verified_at so a
	// stale verification can never read as current.
	ResetConnectorCapability(ctx context.Context, marketplaceAccountID uuid.UUID) error
	// Insert a capability at 'unknown' if absent; leave an existing row untouched so
	// a prior probe result is not clobbered by a re-seed (capability-gating invariant).
	SeedConnectorCapability(ctx context.Context, arg SeedConnectorCapabilityParams) error
	// Record a retryable error WITHOUT marking the run failed: status stays 'running'
	// and next_page is untouched, so a retry (River backoff) resumes from the same
	// page. Used for transient fetch/apply faults (pagination fault, parser drift).
	SetCatalogSyncRunError(ctx context.Context, arg SetCatalogSyncRunErrorParams) (CatalogSyncRun, error)
	// Record a probe result. Only a probe calls this; status is set explicitly and
	// last_verified_at stamps when it was determined.
	SetConnectorCapabilityStatus(ctx context.Context, arg SetConnectorCapabilityStatusParams) (ConnectorCapability, error)
	// Establish or update the connection with sealed tokens (connect / refresh).
	UpsertConnectorConnection(ctx context.Context, arg UpsertConnectorConnectionParams) (ConnectorConnection, error)
	UpsertListing(ctx context.Context, arg UpsertListingParams) (UpsertListingRow, error)
	// Money quarantine (§9.1): price is stored ONLY as raw evidence text; there is no
	// Money/currency column and no conversion path. last_seen_run_id stamps the run
	// that observed this offer for the reconciliation drift pass.
	UpsertOwnedOffer(ctx context.Context, arg UpsertOwnedOfferParams) (UpsertOwnedOfferRow, error)
	// Catalog + owned-offer sync queries (S10, CAT-001, ACC-004/ACC-005).
	// Every canonical upsert conflicts on the stable DK native identifier so a
	// repeated or REORDERED payload replay updates in place and never inserts a
	// duplicate. The `(xmax = 0) AS inserted` flag distinguishes an INSERT from an
	// UPDATE (Postgres system-column idiom) so the sync run can count new vs changed
	// records without a second round trip.
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (UpsertProductRow, error)
	// Set or rotate a user's argon2id password hash. Current-state upsert: a
	// password change replaces the hash in place.
	UpsertUserCredential(ctx context.Context, arg UpsertUserCredentialParams) error
	UpsertVariant(ctx context.Context, arg UpsertVariantParams) (UpsertVariantRow, error)
}

var _ Querier = (*Queries)(nil)
