// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentRecommendation = `-- name: GetCurrentRecommendation :one
SELECT id, marketplace_account_id, variant_id, lineage_id, version, event_id, objective, current_price_mantissa, current_price_currency, current_price_exponent, proposed_price_available, proposed_price_mantissa, proposed_price_currency, proposed_price_exponent, proposed_price_reason, current_contribution_available, current_contribution_mantissa, current_contribution_currency, current_contribution_exponent, current_contribution_reason, proposed_contribution_available, proposed_contribution_mantissa, proposed_contribution_currency, proposed_contribution_exponent, proposed_contribution_reason, allowed_range_available, allowed_range_min_mantissa, allowed_range_max_mantissa, allowed_range_currency, allowed_range_exponent, allowed_range_reason, readiness, evidence_quality, evidence_observation_id, evidence_refs, evidence_as_of, cost_profile_version, policy_version, context_version, parameter_version, inputs, assumptions, blockers, approvable, simulation, expires_at, created_at, evidence_versions FROM recommendations
WHERE lineage_id = $1
ORDER BY version DESC
LIMIT 1
`

// The greatest-version row for a lineage (the current recommendation).
func (q *Queries) GetCurrentRecommendation(ctx context.Context, lineageID uuid.UUID) (Recommendation, error) {
	row := q.db.QueryRow(ctx, getCurrentRecommendation, lineageID)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.LineageID,
		&i.Version,
		&i.EventID,
		&i.Objective,
		&i.CurrentPriceMantissa,
		&i.CurrentPriceCurrency,
		&i.CurrentPriceExponent,
		&i.ProposedPriceAvailable,
		&i.ProposedPriceMantissa,
		&i.ProposedPriceCurrency,
		&i.ProposedPriceExponent,
		&i.ProposedPriceReason,
		&i.CurrentContributionAvailable,
		&i.CurrentContributionMantissa,
		&i.CurrentContributionCurrency,
		&i.CurrentContributionExponent,
		&i.CurrentContributionReason,
		&i.ProposedContributionAvailable,
		&i.ProposedContributionMantissa,
		&i.ProposedContributionCurrency,
		&i.ProposedContributionExponent,
		&i.ProposedContributionReason,
		&i.AllowedRangeAvailable,
		&i.AllowedRangeMinMantissa,
		&i.AllowedRangeMaxMantissa,
		&i.AllowedRangeCurrency,
		&i.AllowedRangeExponent,
		&i.AllowedRangeReason,
		&i.Readiness,
		&i.EvidenceQuality,
		&i.EvidenceObservationID,
		&i.EvidenceRefs,
		&i.EvidenceAsOf,
		&i.CostProfileVersion,
		&i.PolicyVersion,
		&i.ContextVersion,
		&i.ParameterVersion,
		&i.Inputs,
		&i.Assumptions,
		&i.Blockers,
		&i.Approvable,
		&i.Simulation,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EvidenceVersions,
	)
	return i, err
}

const getRecommendation = `-- name: GetRecommendation :one
SELECT id, marketplace_account_id, variant_id, lineage_id, version, event_id, objective, current_price_mantissa, current_price_currency, current_price_exponent, proposed_price_available, proposed_price_mantissa, proposed_price_currency, proposed_price_exponent, proposed_price_reason, current_contribution_available, current_contribution_mantissa, current_contribution_currency, current_contribution_exponent, current_contribution_reason, proposed_contribution_available, proposed_contribution_mantissa, proposed_contribution_currency, proposed_contribution_exponent, proposed_contribution_reason, allowed_range_available, allowed_range_min_mantissa, allowed_range_max_mantissa, allowed_range_currency, allowed_range_exponent, allowed_range_reason, readiness, evidence_quality, evidence_observation_id, evidence_refs, evidence_as_of, cost_profile_version, policy_version, context_version, parameter_version, inputs, assumptions, blockers, approvable, simulation, expires_at, created_at, evidence_versions FROM recommendations WHERE id = $1
`

func (q *Queries) GetRecommendation(ctx context.Context, id uuid.UUID) (Recommendation, error) {
	row := q.db.QueryRow(ctx, getRecommendation, id)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.LineageID,
		&i.Version,
		&i.EventID,
		&i.Objective,
		&i.CurrentPriceMantissa,
		&i.CurrentPriceCurrency,
		&i.CurrentPriceExponent,
		&i.ProposedPriceAvailable,
		&i.ProposedPriceMantissa,
		&i.ProposedPriceCurrency,
		&i.ProposedPriceExponent,
		&i.ProposedPriceReason,
		&i.CurrentContributionAvailable,
		&i.CurrentContributionMantissa,
		&i.CurrentContributionCurrency,
		&i.CurrentContributionExponent,
		&i.CurrentContributionReason,
		&i.ProposedContributionAvailable,
		&i.ProposedContributionMantissa,
		&i.ProposedContributionCurrency,
		&i.ProposedContributionExponent,
		&i.ProposedContributionReason,
		&i.AllowedRangeAvailable,
		&i.AllowedRangeMinMantissa,
		&i.AllowedRangeMaxMantissa,
		&i.AllowedRangeCurrency,
		&i.AllowedRangeExponent,
		&i.AllowedRangeReason,
		&i.Readiness,
		&i.EvidenceQuality,
		&i.EvidenceObservationID,
		&i.EvidenceRefs,
		&i.EvidenceAsOf,
		&i.CostProfileVersion,
		&i.PolicyVersion,
		&i.ContextVersion,
		&i.ParameterVersion,
		&i.Inputs,
		&i.Assumptions,
		&i.Blockers,
		&i.Approvable,
		&i.Simulation,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EvidenceVersions,
	)
	return i, err
}

const getRecommendationForAccount = `-- name: GetRecommendationForAccount :one
SELECT id, marketplace_account_id, variant_id, lineage_id, version, event_id, objective, current_price_mantissa, current_price_currency, current_price_exponent, proposed_price_available, proposed_price_mantissa, proposed_price_currency, proposed_price_exponent, proposed_price_reason, current_contribution_available, current_contribution_mantissa, current_contribution_currency, current_contribution_exponent, current_contribution_reason, proposed_contribution_available, proposed_contribution_mantissa, proposed_contribution_currency, proposed_contribution_exponent, proposed_contribution_reason, allowed_range_available, allowed_range_min_mantissa, allowed_range_max_mantissa, allowed_range_currency, allowed_range_exponent, allowed_range_reason, readiness, evidence_quality, evidence_observation_id, evidence_refs, evidence_as_of, cost_profile_version, policy_version, context_version, parameter_version, inputs, assumptions, blockers, approvable, simulation, expires_at, created_at, evidence_versions FROM recommendations WHERE id = $1 AND marketplace_account_id = $2
`

type GetRecommendationForAccountParams struct {
	ID                   uuid.UUID
	MarketplaceAccountID uuid.UUID
}

// Tenant-scoped recommendation fetch (issue #102): resolves a recommendation ONLY
// when it belongs to the caller's marketplace account. A recommendation owned by
// another account matches no row, so a foreign recommendation is indistinguishable
// from a missing one (no existence oracle) and is never disclosed.
func (q *Queries) GetRecommendationForAccount(ctx context.Context, arg GetRecommendationForAccountParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, getRecommendationForAccount, arg.ID, arg.MarketplaceAccountID)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.LineageID,
		&i.Version,
		&i.EventID,
		&i.Objective,
		&i.CurrentPriceMantissa,
		&i.CurrentPriceCurrency,
		&i.CurrentPriceExponent,
		&i.ProposedPriceAvailable,
		&i.ProposedPriceMantissa,
		&i.ProposedPriceCurrency,
		&i.ProposedPriceExponent,
		&i.ProposedPriceReason,
		&i.CurrentContributionAvailable,
		&i.CurrentContributionMantissa,
		&i.CurrentContributionCurrency,
		&i.CurrentContributionExponent,
		&i.CurrentContributionReason,
		&i.ProposedContributionAvailable,
		&i.ProposedContributionMantissa,
		&i.ProposedContributionCurrency,
		&i.ProposedContributionExponent,
		&i.ProposedContributionReason,
		&i.AllowedRangeAvailable,
		&i.AllowedRangeMinMantissa,
		&i.AllowedRangeMaxMantissa,
		&i.AllowedRangeCurrency,
		&i.AllowedRangeExponent,
		&i.AllowedRangeReason,
		&i.Readiness,
		&i.EvidenceQuality,
		&i.EvidenceObservationID,
		&i.EvidenceRefs,
		&i.EvidenceAsOf,
		&i.CostProfileVersion,
		&i.PolicyVersion,
		&i.ContextVersion,
		&i.ParameterVersion,
		&i.Inputs,
		&i.Assumptions,
		&i.Blockers,
		&i.Approvable,
		&i.Simulation,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EvidenceVersions,
	)
	return i, err
}

const insertRecommendation = `-- name: InsertRecommendation :one

INSERT INTO recommendations (
    marketplace_account_id, variant_id, lineage_id, version, event_id, objective,
    current_price_mantissa, current_price_currency, current_price_exponent,
    proposed_price_available, proposed_price_mantissa, proposed_price_currency, proposed_price_exponent, proposed_price_reason,
    current_contribution_available, current_contribution_mantissa, current_contribution_currency, current_contribution_exponent, current_contribution_reason,
    proposed_contribution_available, proposed_contribution_mantissa, proposed_contribution_currency, proposed_contribution_exponent, proposed_contribution_reason,
    allowed_range_available, allowed_range_min_mantissa, allowed_range_max_mantissa, allowed_range_currency, allowed_range_exponent, allowed_range_reason,
    readiness, evidence_quality, evidence_observation_id, evidence_refs, evidence_as_of,
    cost_profile_version, policy_version, context_version, parameter_version,
    inputs, assumptions, blockers, approvable, simulation, expires_at,
    evidence_versions
) VALUES (
    $1, $2, $3,
    (SELECT COALESCE(MAX(version), 0) + 1 FROM recommendations WHERE lineage_id = $3),
    $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $23,
    $24, $25, $26, $27, $28, $29,
    $30, $31, $32, $33, $34,
    $35, $36, $37, $38,
    $39, $40, $41, $42, $43, $44,
    $45
)
RETURNING id, marketplace_account_id, variant_id, lineage_id, version, event_id, objective, current_price_mantissa, current_price_currency, current_price_exponent, proposed_price_available, proposed_price_mantissa, proposed_price_currency, proposed_price_exponent, proposed_price_reason, current_contribution_available, current_contribution_mantissa, current_contribution_currency, current_contribution_exponent, current_contribution_reason, proposed_contribution_available, proposed_contribution_mantissa, proposed_contribution_currency, proposed_contribution_exponent, proposed_contribution_reason, allowed_range_available, allowed_range_min_mantissa, allowed_range_max_mantissa, allowed_range_currency, allowed_range_exponent, allowed_range_reason, readiness, evidence_quality, evidence_observation_id, evidence_refs, evidence_as_of, cost_profile_version, policy_version, context_version, parameter_version, inputs, assumptions, blockers, approvable, simulation, expires_at, created_at, evidence_versions
`

type InsertRecommendationParams struct {
	MarketplaceAccountID          uuid.UUID
	VariantID                     uuid.UUID
	LineageID                     uuid.UUID
	EventID                       pgtype.UUID
	Objective                     string
	CurrentPriceMantissa          int64
	CurrentPriceCurrency          string
	CurrentPriceExponent          int16
	ProposedPriceAvailable        bool
	ProposedPriceMantissa         pgtype.Int8
	ProposedPriceCurrency         string
	ProposedPriceExponent         int16
	ProposedPriceReason           string
	CurrentContributionAvailable  bool
	CurrentContributionMantissa   pgtype.Int8
	CurrentContributionCurrency   string
	CurrentContributionExponent   int16
	CurrentContributionReason     string
	ProposedContributionAvailable bool
	ProposedContributionMantissa  pgtype.Int8
	ProposedContributionCurrency  string
	ProposedContributionExponent  int16
	ProposedContributionReason    string
	AllowedRangeAvailable         bool
	AllowedRangeMinMantissa       pgtype.Int8
	AllowedRangeMaxMantissa       pgtype.Int8
	AllowedRangeCurrency          string
	AllowedRangeExponent          int16
	AllowedRangeReason            string
	Readiness                     string
	EvidenceQuality               string
	EvidenceObservationID         pgtype.UUID
	EvidenceRefs                  []byte
	EvidenceAsOf                  pgtype.Timestamptz
	CostProfileVersion            int64
	PolicyVersion                 int64
	ContextVersion                int64
	ParameterVersion              int64
	Inputs                        []byte
	Assumptions                   []byte
	Blockers                      []byte
	Approvable                    bool
	Simulation                    bool
	ExpiresAt                     pgtype.Timestamptz
	EvidenceVersions              []byte
}

// Recommendation queries (PRD §7.5 PRC-001/002). recommendations is APPEND-ONLY
// within a lineage: a new version is a new row whose version is the greatest in
// the lineage plus one (computed in SQL, never floated). There is NO UPDATE/DELETE
// here — the "current" recommendation is the greatest version per lineage.
func (q *Queries) InsertRecommendation(ctx context.Context, arg InsertRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, insertRecommendation,
		arg.MarketplaceAccountID,
		arg.VariantID,
		arg.LineageID,
		arg.EventID,
		arg.Objective,
		arg.CurrentPriceMantissa,
		arg.CurrentPriceCurrency,
		arg.CurrentPriceExponent,
		arg.ProposedPriceAvailable,
		arg.ProposedPriceMantissa,
		arg.ProposedPriceCurrency,
		arg.ProposedPriceExponent,
		arg.ProposedPriceReason,
		arg.CurrentContributionAvailable,
		arg.CurrentContributionMantissa,
		arg.CurrentContributionCurrency,
		arg.CurrentContributionExponent,
		arg.CurrentContributionReason,
		arg.ProposedContributionAvailable,
		arg.ProposedContributionMantissa,
		arg.ProposedContributionCurrency,
		arg.ProposedContributionExponent,
		arg.ProposedContributionReason,
		arg.AllowedRangeAvailable,
		arg.AllowedRangeMinMantissa,
		arg.AllowedRangeMaxMantissa,
		arg.AllowedRangeCurrency,
		arg.AllowedRangeExponent,
		arg.AllowedRangeReason,
		arg.Readiness,
		arg.EvidenceQuality,
		arg.EvidenceObservationID,
		arg.EvidenceRefs,
		arg.EvidenceAsOf,
		arg.CostProfileVersion,
		arg.PolicyVersion,
		arg.ContextVersion,
		arg.ParameterVersion,
		arg.Inputs,
		arg.Assumptions,
		arg.Blockers,
		arg.Approvable,
		arg.Simulation,
		arg.ExpiresAt,
		arg.EvidenceVersions,
	)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.LineageID,
		&i.Version,
		&i.EventID,
		&i.Objective,
		&i.CurrentPriceMantissa,
		&i.CurrentPriceCurrency,
		&i.CurrentPriceExponent,
		&i.ProposedPriceAvailable,
		&i.ProposedPriceMantissa,
		&i.ProposedPriceCurrency,
		&i.ProposedPriceExponent,
		&i.ProposedPriceReason,
		&i.CurrentContributionAvailable,
		&i.CurrentContributionMantissa,
		&i.CurrentContributionCurrency,
		&i.CurrentContributionExponent,
		&i.CurrentContributionReason,
		&i.ProposedContributionAvailable,
		&i.ProposedContributionMantissa,
		&i.ProposedContributionCurrency,
		&i.ProposedContributionExponent,
		&i.ProposedContributionReason,
		&i.AllowedRangeAvailable,
		&i.AllowedRangeMinMantissa,
		&i.AllowedRangeMaxMantissa,
		&i.AllowedRangeCurrency,
		&i.AllowedRangeExponent,
		&i.AllowedRangeReason,
		&i.Readiness,
		&i.EvidenceQuality,
		&i.EvidenceObservationID,
		&i.EvidenceRefs,
		&i.EvidenceAsOf,
		&i.CostProfileVersion,
		&i.PolicyVersion,
		&i.ContextVersion,
		&i.ParameterVersion,
		&i.Inputs,
		&i.Assumptions,
		&i.Blockers,
		&i.Approvable,
		&i.Simulation,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EvidenceVersions,
	)
	return i, err
}

const listRecommendationsForVariant = `-- name: ListRecommendationsForVariant :many
SELECT id, marketplace_account_id, variant_id, lineage_id, version, event_id, objective, current_price_mantissa, current_price_currency, current_price_exponent, proposed_price_available, proposed_price_mantissa, proposed_price_currency, proposed_price_exponent, proposed_price_reason, current_contribution_available, current_contribution_mantissa, current_contribution_currency, current_contribution_exponent, current_contribution_reason, proposed_contribution_available, proposed_contribution_mantissa, proposed_contribution_currency, proposed_contribution_exponent, proposed_contribution_reason, allowed_range_available, allowed_range_min_mantissa, allowed_range_max_mantissa, allowed_range_currency, allowed_range_exponent, allowed_range_reason, readiness, evidence_quality, evidence_observation_id, evidence_refs, evidence_as_of, cost_profile_version, policy_version, context_version, parameter_version, inputs, assumptions, blockers, approvable, simulation, expires_at, created_at, evidence_versions FROM recommendations
WHERE marketplace_account_id = $1 AND variant_id = $2
ORDER BY created_at DESC
`

type ListRecommendationsForVariantParams struct {
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
}

func (q *Queries) ListRecommendationsForVariant(ctx context.Context, arg ListRecommendationsForVariantParams) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendationsForVariant, arg.MarketplaceAccountID, arg.VariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recommendation{}
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.VariantID,
			&i.LineageID,
			&i.Version,
			&i.EventID,
			&i.Objective,
			&i.CurrentPriceMantissa,
			&i.CurrentPriceCurrency,
			&i.CurrentPriceExponent,
			&i.ProposedPriceAvailable,
			&i.ProposedPriceMantissa,
			&i.ProposedPriceCurrency,
			&i.ProposedPriceExponent,
			&i.ProposedPriceReason,
			&i.CurrentContributionAvailable,
			&i.CurrentContributionMantissa,
			&i.CurrentContributionCurrency,
			&i.CurrentContributionExponent,
			&i.CurrentContributionReason,
			&i.ProposedContributionAvailable,
			&i.ProposedContributionMantissa,
			&i.ProposedContributionCurrency,
			&i.ProposedContributionExponent,
			&i.ProposedContributionReason,
			&i.AllowedRangeAvailable,
			&i.AllowedRangeMinMantissa,
			&i.AllowedRangeMaxMantissa,
			&i.AllowedRangeCurrency,
			&i.AllowedRangeExponent,
			&i.AllowedRangeReason,
			&i.Readiness,
			&i.EvidenceQuality,
			&i.EvidenceObservationID,
			&i.EvidenceRefs,
			&i.EvidenceAsOf,
			&i.CostProfileVersion,
			&i.PolicyVersion,
			&i.ContextVersion,
			&i.ParameterVersion,
			&i.Inputs,
			&i.Assumptions,
			&i.Blockers,
			&i.Approvable,
			&i.Simulation,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.EvidenceVersions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
