// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routec.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const disengageAccountKillSwitch = `-- name: DisengageAccountKillSwitch :exec
DELETE FROM route_kill_switches WHERE scope = 'account' AND account_id = $1
`

func (q *Queries) DisengageAccountKillSwitch(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disengageAccountKillSwitch, accountID)
	return err
}

const disengageGlobalKillSwitch = `-- name: DisengageGlobalKillSwitch :exec
DELETE FROM route_kill_switches WHERE scope = 'global'
`

func (q *Queries) DisengageGlobalKillSwitch(ctx context.Context) error {
	_, err := q.db.Exec(ctx, disengageGlobalKillSwitch)
	return err
}

const disengageTargetKillSwitch = `-- name: DisengageTargetKillSwitch :exec
DELETE FROM route_kill_switches WHERE scope = 'target' AND target_id = $1
`

func (q *Queries) DisengageTargetKillSwitch(ctx context.Context, targetID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disengageTargetKillSwitch, targetID)
	return err
}

const engageAccountKillSwitch = `-- name: EngageAccountKillSwitch :exec
INSERT INTO route_kill_switches (scope, account_id, reason, engaged_by)
VALUES ('account', $1, $2, $3)
ON CONFLICT (account_id) WHERE scope = 'account' DO NOTHING
`

type EngageAccountKillSwitchParams struct {
	AccountID pgtype.UUID
	Reason    string
	EngagedBy pgtype.UUID
}

// Stop Route C for one account. Idempotent per account.
func (q *Queries) EngageAccountKillSwitch(ctx context.Context, arg EngageAccountKillSwitchParams) error {
	_, err := q.db.Exec(ctx, engageAccountKillSwitch, arg.AccountID, arg.Reason, arg.EngagedBy)
	return err
}

const engageGlobalKillSwitch = `-- name: EngageGlobalKillSwitch :exec

INSERT INTO route_kill_switches (scope, reason, engaged_by)
VALUES ('global', $1, $2)
ON CONFLICT ((true)) WHERE scope = 'global' DO NOTHING
`

type EngageGlobalKillSwitchParams struct {
	Reason    string
	EngagedBy pgtype.UUID
}

// Route C kill-switch queries (S14, OBS-006). route_kill_switches is a
// current-state operator control table: engage = INSERT (idempotent per layer),
// disengage = DELETE. There is no history table here; the append-only audit of
// who stopped what lives in the platform audit trail (later step). Presence of a
// row means "stopped".
// Stop ALL Route C traffic. Idempotent: a second engage is a no-op (the switch is
// already on), so an operator flipping it twice never errors.
func (q *Queries) EngageGlobalKillSwitch(ctx context.Context, arg EngageGlobalKillSwitchParams) error {
	_, err := q.db.Exec(ctx, engageGlobalKillSwitch, arg.Reason, arg.EngagedBy)
	return err
}

const engageTargetKillSwitch = `-- name: EngageTargetKillSwitch :exec
INSERT INTO route_kill_switches (scope, account_id, target_id, reason, engaged_by)
VALUES ('target', $1, $2, $3, $4)
ON CONFLICT (target_id) WHERE scope = 'target' DO NOTHING
`

type EngageTargetKillSwitchParams struct {
	AccountID pgtype.UUID
	TargetID  pgtype.UUID
	Reason    string
	EngagedBy pgtype.UUID
}

// Stop Route C for one target. Idempotent per target.
func (q *Queries) EngageTargetKillSwitch(ctx context.Context, arg EngageTargetKillSwitchParams) error {
	_, err := q.db.Exec(ctx, engageTargetKillSwitch,
		arg.AccountID,
		arg.TargetID,
		arg.Reason,
		arg.EngagedBy,
	)
	return err
}

const listEngagedKillSwitches = `-- name: ListEngagedKillSwitches :many
SELECT scope, account_id, target_id, reason, engaged_by, engaged_at
FROM route_kill_switches
ORDER BY scope, engaged_at
`

type ListEngagedKillSwitchesRow struct {
	Scope     string
	AccountID pgtype.UUID
	TargetID  pgtype.UUID
	Reason    string
	EngagedBy pgtype.UUID
	EngagedAt time.Time
}

// Load every engaged switch so the observer can evaluate the layered stop in
// process (global OR account OR target). Ordered global-first so the most
// sweeping stop is visible at the head.
func (q *Queries) ListEngagedKillSwitches(ctx context.Context) ([]ListEngagedKillSwitchesRow, error) {
	rows, err := q.db.Query(ctx, listEngagedKillSwitches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEngagedKillSwitchesRow{}
	for rows.Next() {
		var i ListEngagedKillSwitchesRow
		if err := rows.Scan(
			&i.Scope,
			&i.AccountID,
			&i.TargetID,
			&i.Reason,
			&i.EngagedBy,
			&i.EngagedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
