// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routec.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeByteBudget = `-- name: ConsumeByteBudget :exec
INSERT INTO route_budget_usage (account_id, window_key, requests_used, bytes_used)
VALUES ($1::uuid, $2::timestamptz, 0, $3::bigint)
ON CONFLICT (account_id, window_key) DO UPDATE
    SET bytes_used = route_budget_usage.bytes_used + $3::bigint,
        updated_at = now()
`

type ConsumeByteBudgetParams struct {
	AccountID uuid.UUID
	WindowKey time.Time
	Bytes     int64
}

// Reconcile the bytes a completed fetch actually transferred. This is an atomic
// increment on the current window row (never a read-then-write that could lose a
// concurrent update); it creates the row if the window has no reserve yet. Byte
// overshoot on the final reserved request is bounded by design — the request that
// pushes bytes past the ceiling was already admitted; the next reserve's byte
// predicate then denies further fetches.
func (q *Queries) ConsumeByteBudget(ctx context.Context, arg ConsumeByteBudgetParams) error {
	_, err := q.db.Exec(ctx, consumeByteBudget, arg.AccountID, arg.WindowKey, arg.Bytes)
	return err
}

const disengageAccountKillSwitch = `-- name: DisengageAccountKillSwitch :exec
DELETE FROM route_kill_switches WHERE scope = 'account' AND account_id = $1
`

func (q *Queries) DisengageAccountKillSwitch(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disengageAccountKillSwitch, accountID)
	return err
}

const disengageGlobalKillSwitch = `-- name: DisengageGlobalKillSwitch :exec
DELETE FROM route_kill_switches WHERE scope = 'global'
`

func (q *Queries) DisengageGlobalKillSwitch(ctx context.Context) error {
	_, err := q.db.Exec(ctx, disengageGlobalKillSwitch)
	return err
}

const disengageTargetKillSwitch = `-- name: DisengageTargetKillSwitch :exec
DELETE FROM route_kill_switches WHERE scope = 'target' AND target_id = $1
`

func (q *Queries) DisengageTargetKillSwitch(ctx context.Context, targetID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disengageTargetKillSwitch, targetID)
	return err
}

const engageAccountKillSwitch = `-- name: EngageAccountKillSwitch :exec
INSERT INTO route_kill_switches (scope, account_id, reason, engaged_by)
VALUES ('account', $1, $2, $3)
ON CONFLICT (account_id) WHERE scope = 'account' DO NOTHING
`

type EngageAccountKillSwitchParams struct {
	AccountID pgtype.UUID
	Reason    string
	EngagedBy pgtype.UUID
}

// Stop Route C for one account. Idempotent per account.
func (q *Queries) EngageAccountKillSwitch(ctx context.Context, arg EngageAccountKillSwitchParams) error {
	_, err := q.db.Exec(ctx, engageAccountKillSwitch, arg.AccountID, arg.Reason, arg.EngagedBy)
	return err
}

const engageGlobalKillSwitch = `-- name: EngageGlobalKillSwitch :exec

INSERT INTO route_kill_switches (scope, reason, engaged_by)
VALUES ('global', $1, $2)
ON CONFLICT ((true)) WHERE scope = 'global' DO NOTHING
`

type EngageGlobalKillSwitchParams struct {
	Reason    string
	EngagedBy pgtype.UUID
}

// Route C kill-switch queries (S14, OBS-006). route_kill_switches is a
// current-state operator control table: engage = INSERT (idempotent per layer),
// disengage = DELETE. There is no history table here; the append-only audit of
// who stopped what lives in the platform audit trail (later step). Presence of a
// row means "stopped".
// Stop ALL Route C traffic. Idempotent: a second engage is a no-op (the switch is
// already on), so an operator flipping it twice never errors.
func (q *Queries) EngageGlobalKillSwitch(ctx context.Context, arg EngageGlobalKillSwitchParams) error {
	_, err := q.db.Exec(ctx, engageGlobalKillSwitch, arg.Reason, arg.EngagedBy)
	return err
}

const engageTargetKillSwitch = `-- name: EngageTargetKillSwitch :exec
INSERT INTO route_kill_switches (scope, account_id, target_id, reason, engaged_by)
VALUES ('target', $1, $2, $3, $4)
ON CONFLICT (target_id) WHERE scope = 'target' DO NOTHING
`

type EngageTargetKillSwitchParams struct {
	AccountID pgtype.UUID
	TargetID  pgtype.UUID
	Reason    string
	EngagedBy pgtype.UUID
}

// Stop Route C for one target. Idempotent per target.
func (q *Queries) EngageTargetKillSwitch(ctx context.Context, arg EngageTargetKillSwitchParams) error {
	_, err := q.db.Exec(ctx, engageTargetKillSwitch,
		arg.AccountID,
		arg.TargetID,
		arg.Reason,
		arg.EngagedBy,
	)
	return err
}

const getBudgetUsage = `-- name: GetBudgetUsage :one
SELECT requests_used, bytes_used
FROM route_budget_usage
WHERE account_id = $1::uuid AND window_key = $2::timestamptz
`

type GetBudgetUsageParams struct {
	AccountID uuid.UUID
	WindowKey time.Time
}

type GetBudgetUsageRow struct {
	RequestsUsed int32
	BytesUsed    int64
}

// Read the durable spend for one (account, window) so the scheduler can size the
// sweep (Snapshot -> State -> PlanSweep). A missing row means the window is
// untouched: the caller treats pgx.ErrNoRows as zero spend (full headroom).
func (q *Queries) GetBudgetUsage(ctx context.Context, arg GetBudgetUsageParams) (GetBudgetUsageRow, error) {
	row := q.db.QueryRow(ctx, getBudgetUsage, arg.AccountID, arg.WindowKey)
	var i GetBudgetUsageRow
	err := row.Scan(&i.RequestsUsed, &i.BytesUsed)
	return i, err
}

const listEngagedKillSwitches = `-- name: ListEngagedKillSwitches :many
SELECT scope, account_id, target_id, reason, engaged_by, engaged_at
FROM route_kill_switches
ORDER BY scope, engaged_at
`

type ListEngagedKillSwitchesRow struct {
	Scope     string
	AccountID pgtype.UUID
	TargetID  pgtype.UUID
	Reason    string
	EngagedBy pgtype.UUID
	EngagedAt time.Time
}

// Load every engaged switch so the observer can evaluate the layered stop in
// process (global OR account OR target). Ordered global-first so the most
// sweeping stop is visible at the head.
func (q *Queries) ListEngagedKillSwitches(ctx context.Context) ([]ListEngagedKillSwitchesRow, error) {
	rows, err := q.db.Query(ctx, listEngagedKillSwitches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEngagedKillSwitchesRow{}
	for rows.Next() {
		var i ListEngagedKillSwitchesRow
		if err := rows.Scan(
			&i.Scope,
			&i.AccountID,
			&i.TargetID,
			&i.Reason,
			&i.EngagedBy,
			&i.EngagedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveRequestBudget = `-- name: ReserveRequestBudget :one

INSERT INTO route_budget_usage (account_id, window_key, requests_used, bytes_used)
SELECT $1::uuid, $2::timestamptz, 1, 0
WHERE $3::bigint > 0 AND $4::bigint > 0
ON CONFLICT (account_id, window_key) DO UPDATE
    SET requests_used = route_budget_usage.requests_used + 1,
        updated_at    = now()
    WHERE route_budget_usage.requests_used < $3::bigint
      AND route_budget_usage.bytes_used    < $4::bigint
RETURNING requests_used
`

type ReserveRequestBudgetParams struct {
	AccountID    uuid.UUID
	WindowKey    time.Time
	RequestLimit int64
	ByteLimit    int64
}

// Route C durable daily-budget accounting (issue #48). route_budget_usage holds
// one mutable counter row per (account, window bucket). Reset is bucket-key
// rollover: a new window is a new row, so these queries never DELETE or rewrite a
// prior window. The LIMITS are supplied by the caller (config-driven), not stored.
// Atomically reserve ONE request against the durable daily total. This is the
// SINGLE, conditional statement that admits: for a brand-new window it inserts
// (1,0) only when both limits leave headroom; for an existing window it bumps
// requests_used by 1 ONLY WHILE the durable count is strictly below the request
// limit AND bytes are below the byte limit. The composite PK serializes concurrent
// callers on one row, so racing the last unit admits at most the remainder. A
// denied reserve (limit reached, or a zero/negative limit) matches nothing and
// RETURNS NO ROW — the caller reads pgx.ErrNoRows as "denied" and skips the fetch.
// $3 = request limit, $4 = byte limit.
func (q *Queries) ReserveRequestBudget(ctx context.Context, arg ReserveRequestBudgetParams) (int32, error) {
	row := q.db.QueryRow(ctx, reserveRequestBudget,
		arg.AccountID,
		arg.WindowKey,
		arg.RequestLimit,
		arg.ByteLimit,
	)
	var requests_used int32
	err := row.Scan(&requests_used)
	return requests_used, err
}
