// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: selection.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSelectionSetMembers = `-- name: CountSelectionSetMembers :one
SELECT count(*) FROM selection_set_members WHERE selection_set_id = $1
`

func (q *Queries) CountSelectionSetMembers(ctx context.Context, selectionSetID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSelectionSetMembers, selectionSetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCurrentSelectionSet = `-- name: GetCurrentSelectionSet :one
SELECT id, marketplace_account_id, lineage_id, version, name, criteria, member_count, aggregate_impact_known, aggregate_impact_mantissa, aggregate_impact_currency, aggregate_impact_exponent, created_at, membership_fingerprint FROM selection_sets
WHERE lineage_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetCurrentSelectionSet(ctx context.Context, lineageID uuid.UUID) (SelectionSet, error) {
	row := q.db.QueryRow(ctx, getCurrentSelectionSet, lineageID)
	var i SelectionSet
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.LineageID,
		&i.Version,
		&i.Name,
		&i.Criteria,
		&i.MemberCount,
		&i.AggregateImpactKnown,
		&i.AggregateImpactMantissa,
		&i.AggregateImpactCurrency,
		&i.AggregateImpactExponent,
		&i.CreatedAt,
		&i.MembershipFingerprint,
	)
	return i, err
}

const getSelectionSet = `-- name: GetSelectionSet :one
SELECT id, marketplace_account_id, lineage_id, version, name, criteria, member_count, aggregate_impact_known, aggregate_impact_mantissa, aggregate_impact_currency, aggregate_impact_exponent, created_at, membership_fingerprint FROM selection_sets WHERE id = $1
`

func (q *Queries) GetSelectionSet(ctx context.Context, id uuid.UUID) (SelectionSet, error) {
	row := q.db.QueryRow(ctx, getSelectionSet, id)
	var i SelectionSet
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.LineageID,
		&i.Version,
		&i.Name,
		&i.Criteria,
		&i.MemberCount,
		&i.AggregateImpactKnown,
		&i.AggregateImpactMantissa,
		&i.AggregateImpactCurrency,
		&i.AggregateImpactExponent,
		&i.CreatedAt,
		&i.MembershipFingerprint,
	)
	return i, err
}

const insertSelectionSet = `-- name: InsertSelectionSet :one

INSERT INTO selection_sets (
    marketplace_account_id, lineage_id, version, name, criteria, member_count,
    aggregate_impact_known, aggregate_impact_mantissa, aggregate_impact_currency, aggregate_impact_exponent,
    membership_fingerprint
) VALUES (
    $1, $2,
    (SELECT COALESCE(MAX(version), 0) + 1 FROM selection_sets WHERE lineage_id = $2),
    $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, marketplace_account_id, lineage_id, version, name, criteria, member_count, aggregate_impact_known, aggregate_impact_mantissa, aggregate_impact_currency, aggregate_impact_exponent, created_at, membership_fingerprint
`

type InsertSelectionSetParams struct {
	MarketplaceAccountID    uuid.UUID
	LineageID               uuid.UUID
	Name                    string
	Criteria                []byte
	MemberCount             int32
	AggregateImpactKnown    bool
	AggregateImpactMantissa pgtype.Int8
	AggregateImpactCurrency string
	AggregateImpactExponent int16
	MembershipFingerprint   []byte
}

// Selection-set queries (PRD §7.5, CHAT-050/051). selection_sets is APPEND-ONLY
// within a lineage: a set change is a new version. A bulk approval binds ONE
// version, so any set/evidence change (a new version) invalidates it. No
// UPDATE/DELETE — the current set is the greatest version per lineage.
// membership_fingerprint is the canonical hash of the exact membership + aggregate
// computed by the atomic create BEFORE any write. It is set once at INSERT and never
// UPDATEd (selection_sets is append-only), so a version's fingerprint is immutable —
// binding the version at confirm transitively binds this fingerprint (issue #91).
func (q *Queries) InsertSelectionSet(ctx context.Context, arg InsertSelectionSetParams) (SelectionSet, error) {
	row := q.db.QueryRow(ctx, insertSelectionSet,
		arg.MarketplaceAccountID,
		arg.LineageID,
		arg.Name,
		arg.Criteria,
		arg.MemberCount,
		arg.AggregateImpactKnown,
		arg.AggregateImpactMantissa,
		arg.AggregateImpactCurrency,
		arg.AggregateImpactExponent,
		arg.MembershipFingerprint,
	)
	var i SelectionSet
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.LineageID,
		&i.Version,
		&i.Name,
		&i.Criteria,
		&i.MemberCount,
		&i.AggregateImpactKnown,
		&i.AggregateImpactMantissa,
		&i.AggregateImpactCurrency,
		&i.AggregateImpactExponent,
		&i.CreatedAt,
		&i.MembershipFingerprint,
	)
	return i, err
}

const insertSelectionSetMember = `-- name: InsertSelectionSetMember :one
INSERT INTO selection_set_members (
    selection_set_id, variant_id, recommendation_id, disposition
) VALUES ($1, $2, $3, $4)
RETURNING id, selection_set_id, variant_id, recommendation_id, disposition, created_at
`

type InsertSelectionSetMemberParams struct {
	SelectionSetID   uuid.UUID
	VariantID        uuid.UUID
	RecommendationID pgtype.UUID
	Disposition      string
}

func (q *Queries) InsertSelectionSetMember(ctx context.Context, arg InsertSelectionSetMemberParams) (SelectionSetMember, error) {
	row := q.db.QueryRow(ctx, insertSelectionSetMember,
		arg.SelectionSetID,
		arg.VariantID,
		arg.RecommendationID,
		arg.Disposition,
	)
	var i SelectionSetMember
	err := row.Scan(
		&i.ID,
		&i.SelectionSetID,
		&i.VariantID,
		&i.RecommendationID,
		&i.Disposition,
		&i.CreatedAt,
	)
	return i, err
}

const listSelectionSetMembers = `-- name: ListSelectionSetMembers :many
SELECT id, selection_set_id, variant_id, recommendation_id, disposition, created_at FROM selection_set_members
WHERE selection_set_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListSelectionSetMembers(ctx context.Context, selectionSetID uuid.UUID) ([]SelectionSetMember, error) {
	rows, err := q.db.Query(ctx, listSelectionSetMembers, selectionSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectionSetMember{}
	for rows.Next() {
		var i SelectionSetMember
		if err := rows.Scan(
			&i.ID,
			&i.SelectionSetID,
			&i.VariantID,
			&i.RecommendationID,
			&i.Disposition,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
