// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (organization_id, email, role)
VALUES ($1, email_canonical($2), $3)
RETURNING id, organization_id, email, role, created_at, updated_at
`

type CreateUserParams struct {
	OrganizationID uuid.UUID
	Email          string
	Role           string
}

// Email is stored in its canonical (normalized) form via email_canonical() —
// the SINGLE SQL canonicalizer (migration 0034) that reproduces Go's
// internal/normalize.Email (full Unicode White_Space trim + case-fold) EXACTLY.
// The same expression backs the users_email_canonical_key unique index and the
// GetUserByEmail lookup, so write, uniqueness, and login share one definition
// with no divergence. Normalizing in SQL guarantees write-time canonicalization
// for every caller, not just those that remembered to normalize first.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.OrganizationID, arg.Email, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, organization_id, email, role, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, organization_id, email, role, created_at, updated_at FROM users
WHERE email_canonical(email) = email_canonical($1)
`

// Login identifier lookup (issue #12, #201). Both sides run through the SAME
// email_canonical() the write path and unique index use, so the lookup can never
// diverge from storage/uniqueness (the divergence between Go TrimSpace and SQL
// 1-arg btrim that let a padded id resolve another org's row is closed). Wrapping
// the argument too makes the DB the enforcement authority even if the caller's
// pre-normalization ever drifted. Normalized email is GLOBALLY unique (the
// users_email_canonical_key functional index), so this resolves at most one
// principal — and therefore exactly one organization — using that unique index,
// deterministically, with no LIMIT 1 tie-break masking an ambiguous match.
func (q *Queries) GetUserByEmail(ctx context.Context, addr string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, addr)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByOrganization = `-- name: ListUsersByOrganization :many
SELECT id, organization_id, email, role, created_at, updated_at FROM users
WHERE organization_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListUsersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
