// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchlist.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countWatchlistEntries = `-- name: CountWatchlistEntries :one

SELECT count(*) FROM watchlist_entries WHERE marketplace_account_id = $1
`

// EXT-007 priority watchlist (S37). Add is idempotent (ON CONFLICT DO NOTHING —
// a duplicate variant returns no new row, never a second entry and never an
// error); the cap is enforced in Go (internal/watchlist) BEFORE the insert, from
// CountWatchlistEntries, so the insert itself never needs to race a check
// constraint.
func (q *Queries) CountWatchlistEntries(ctx context.Context, marketplaceAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWatchlistEntries, marketplaceAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWatchlistEntry = `-- name: GetWatchlistEntry :one
SELECT id, marketplace_account_id, variant_id, added_by, created_at FROM watchlist_entries WHERE marketplace_account_id = $1 AND variant_id = $2
`

type GetWatchlistEntryParams struct {
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
}

func (q *Queries) GetWatchlistEntry(ctx context.Context, arg GetWatchlistEntryParams) (WatchlistEntry, error) {
	row := q.db.QueryRow(ctx, getWatchlistEntry, arg.MarketplaceAccountID, arg.VariantID)
	var i WatchlistEntry
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertWatchlistEntry = `-- name: InsertWatchlistEntry :one
INSERT INTO watchlist_entries (marketplace_account_id, variant_id, added_by)
VALUES ($1, $2, $3)
ON CONFLICT (marketplace_account_id, variant_id) DO NOTHING
RETURNING id, marketplace_account_id, variant_id, added_by, created_at
`

type InsertWatchlistEntryParams struct {
	MarketplaceAccountID uuid.UUID
	VariantID            uuid.UUID
	AddedBy              string
}

func (q *Queries) InsertWatchlistEntry(ctx context.Context, arg InsertWatchlistEntryParams) (WatchlistEntry, error) {
	row := q.db.QueryRow(ctx, insertWatchlistEntry, arg.MarketplaceAccountID, arg.VariantID, arg.AddedBy)
	var i WatchlistEntry
	err := row.Scan(
		&i.ID,
		&i.MarketplaceAccountID,
		&i.VariantID,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listWatchlistEntries = `-- name: ListWatchlistEntries :many
SELECT id, marketplace_account_id, variant_id, added_by, created_at FROM watchlist_entries
WHERE marketplace_account_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWatchlistEntries(ctx context.Context, marketplaceAccountID uuid.UUID) ([]WatchlistEntry, error) {
	rows, err := q.db.Query(ctx, listWatchlistEntries, marketplaceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchlistEntry{}
	for rows.Next() {
		var i WatchlistEntry
		if err := rows.Scan(
			&i.ID,
			&i.MarketplaceAccountID,
			&i.VariantID,
			&i.AddedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
